const adminState={query:'',folder:0,toggle:true,invitationFilterOpen:'協作原因',invitationFilterQuery:'',invitationFilters:{},invitationSelected:[],invitationDate:'',contactTab:'vendor',contactFilterOpen:'',contactFilterQuery:'',contactFilters:{},contactQuery:'',alertSettingsTab:'scope',folderFilterOpen:'擁有者'};
const contactRows=[['精誠資訊','Demo9','demo9@example-info.test','2026/08/25']];
function adminToolbar(title,count,action){return `<div class="admin-toolbar"><input id="adminSearch" value="${e(adminState.query)}" placeholder="搜尋${title}…"><span>${count} 筆</span><button class="outline" data-toast="已準備示範匯出">下載</button>${action?`<button class="save" data-admin-create="${action}">${action}</button>`:''}</div>`}
const invitationFilters=[
  ['日期',['7 天','1 個月','3 個月','自訂'],'date'],
  ['寄件者',['API','已刪除的使用者','Peter','spm.demo']],
  ['收件公司',['Awesome Inc','國泰世華商業銀行','精誠資訊','華南永昌證券','兆豐金融控股','兆豐國際商業銀行']],
  ['收件者',['8859','協作聯絡人','Demo9','Peter Peng','security.test','未指派']],
  ['協作原因',['資訊提供','改善','驗證','弱點','其他','自行提出','未指派']],
  ['待檢視項目',[],'select'],
  ['狀態',['等待中','開啟','已解決','邀請已到期','需要核准']],
  ['資料夾',['Transglobe','兆豐銀行','南山產物','臺灣企銀','金融同業','非金融機構','未指派','未訂閱']],
  ['層級',['層級 1','層級 2','層級 3','未分層','未訂閱']],
  ['行動計畫',['監控','檢視','升級處理','未指派']],
  ['關係',['供應商','策略夥伴','第四方','子公司','基準比較','客戶','顧問','其他','未指派']],
  ['生命週期',['導入中','監控中','重新評估','未指派']]
];
const invitationRows=[
  ['2026/08/25','spm.demo','精誠資訊','Demo9','改善','DNSSEC','開啟'],
  ['2026/05/28','Peter','兆豐國際商業銀行','security.test','改善','—','開啟'],
  ['2026/05/15','API','國泰世華商業銀行','未指派','其他','—','邀請已到期']
];
function invitationFilterBody(name,options,type){
  if(type==='date')return `<div class="invitation-date-buttons">${options.map(option=>`<button class="${adminState.invitationDate===option?'active':''}" data-invitation-date="${e(option)}">${e(option)}</button>`).join('')}</div>`;
  if(type==='select')return `<button class="filter-select-count" data-toast="已開啟待檢視項目選擇器">0 個已選 <span>⌄</span></button>`;
  const values=adminState.invitationFilters[name]||[];return options.slice(0,20).map(option=>`<label><input type="checkbox" data-invitation-option="${e(name)}" value="${e(option)}" ${values.includes(option)?'checked':''}> ${e(option)}</label>`).join('')
}
function invitationsView(){
  const active=Object.entries(adminState.invitationFilters).flatMap(([group,values])=>values.map(value=>[group,value]));
  const groups=invitationFilters.filter(([name])=>!adminState.invitationFilterQuery||name.includes(adminState.invitationFilterQuery)).map(([name,options,type])=>`<div class="filter-row"><button data-invitation-filter="${e(name)}"><span>${e(name)}${adminState.invitationFilters[name]?.length?` <b class="filter-count">${adminState.invitationFilters[name].length}</b>`:''}</span><span>${adminState.invitationFilterOpen===name?'⌃':'⌄'}</span></button>${adminState.invitationFilterOpen===name?`<div class="filter-options invitation-filter-options">${invitationFilterBody(name,options,type)}</div>`:''}</div>`).join('');
  const rows=invitationRows.filter(row=>(!adminState.query||row.join(' ').includes(adminState.query))&&Object.entries(adminState.invitationFilters).every(([group,values])=>!values.length||values.some(value=>row.includes(value))));
  return `${pagebar('存取邀請')}<div class="invitation-summary"><div><small>已邀請的投資組合</small><strong>12</strong><span>封邀請已傳送給 <b>4</b> 家公司</span></div><div><small>邀請接受情形</small><strong>10</strong><span>封邀請已接受，共 <b>12</b> 封</span></div><div><small>目前狀態分布</small><strong>0</strong><span>封邀請等待回覆</span><button data-toast="已開啟完整狀態分布">查看完整分布⌄</button></div></div><div class="content invitation-content"><div class="companies-layout invitation-layout"><aside class="filters"><div class="filter-top"><button class="active">▽ 篩選</button><button data-modal="columns">▥</button><button data-modal="views">♧</button></div><input id="invitationFilterSearch" class="filter-search" value="${e(adminState.invitationFilterQuery)}" placeholder="搜尋篩選條件…">${active.length||adminState.invitationDate?`<div class="vuln-active-head"><b>使用中的篩選</b><button data-invitation-clear>清除全部</button></div><div class="vuln-active-chips">${adminState.invitationDate?`<button data-invitation-date="">${e(adminState.invitationDate)}　×</button>`:''}${active.map(([group,value])=>`<button data-invitation-remove="${e(group)}" data-invitation-value="${e(value)}">${e(value)}　×</button>`).join('')}</div>`:''}<div class="filter-scroll">${groups}</div><button class="filter-bottom" data-modal="create-view">建立檢視</button></aside><section class="panel table-panel invitation-table"><div class="table-tools"><span>${rows.length} 封邀請</span><button class="outline" data-toast="請先選擇邀請">標示為已解決 (${adminState.invitationSelected.length}/1)</button><button class="outline" data-toast="請先選擇自行提出的邀請">核准自行提出的要求</button><span class="spacer"></span><button data-toggle="invitation-search">⌕</button><button data-toast="已準備示範 CSV">↓</button><button data-toggle="fullscreen">⛶</button></div><div id="invitationSearchBox" style="display:${adminState.query?'block':'none'};padding:0 12px 10px"><input id="invitationSearch" value="${e(adminState.query)}" placeholder="搜尋邀請" class="table-search-input"></div><div class="table-scroll"><table class="data-table"><thead><tr><th><input type="checkbox" data-invitation-select-all></th><th>日期 ↓</th><th>寄件者</th><th>收件公司</th><th>收件者</th><th>協作原因</th><th>待檢視項目</th><th>狀態</th><th></th></tr></thead><tbody>${rows.map((row,index)=>`<tr><td><input type="checkbox" data-invitation-select="${index}" ${adminState.invitationSelected.includes(index)?'checked':''}></td>${row.map((cell,i)=>`<td class="${i===2?'name':''}">${i===6?`<span class="state-pill ${cell==='開啟'?'pending':''}">${e(cell)}</span>`:e(cell)}</td>`).join('')}<td class="invitation-actions"><button data-toast="已準備下載邀請明細">下載明細</button><button data-toast="已開啟訊息紀錄">檢視訊息</button><button data-toast="已將示範邀請標示為已解決">標示為已解決</button></td></tr>`).join('')}</tbody></table>${rows.length?'':'<div class="empty">沒有符合條件的邀請</div>'}</div><div class="pager"><span>1 – ${rows.length}，共 ${rows.length} 筆</span><span class="spacer"></span><button>‹</button><span>1 / 1</span><button>›</button></div></section></div></div>`
}
function linksView(){return `${pagebar('供應商存取連結',`<button class="save" data-admin-create="建立連結">建立連結</button>`)}<div class="content access-links-page"><section class="access-guidance"><div class="access-guide-icon">↗</div><div><h2>供應商存取連結如何運作？</h2><p>產生供應商存取連結後，你的供應商可使用此連結申請存取 BitSight。複製連結，並放在供應商可以取得的資料或通知中。</p></div><button data-toggle-access-guide>隱藏說明</button></section><section class="panel table-panel"><div class="table-tools"><span>0 個連結</span><span class="spacer"></span><button data-toggle="access-link-search">⌕</button></div><div class="table-scroll"><table class="data-table access-links-table"><thead><tr><th>名稱</th><th>說明</th><th>供應商存取連結</th><th>使用者</th><th>建立日期 ↓</th><th></th></tr></thead><tbody></tbody></table><div class="empty access-empty">尚未建立供應商存取連結</div></div><div class="pager"><button>30⌄</button><span>0 – 0，共 0 筆</span><span class="spacer"></span><button disabled>‹</button><span>0 / 0</span><button disabled>›</button></div></section></div>`}
const contactFilters=[['公司',[],'select'],['資料夾',['我的公司','Transglobe','兆豐銀行','南山產物','臺灣企銀','金融同業','非金融機構']],['層級',['層級 1','層級 2','層級 3']]];
function contactFilterBody(name,options,type){if(type==='select')return `<button class="filter-select-count" data-toast="已開啟公司選擇器">0 個已選 <span>⌄</span></button>`;const values=adminState.contactFilters[name]||[];return options.slice(0,20).map(option=>`<label><input type="checkbox" data-contact-option="${e(name)}" value="${e(option)}" ${values.includes(option)?'checked':''}> ${e(option)}</label>`).join('')}
function contactsView(){
  const groups=contactFilters.filter(([name])=>!adminState.contactFilterQuery||name.includes(adminState.contactFilterQuery)).map(([name,options,type])=>`<div class="filter-row"><button data-contact-filter="${e(name)}"><span>${e(name)}${adminState.contactFilters[name]?.length?` <b class="filter-count">${adminState.contactFilters[name].length}</b>`:''}</span><span>${adminState.contactFilterOpen===name?'⌃':'⌄'}</span></button>${adminState.contactFilterOpen===name?`<div class="filter-options">${contactFilterBody(name,options,type)}</div>`:''}</div>`).join('');
  const rows=contactRows.filter(row=>!adminState.contactQuery||row.join(' ').includes(adminState.contactQuery));
  const collaboration=adminState.contactTab==='collaboration';
  return `${pagebar('供應商聯絡人')}<div class="contact-tabs"><button class="${!collaboration?'active':''}" data-contact-tab="vendor">供應商聯絡人</button><button class="${collaboration?'active':''}" data-contact-tab="collaboration">協作聯絡人</button></div><div class="content contact-content"><div class="companies-layout contact-layout"><aside class="filters"><div class="filter-top"><button class="active">▽ 篩選</button><button class="close-filter">‹</button></div><input id="contactFilterSearch" class="filter-search" value="${e(adminState.contactFilterQuery)}" placeholder="搜尋篩選條件…"><div class="filter-scroll">${groups}</div></aside><section class="panel table-panel contact-table"><div class="table-tools"><span>${collaboration?0:rows.length} 位聯絡人</span>${collaboration?'':`<button class="outline" data-admin-create="新增供應商聯絡人">新增供應商聯絡人</button><button class="outline" data-toast="已開啟 CSV 上傳說明">上傳 CSV</button>`}<span class="spacer"></span>${collaboration?'':`<button data-toggle="contact-search">⌕</button>`}</div><div id="contactSearchBox" style="display:${adminState.contactQuery?'block':'none'};padding:0 12px 10px"><input id="contactSearch" class="table-search-input" value="${e(adminState.contactQuery)}" placeholder="搜尋聯絡人"></div><div class="table-scroll"><table class="data-table"><thead>${collaboration?'<tr><th>公司</th><th>協作聯絡人</th></tr>':'<tr><th>公司</th><th>姓名</th><th>電子郵件</th><th>新增日期 ↓</th><th></th></tr>'}</thead><tbody>${collaboration?'':rows.map(row=>`<tr>${row.map((cell,i)=>`<td class="${i===0?'name':''}">${e(cell)}</td>`).join('')}<td class="contact-actions"><button data-toast="已開啟編輯視窗">編輯</button><button data-toast="示範資料不會刪除">刪除</button></td></tr>`).join('')}</tbody></table>${collaboration||!rows.length?`<div class="empty">${collaboration?'尚未設定協作聯絡人':'沒有符合條件的聯絡人'}</div>`:''}</div><div class="pager"><span>${collaboration?'0 – 0，共 0 筆':`1 – ${rows.length}，共 ${rows.length} 筆`}</span><span class="spacer"></span><button disabled>‹</button><span>${collaboration?'0 / 0':'1 / 1'}</span><button disabled>›</button></div></section></div></div>`
}
function alertSettingsView(){
  const sets=adminState.alertSettingsTab==='sets';
  return `${pagebar('警示設定',sets?`<button class="save" data-admin-create="建立警示集合">建立警示集合</button>`:'')}<div class="settings-tabs"><button class="${!sets?'active':''}" data-alert-settings-tab="scope">層級與資料夾</button><button class="${sets?'active':''}" data-alert-settings-tab="sets">警示集合</button></div><div class="content settings-content"><section class="panel table-panel"><div class="table-tools"><span>0 筆</span><span class="spacer"></span><button data-toggle="settings-search">⌕</button></div><div class="table-scroll"><table class="data-table"><thead>${sets?'<tr><th></th><th>名稱</th><th>說明</th><th>建立者 ↓</th><th>共用</th><th>動作</th></tr>':'<tr><th></th><th>名稱</th><th>警示集合</th><th>政策</th><th>電子郵件 ↓</th><th>動作</th></tr>'}</thead><tbody></tbody></table><div class="empty">${sets?'尚未建立警示集合':'目前沒有層級或資料夾警示設定'}</div></div><div class="pager"><span>0 – 0，共 0 筆</span><span class="spacer"></span><button disabled>‹</button><span>0 / 0</span><button disabled>›</button></div></section></div>`
}
const folderData=[['Transglobe',1,790],['兆豐銀行',1,760],['南山產物',1,760],['臺灣企銀',1,800],['金融同業',31,770],['非金融機構',14,720]];
function foldersView(){
  return `${pagebar('資料夾管理',`<button class="save" data-admin-create="建立資料夾">建立資料夾</button>`)}<div class="content"><div class="companies-layout folder-management-layout"><aside class="filters"><div class="filter-top"><button class="active">▽ 篩選</button><button data-modal="views">♧</button><button class="close-filter">‹</button></div><input class="filter-search" placeholder="搜尋篩選條件…"><div class="filter-scroll"><div class="filter-row"><button data-folder-filter="擁有者"><span>擁有者</span><span>${adminState.folderFilterOpen==='擁有者'?'⌃':'⌄'}</span></button>${adminState.folderFilterOpen==='擁有者'?'<div class="filter-options"><label><input type="checkbox"> spm.demo@example.test <small>6</small></label></div>':''}</div><div class="filter-row"><button data-folder-filter="評等中位數"><span>評等中位數</span><span>${adminState.folderFilterOpen==='評等中位數'?'⌃':'⌄'}</span></button>${adminState.folderFilterOpen==='評等中位數'?'<div class="folder-range"><span>0</span><div></div><span>800</span></div>':''}</div><div class="filter-row"><button data-folder-filter="資料夾內公司"><span>資料夾內公司</span><span>${adminState.folderFilterOpen==='資料夾內公司'?'⌃':'⌄'}</span></button>${adminState.folderFilterOpen==='資料夾內公司'?'<div class="folder-range"><span>0</span><div></div><span>31</span></div>':''}</div></div><button class="filter-bottom" data-modal="create-view">建立檢視</button></aside><section class="panel table-panel"><div class="table-tools"><span>6 筆</span><span class="spacer"></span><button data-toggle="folder-search">⌕</button><button data-toast="已準備示範 CSV">↓</button><button data-toggle="fullscreen">⛶</button></div><div class="table-scroll"><table class="data-table"><thead><tr><th>名稱 ↓</th><th>公司數量</th><th>評等中位數</th><th>擁有者</th><th>說明</th><th>警示</th><th></th></tr></thead><tbody>${folderData.map(row=>`<tr><td class="name">${e(row[0])}</td><td>${row[1]}</td><td>${row[2]}</td><td>spm.demo@example.test</td><td>—</td><td><button class="table-link" data-toast="已開啟資料夾警示">檢視</button></td><td><button class="row-menu" data-toast="已開啟資料夾動作">⋮</button></td></tr>`).join('')}</tbody></table></div><div class="pager"><span>1 – 6，共 6 筆</span><span class="spacer"></span><button disabled>‹</button><span>1 / 1</span><button disabled>›</button></div></section></div></div>`
}
const tierRows=[['層級 1',700,9],['層級 2',600,8],['層級 3',500,7]];
function tiersView(){return `${pagebar('層級設定')}<div class="content tier-settings-page"><div class="tier-rank"><span>最高</span><div class="rank-line">▲<i></i>▼</div><span>最低</span></div><section class="panel tier-settings-table"><div class="tier-head"><span>層級名稱</span><span>說明</span><span>風險門檻</span><span>公司</span><span>評估</span><span></span></div>${tierRows.map(row=>`<div class="tier-setting-row"><span class="tier-name">⠿　<button data-toast="已開啟${e(row[0])}">${e(row[0])}</button></span><span>—</span><span class="risk-threshold" style="--threshold:${(820-row[1])/5.2}%"><b class="max">820</b><strong>${row[1]}</strong><b class="min">300</b><i></i><small>監控</small><small>升級處理</small></span><span>${row[2]}</span><span>—</span><button class="row-menu" data-toast="已開啟層級動作">⋮</button></div>`).join('')}<button class="create-tier" data-admin-create="建立層級">＋　建立層級 (3/5)</button></section></div>`}
function integrationsView(){const cards=[['API','以 API 讀取評等、公司與發現事項','已連接'],['單一登入 SSO','使用身分提供者登入','設定'],['SIEM','將警示傳送到安全資訊平台','設定'],['工單系統','將改善要求同步到工作流程','設定'],['雲端儲存','排程匯出報表與資料','設定'],['Webhook','即時接收評等與事件變更','設定']];return `${pagebar('整合')}<div class="content"><div class="integration-intro"><h2>連接你的安全工作流程</h2><p>使用示範整合卡片了解各種資料交換與通知方式。</p></div><div class="integration-grid">${cards.map((c,i)=>`<section class="panel integration-card"><span>${['⌘','◇','◉','✓','▤','↗'][i]}</span><div><h3>${c[0]}</h3><p>${c[1]}</p></div><button class="outline ${c[2]==='已連接'?'connected':''}" data-integration>${c[2]}</button></section>`).join('')}</div></div>`}
function adminView(page){return page==='invitations'?invitationsView():page==='access-links'?linksView():page==='contacts'?contactsView():page==='alert-settings'?alertSettingsView():page==='folders'?foldersView():page==='tiers'?tiersView():integrationsView()}
document.addEventListener('click',event=>{const x=event.target.closest('[data-admin-row],[data-admin-create],[data-folder],[data-integration]');if(!x)return;if(x.dataset.folder!==undefined){adminState.folder=+x.dataset.folder;render()}else if(x.hasAttribute('data-integration'))showToast(x.textContent==='已連接'?'整合連線正常':'已開啟整合設定');else if(x.dataset.adminCreate)showToast(`${x.dataset.adminCreate}視窗已開啟`);else showToast('已開啟項目詳情')});
document.addEventListener('input',event=>{if(event.target.id==='adminSearch'){adminState.query=event.target.value;const p=event.target.selectionStart;render();const i=document.getElementById('adminSearch');i.focus();i.setSelectionRange(p,p)}});
document.addEventListener('change',event=>{if(event.target.hasAttribute('data-rule-toggle'))showToast(event.target.checked?'已啟用警示規則':'已停用警示規則')});
document.addEventListener('click',event=>{
  const group=event.target.closest('[data-invitation-filter]');
  if(group){const name=group.dataset.invitationFilter;adminState.invitationFilterOpen=adminState.invitationFilterOpen===name?'':name;render();return;}
  const remove=event.target.closest('[data-invitation-remove]');
  if(remove){const groupName=remove.dataset.invitationRemove;adminState.invitationFilters[groupName]=(adminState.invitationFilters[groupName]||[]).filter(value=>value!==remove.dataset.invitationValue);render();return;}
  if(event.target.closest('[data-invitation-clear]')){adminState.invitationFilters={};adminState.invitationDate='';render();return;}
  const date=event.target.closest('[data-invitation-date]');
  if(date){adminState.invitationDate=date.dataset.invitationDate;render();return;}
  if(event.target.closest('[data-toggle="invitation-search"]')){const box=document.getElementById('invitationSearchBox');if(box)box.style.display=box.style.display==='none'?'block':'none';}
});
document.addEventListener('input',event=>{
  if(event.target.id==='invitationFilterSearch'){adminState.invitationFilterQuery=event.target.value;const at=event.target.selectionStart;render();const input=document.getElementById('invitationFilterSearch');input.focus();input.setSelectionRange(at,at);}
  if(event.target.id==='invitationSearch'){adminState.query=event.target.value;const at=event.target.selectionStart;render();const input=document.getElementById('invitationSearch');input.focus();input.setSelectionRange(at,at);}
});
document.addEventListener('change',event=>{
  if(event.target.dataset.invitationOption){const group=event.target.dataset.invitationOption;const values=adminState.invitationFilters[group]||[];adminState.invitationFilters[group]=event.target.checked?[...new Set([...values,event.target.value])]:values.filter(value=>value!==event.target.value);render();}
  if(event.target.dataset.invitationSelect!==undefined){const id=+event.target.dataset.invitationSelect;adminState.invitationSelected=event.target.checked?[...new Set([...adminState.invitationSelected,id])]:adminState.invitationSelected.filter(value=>value!==id);render();}
  if(event.target.hasAttribute('data-invitation-select-all')){adminState.invitationSelected=event.target.checked?invitationRows.map((_,index)=>index):[];render();}
});
document.addEventListener('click',event=>{
  const tab=event.target.closest('[data-contact-tab]');if(tab){adminState.contactTab=tab.dataset.contactTab;render();return;}
  const group=event.target.closest('[data-contact-filter]');if(group){const name=group.dataset.contactFilter;adminState.contactFilterOpen=adminState.contactFilterOpen===name?'':name;render();return;}
  if(event.target.closest('[data-toggle="contact-search"]')){const box=document.getElementById('contactSearchBox');if(box)box.style.display=box.style.display==='none'?'block':'none';return;}
  if(event.target.closest('[data-toggle-access-guide]')){event.target.closest('.access-guidance')?.classList.toggle('collapsed');return;}
});
document.addEventListener('input',event=>{
  if(event.target.id==='contactFilterSearch'){adminState.contactFilterQuery=event.target.value;const at=event.target.selectionStart;render();const input=document.getElementById('contactFilterSearch');input.focus();input.setSelectionRange(at,at);}
  if(event.target.id==='contactSearch'){adminState.contactQuery=event.target.value;const at=event.target.selectionStart;render();const input=document.getElementById('contactSearch');input.focus();input.setSelectionRange(at,at);}
});
document.addEventListener('change',event=>{if(event.target.dataset.contactOption){const group=event.target.dataset.contactOption;const values=adminState.contactFilters[group]||[];adminState.contactFilters[group]=event.target.checked?[...new Set([...values,event.target.value])]:values.filter(value=>value!==event.target.value);render();}});
document.addEventListener('click',event=>{
  const tab=event.target.closest('[data-alert-settings-tab]');if(tab){adminState.alertSettingsTab=tab.dataset.alertSettingsTab;render();return;}
  const folderFilter=event.target.closest('[data-folder-filter]');if(folderFilter){const name=folderFilter.dataset.folderFilter;adminState.folderFilterOpen=adminState.folderFilterOpen===name?'':name;render();return;}
});
