const adminState={query:'',folder:0,toggle:true,invitationFilterOpen:'日期',invitationFilterQuery:'',invitationFilters:{},invitationSelected:[]};
const contactRows=[['王小明','security@example-bank.test','範例商業銀行','主要聯絡人'],['陳美玲','risk@example-cloud.test','範例雲端服務','風險負責人'],['林志強','it@example-telco.test','範例電信公司','技術聯絡人']];
function adminToolbar(title,count,action){return `<div class="admin-toolbar"><input id="adminSearch" value="${e(adminState.query)}" placeholder="搜尋${title}…"><span>${count} 筆</span><button class="outline" data-toast="已準備示範匯出">下載</button>${action?`<button class="save" data-admin-create="${action}">${action}</button>`:''}</div>`}
const invitationFilters=[
  ['日期',['過去 7 天','過去 30 天','過去 90 天','自訂日期範圍']],
  ['寄件者',['管理者','風險管理團隊','API']],
  ['收件公司',['範例資訊服務','範例商業銀行','範例金融控股','範例電信公司']],
  ['收件者',['主要協作聯絡人','資安窗口','未指派']],
  ['協作原因',['改善','評估','其他']],
  ['待檢視項目',['DNSSEC','DKIM','TLS/SSL 設定','開放連接埠','重大弱點管理']],
  ['狀態',['開啟','已解決','邀請已到期','等待回覆']],
  ['資料夾',['全部公司','重要供應商','金融服務','資訊服務']],
  ['層級',['層級 1','層級 2','層級 3','未分層']],
  ['行動計畫',['需要改善','持續監控','優先處理']],
  ['關係',['供應商','策略夥伴','第四方','子公司']],
  ['生命週期',['導入中','監控中','重新評估','未指派']]
];
const invitationRows=[
  ['2026/08/25','管理者','範例資訊服務','主要協作聯絡人','改善','DNSSEC','開啟'],
  ['2026/05/28','風險管理團隊','範例商業銀行','資安窗口','改善','—','開啟'],
  ['2026/05/15','API','範例金融控股','未指派','其他','—','邀請已到期']
];
function invitationFilterBody(name,options){const values=adminState.invitationFilters[name]||[];return options.slice(0,20).map(option=>`<label><input type="checkbox" data-invitation-option="${e(name)}" value="${e(option)}" ${values.includes(option)?'checked':''}> ${e(option)}</label>`).join('')}
function invitationsView(){
  const active=Object.entries(adminState.invitationFilters).flatMap(([group,values])=>values.map(value=>[group,value]));
  const groups=invitationFilters.filter(([name])=>!adminState.invitationFilterQuery||name.includes(adminState.invitationFilterQuery)).map(([name,options])=>`<div class="filter-row"><button data-invitation-filter="${e(name)}"><span>${e(name)}${adminState.invitationFilters[name]?.length?` <b class="filter-count">${adminState.invitationFilters[name].length}</b>`:''}</span><span>${adminState.invitationFilterOpen===name?'⌃':'⌄'}</span></button>${adminState.invitationFilterOpen===name?`<div class="filter-options invitation-filter-options">${invitationFilterBody(name,options)}</div>`:''}</div>`).join('');
  const rows=invitationRows.filter(row=>(!adminState.query||row.join(' ').includes(adminState.query))&&Object.entries(adminState.invitationFilters).every(([group,values])=>!values.length||values.some(value=>row.includes(value))));
  return `${pagebar('存取邀請')}<div class="invitation-summary"><div><small>已邀請的投資組合比例</small><strong>8%</strong><span>已向 4 家公司傳送 12 封邀請</span></div><div><small>邀請接受率</small><strong>83%</strong><span>12 封邀請中已有 10 封接受</span></div><div><small>目前狀態分布</small><strong>0</strong><span>封邀請等待回覆</span><button data-toast="已開啟完整狀態分布">查看完整分布⌄</button></div></div><div class="content invitation-content"><div class="companies-layout invitation-layout"><aside class="filters"><div class="filter-top"><button class="active">▽ 篩選</button><button data-modal="columns">▥</button><button data-modal="views">♧</button></div><input id="invitationFilterSearch" class="filter-search" value="${e(adminState.invitationFilterQuery)}" placeholder="搜尋篩選條件…">${active.length?`<div class="vuln-active-head"><b>使用中的篩選</b><button data-invitation-clear>清除全部</button></div><div class="vuln-active-chips">${active.map(([group,value])=>`<button data-invitation-remove="${e(group)}" data-invitation-value="${e(value)}">${e(value)}　×</button>`).join('')}</div>`:''}<div class="filter-scroll">${groups}</div><button class="filter-bottom" data-modal="create-view">建立檢視</button></aside><section class="panel table-panel invitation-table"><div class="table-tools"><span>${rows.length} 封邀請</span><button class="outline" data-toast="請先選擇邀請">標示為已解決 (${adminState.invitationSelected.length}/1)</button><button class="outline" data-toast="請先選擇自行提出的邀請">核准自行提出的要求</button><span class="spacer"></span><button data-toggle="invitation-search">⌕</button><button data-toast="已準備示範 CSV">↓</button><button data-toggle="fullscreen">⛶</button></div><div id="invitationSearchBox" style="display:${adminState.query?'block':'none'};padding:0 12px 10px"><input id="invitationSearch" value="${e(adminState.query)}" placeholder="搜尋邀請" class="table-search-input"></div><div class="table-scroll"><table class="data-table"><thead><tr><th><input type="checkbox" data-invitation-select-all></th><th>日期 ↓</th><th>寄件者</th><th>收件公司</th><th>收件者</th><th>協作原因</th><th>待檢視項目</th><th>狀態</th><th></th></tr></thead><tbody>${rows.map((row,index)=>`<tr><td><input type="checkbox" data-invitation-select="${index}" ${adminState.invitationSelected.includes(index)?'checked':''}></td>${row.map((cell,i)=>`<td class="${i===2?'name':''}">${i===6?`<span class="state-pill ${cell==='開啟'?'pending':''}">${e(cell)}</span>`:e(cell)}</td>`).join('')}<td class="invitation-actions"><button data-toast="已準備下載邀請明細">下載明細</button><button data-toast="已開啟訊息紀錄">檢視訊息</button><button data-toast="已將示範邀請標示為已解決">標示為已解決</button></td></tr>`).join('')}</tbody></table>${rows.length?'':'<div class="empty">沒有符合條件的邀請</div>'}</div><div class="pager"><span>1 – ${rows.length}，共 ${rows.length} 筆</span><span class="spacer"></span><button>‹</button><span>1 / 1</span><button>›</button></div></section></div></div>`
}
function linksView(){return `${pagebar('供應商存取連結')}<div class="content">${adminToolbar('連結',2,'建立存取連結')}<section class="panel"><table class="data-table"><thead><tr><th>連結名稱</th><th>適用公司</th><th>建立者</th><th>到期日</th><th>使用次數</th><th>狀態</th></tr></thead><tbody><tr data-admin-row><td class="name">年度評估回覆連結</td><td>範例商業銀行</td><td>管理者</td><td>2026/10/31</td><td>3</td><td><span class="state-pill good">有效</span></td></tr><tr data-admin-row><td class="name">改善證明上傳</td><td>範例資訊服務</td><td>管理者</td><td>2026/09/30</td><td>1</td><td><span class="state-pill pending">即將到期</span></td></tr></tbody></table></section></div>`}
function contactsView(){const rows=contactRows.filter(r=>!adminState.query||r.join(' ').includes(adminState.query));return `${pagebar('供應商聯絡人')}<div class="content">${adminToolbar('聯絡人',rows.length,'新增聯絡人')}<section class="panel"><table class="data-table"><thead><tr><th>姓名</th><th>電子郵件</th><th>公司</th><th>角色</th></tr></thead><tbody>${rows.map(r=>`<tr data-admin-row>${r.map((x,i)=>`<td class="${i===0?'name':''}">${x}</td>`).join('')}</tr>`).join('')}</tbody></table></section></div>`}
const rules=[['安全評等下降','評等下降 20 分以上','電子郵件、應用程式內'],['重大弱點出現','偵測到已知遭利用弱點','應用程式內'],['新資料外洩事件','任何新的重大或高風險事件','電子郵件'],['第四方集中風險','影響 4 家以上受監控公司','應用程式內']];
function alertSettingsView(){return `${pagebar('警示設定',`<button class="outline" data-admin-create="新增警示規則">新增規則</button>`)}<div class="content"><div class="settings-layout"><nav class="settings-nav"><button class="active">警示規則</button><button>通知對象</button><button>傳送方式</button></nav><section class="panel rule-list">${rules.map((r,i)=>`<article><label class="toggle"><input type="checkbox" ${i<3?'checked':''} data-rule-toggle><span></span></label><div><h3>${r[0]}</h3><p>${r[1]}</p><small>${r[2]}</small></div><button data-toast="已開啟規則設定">編輯</button></article>`).join('')}</section></div></div>`}
const folderData=[['全部公司','12','系統'],['重要供應商','5','自訂'],['金融服務','4','自訂'],['資訊服務','3','自訂']];
function foldersView(){return `${pagebar('資料夾管理',`<button class="outline" data-admin-create="新增資料夾">新增資料夾</button>`)}<div class="content"><div class="folder-layout"><section class="panel folder-list">${folderData.map((f,i)=>`<button data-folder="${i}" class="${adminState.folder===i?'active':''}"><span>▣</span><b>${f[0]}</b><small>${f[1]} 家公司 · ${f[2]}</small></button>`).join('')}</section><section class="panel folder-detail"><h2>${folderData[adminState.folder][0]}</h2><p>此資料夾包含 ${folderData[adminState.folder][1]} 家公司，可用於篩選、報表與警示規則。</p><div class="assigned">${companies.slice(0,+folderData[adminState.folder][1]).map(c=>`<span>▣ ${c[0]} <button data-toast="已從示範資料夾移除">×</button></span>`).join('')}</div><button class="outline" data-toast="已開啟公司選擇器">新增公司</button></section></div></div>`}
function tiersView(){return `${pagebar('層級設定',`<button class="outline" data-admin-create="新增層級">新增層級</button>`)}<div class="content tier-grid"><section class="panel tier-card"><span class="tier-dot critical"></span><h2>層級 1</h2><b>7 家公司</b><p>關鍵供應商，需持續監控並優先處理重大風險。</p><button data-toast="已開啟層級設定">編輯</button></section><section class="panel tier-card"><span class="tier-dot medium"></span><h2>層級 2</h2><b>5 家公司</b><p>重要供應商，依排程檢視評等與發現事項。</p><button data-toast="已開啟層級設定">編輯</button></section><section class="panel tier-card"><span class="tier-dot low"></span><h2>未指派</h2><b>0 家公司</b><p>尚未指定監控層級的公司。</p><button data-nav="companies">查看公司</button></section></div>`}
function integrationsView(){const cards=[['API','以 API 讀取評等、公司與發現事項','已連接'],['單一登入 SSO','使用身分提供者登入','設定'],['SIEM','將警示傳送到安全資訊平台','設定'],['工單系統','將改善要求同步到工作流程','設定'],['雲端儲存','排程匯出報表與資料','設定'],['Webhook','即時接收評等與事件變更','設定']];return `${pagebar('整合')}<div class="content"><div class="integration-intro"><h2>連接你的安全工作流程</h2><p>使用示範整合卡片了解各種資料交換與通知方式。</p></div><div class="integration-grid">${cards.map((c,i)=>`<section class="panel integration-card"><span>${['⌘','◇','◉','✓','▤','↗'][i]}</span><div><h3>${c[0]}</h3><p>${c[1]}</p></div><button class="outline ${c[2]==='已連接'?'connected':''}" data-integration>${c[2]}</button></section>`).join('')}</div></div>`}
function adminView(page){return page==='invitations'?invitationsView():page==='access-links'?linksView():page==='contacts'?contactsView():page==='alert-settings'?alertSettingsView():page==='folders'?foldersView():page==='tiers'?tiersView():integrationsView()}
document.addEventListener('click',event=>{const x=event.target.closest('[data-admin-row],[data-admin-create],[data-folder],[data-integration]');if(!x)return;if(x.dataset.folder!==undefined){adminState.folder=+x.dataset.folder;render()}else if(x.hasAttribute('data-integration'))showToast(x.textContent==='已連接'?'整合連線正常':'已開啟整合設定');else if(x.dataset.adminCreate)showToast(`${x.dataset.adminCreate}視窗已開啟`);else showToast('已開啟項目詳情')});
document.addEventListener('input',event=>{if(event.target.id==='adminSearch'){adminState.query=event.target.value;const p=event.target.selectionStart;render();const i=document.getElementById('adminSearch');i.focus();i.setSelectionRange(p,p)}});
document.addEventListener('change',event=>{if(event.target.hasAttribute('data-rule-toggle'))showToast(event.target.checked?'已啟用警示規則':'已停用警示規則')});
document.addEventListener('click',event=>{
  const group=event.target.closest('[data-invitation-filter]');
  if(group){const name=group.dataset.invitationFilter;adminState.invitationFilterOpen=adminState.invitationFilterOpen===name?'':name;render();return;}
  const remove=event.target.closest('[data-invitation-remove]');
  if(remove){const groupName=remove.dataset.invitationRemove;adminState.invitationFilters[groupName]=(adminState.invitationFilters[groupName]||[]).filter(value=>value!==remove.dataset.invitationValue);render();return;}
  if(event.target.closest('[data-invitation-clear]')){adminState.invitationFilters={};render();return;}
  if(event.target.closest('[data-toggle="invitation-search"]')){const box=document.getElementById('invitationSearchBox');if(box)box.style.display=box.style.display==='none'?'block':'none';}
});
document.addEventListener('input',event=>{
  if(event.target.id==='invitationFilterSearch'){adminState.invitationFilterQuery=event.target.value;const at=event.target.selectionStart;render();const input=document.getElementById('invitationFilterSearch');input.focus();input.setSelectionRange(at,at);}
  if(event.target.id==='invitationSearch'){adminState.query=event.target.value;const at=event.target.selectionStart;render();const input=document.getElementById('invitationSearch');input.focus();input.setSelectionRange(at,at);}
});
document.addEventListener('change',event=>{
  if(event.target.dataset.invitationOption){const group=event.target.dataset.invitationOption;const values=adminState.invitationFilters[group]||[];adminState.invitationFilters[group]=event.target.checked?[...new Set([...values,event.target.value])]:values.filter(value=>value!==event.target.value);render();}
  if(event.target.dataset.invitationSelect!==undefined){const id=+event.target.dataset.invitationSelect;adminState.invitationSelected=event.target.checked?[...new Set([...adminState.invitationSelected,id])]:adminState.invitationSelected.filter(value=>value!==id);render();}
  if(event.target.hasAttribute('data-invitation-select-all')){adminState.invitationSelected=event.target.checked?invitationRows.map((_,index)=>index):[];render();}
});
