const adminState={query:'',folder:0,toggle:true};
const contactRows=[['王小明','security@example-bank.test','範例商業銀行','主要聯絡人'],['陳美玲','risk@example-cloud.test','範例雲端服務','風險負責人'],['林志強','it@example-telco.test','範例電信公司','技術聯絡人']];
function adminToolbar(title,count,action){return `<div class="admin-toolbar"><input id="adminSearch" value="${e(adminState.query)}" placeholder="搜尋${title}…"><span>${count} 筆</span><button class="outline" data-toast="已準備示範匯出">下載</button>${action?`<button class="save" data-admin-create="${action}">${action}</button>`:''}</div>`}
function invitationsView(){return `${pagebar('存取邀請')}<div class="content">${adminToolbar('邀請',3,'傳送邀請')}<section class="panel"><table class="data-table"><thead><tr><th>受邀者</th><th>公司</th><th>權限</th><th>傳送日期</th><th>狀態</th></tr></thead><tbody><tr data-admin-row><td class="name">security@example-bank.test</td><td>範例商業銀行</td><td>公司管理員</td><td>2026/09/12</td><td><span class="state-pill pending">等待接受</span></td></tr><tr data-admin-row><td class="name">risk@example-cloud.test</td><td>範例雲端服務</td><td>公司使用者</td><td>2026/09/05</td><td><span class="state-pill good">已接受</span></td></tr><tr data-admin-row><td class="name">audit@example-telco.test</td><td>範例電信公司</td><td>唯讀</td><td>2026/08/15</td><td><span class="state-pill">已到期</span></td></tr></tbody></table></section></div>`}
function linksView(){return `${pagebar('供應商存取連結')}<div class="content">${adminToolbar('連結',2,'建立存取連結')}<section class="panel"><table class="data-table"><thead><tr><th>連結名稱</th><th>適用公司</th><th>建立者</th><th>到期日</th><th>使用次數</th><th>狀態</th></tr></thead><tbody><tr data-admin-row><td class="name">年度評估回覆連結</td><td>範例商業銀行</td><td>管理者</td><td>2026/10/31</td><td>3</td><td><span class="state-pill good">有效</span></td></tr><tr data-admin-row><td class="name">改善證明上傳</td><td>範例資訊服務</td><td>管理者</td><td>2026/09/30</td><td>1</td><td><span class="state-pill pending">即將到期</span></td></tr></tbody></table></section></div>`}
function contactsView(){const rows=contactRows.filter(r=>!adminState.query||r.join(' ').includes(adminState.query));return `${pagebar('供應商聯絡人')}<div class="content">${adminToolbar('聯絡人',rows.length,'新增聯絡人')}<section class="panel"><table class="data-table"><thead><tr><th>姓名</th><th>電子郵件</th><th>公司</th><th>角色</th></tr></thead><tbody>${rows.map(r=>`<tr data-admin-row>${r.map((x,i)=>`<td class="${i===0?'name':''}">${x}</td>`).join('')}</tr>`).join('')}</tbody></table></section></div>`}
const rules=[['安全評等下降','評等下降 20 分以上','電子郵件、應用程式內'],['重大弱點出現','偵測到已知遭利用弱點','應用程式內'],['新資料外洩事件','任何新的重大或高風險事件','電子郵件'],['第四方集中風險','影響 4 家以上受監控公司','應用程式內']];
function alertSettingsView(){return `${pagebar('警示設定',`<button class="outline" data-admin-create="新增警示規則">新增規則</button>`)}<div class="content"><div class="settings-layout"><nav class="settings-nav"><button class="active">警示規則</button><button>通知對象</button><button>傳送方式</button></nav><section class="panel rule-list">${rules.map((r,i)=>`<article><label class="toggle"><input type="checkbox" ${i<3?'checked':''} data-rule-toggle><span></span></label><div><h3>${r[0]}</h3><p>${r[1]}</p><small>${r[2]}</small></div><button data-toast="已開啟規則設定">編輯</button></article>`).join('')}</section></div></div>`}
const folderData=[['全部公司','12','系統'],['重要供應商','5','自訂'],['金融服務','4','自訂'],['資訊服務','3','自訂']];
function foldersView(){return `${pagebar('資料夾管理',`<button class="outline" data-admin-create="新增資料夾">新增資料夾</button>`)}<div class="content"><div class="folder-layout"><section class="panel folder-list">${folderData.map((f,i)=>`<button data-folder="${i}" class="${adminState.folder===i?'active':''}"><span>▣</span><b>${f[0]}</b><small>${f[1]} 家公司 · ${f[2]}</small></button>`).join('')}</section><section class="panel folder-detail"><h2>${folderData[adminState.folder][0]}</h2><p>此資料夾包含 ${folderData[adminState.folder][1]} 家公司，可用於篩選、報表與警示規則。</p><div class="assigned">${companies.slice(0,+folderData[adminState.folder][1]).map(c=>`<span>▣ ${c[0]} <button data-toast="已從示範資料夾移除">×</button></span>`).join('')}</div><button class="outline" data-toast="已開啟公司選擇器">新增公司</button></section></div></div>`}
function tiersView(){return `${pagebar('層級設定',`<button class="outline" data-admin-create="新增層級">新增層級</button>`)}<div class="content tier-grid"><section class="panel tier-card"><span class="tier-dot critical"></span><h2>層級 1</h2><b>7 家公司</b><p>關鍵供應商，需持續監控並優先處理重大風險。</p><button data-toast="已開啟層級設定">編輯</button></section><section class="panel tier-card"><span class="tier-dot medium"></span><h2>層級 2</h2><b>5 家公司</b><p>重要供應商，依排程檢視評等與發現事項。</p><button data-toast="已開啟層級設定">編輯</button></section><section class="panel tier-card"><span class="tier-dot low"></span><h2>未指派</h2><b>0 家公司</b><p>尚未指定監控層級的公司。</p><button data-nav="companies">查看公司</button></section></div>`}
function integrationsView(){const cards=[['API','以 API 讀取評等、公司與發現事項','已連接'],['單一登入 SSO','使用身分提供者登入','設定'],['SIEM','將警示傳送到安全資訊平台','設定'],['工單系統','將改善要求同步到工作流程','設定'],['雲端儲存','排程匯出報表與資料','設定'],['Webhook','即時接收評等與事件變更','設定']];return `${pagebar('整合')}<div class="content"><div class="integration-intro"><h2>連接你的安全工作流程</h2><p>使用示範整合卡片了解各種資料交換與通知方式。</p></div><div class="integration-grid">${cards.map((c,i)=>`<section class="panel integration-card"><span>${['⌘','◇','◉','✓','▤','↗'][i]}</span><div><h3>${c[0]}</h3><p>${c[1]}</p></div><button class="outline ${c[2]==='已連接'?'connected':''}" data-integration>${c[2]}</button></section>`).join('')}</div></div>`}
function adminView(page){return page==='invitations'?invitationsView():page==='access-links'?linksView():page==='contacts'?contactsView():page==='alert-settings'?alertSettingsView():page==='folders'?foldersView():page==='tiers'?tiersView():integrationsView()}
document.addEventListener('click',event=>{const x=event.target.closest('[data-admin-row],[data-admin-create],[data-folder],[data-integration]');if(!x)return;if(x.dataset.folder!==undefined){adminState.folder=+x.dataset.folder;render()}else if(x.hasAttribute('data-integration'))showToast(x.textContent==='已連接'?'整合連線正常':'已開啟整合設定');else if(x.dataset.adminCreate)showToast(`${x.dataset.adminCreate}視窗已開啟`);else showToast('已開啟項目詳情')});
document.addEventListener('input',event=>{if(event.target.id==='adminSearch'){adminState.query=event.target.value;const p=event.target.selectionStart;render();const i=document.getElementById('adminSearch');i.focus();i.setSelectionRange(p,p)}});
document.addEventListener('change',event=>{if(event.target.hasAttribute('data-rule-toggle'))showToast(event.target.checked?'已啟用警示規則':'已停用警示規則')});
