const menu=[
  ['儀表板','dashboard','⌁'],
  ['投資組合風險',null,'▣',[
    ['公司清單','companies'],['框架評估','fi-assessments'],['關鍵資產','critical-assets'],['公司比較','compare'],['供應商探索','discovery'],['到期訂閱','expired']]],
  ['供應商風險',null,'▦',[
    ['總覽','vendor-overview'],['框架情報','framework'],['即時洞察','instant'],['評估','assessments'],['風險面向','vectors'],['發現事項','findings'],['威脅洞察','threat'],['評等樹','tree'],['改善追蹤','remediation'],['基礎設施','infrastructure']]],
  ['資料外洩情報','breach','⚑'],['弱點偵測','vulnerability','◉'],
  ['第四方風險',null,'♧', [['總覽','fourth-overview'],['服務提供者','providers'],['產品','products']]],
  ['警示',null,'⚑',[['投資組合警示','portfolio-alerts'],['第四方警示','fourth-alerts']]],
  ['報表','reports','▤'],
  ['協作',null,'✉',[['存取邀請','invitations'],['供應商存取連結','access-links'],['供應商聯絡人','contacts']]],
  ['投資組合設定',null,'☷',[['警示設定','alert-settings'],['資料夾管理','folders'],['層級設定','tiers']]],
  ['整合','integrations','♧']
];
const names=Object.fromEntries(menu.flatMap(m=>m[3]?m[3].map(x=>[x[1],x[0]]):[[m[1],m[0]]]));
const companies=[
  ['範例金融控股','800','—','—','—'],['範例商業銀行','750','—','層級 1','供應商'],['範例資訊服務','780','—','—','供應商'],['範例國際銀行','800','—','層級 1','—'],['範例製造企業','820','—','層級 1','—'],['範例電信公司','670','—','層級 1','供應商'],['範例電子收費','730','—','層級 1','—'],['範例第一銀行','760','—','層級 1','—'],['範例證券集團','720','—','層級 2','供應商'],['範例數位娛樂','540','—','層級 2','—'],['範例保險公司','770','—','層級 2','供應商'],['範例雲端服務','690','—','層級 2','供應商']
];
const filters=[['資料夾',['全部公司','重要供應商','金融服務','資訊服務']],['層級',['層級 1','層級 2','未設定']],['訂閱類型',['持續監控','已到期']],['供應商行動計畫',['已建立','未建立']],['關係',['供應商','客戶','未設定']],['生命週期',['使用中','評估中']],['有聯絡人',['是','否']],['安全評等',['700 以上','600–699','600 以下']],['產業',['金融','科技','製造']],['國家／地區',['臺灣','美國','其他']],['自行發布',['是','否']],['評等類型',['標準','資訊不足']],['風險面向等級',['良好','普通','待改善']],['感染事件',['有','無']],['開放埠',['有','無']],['公開揭露',['有','無']],['軟體',['有','無']],['服務提供者',['有','無']],['產品',['有','無']],['產品類型',['有','無']]];
const state={page:'dashboard',open:'',filterOpen:'',filterValues:{},query:'',selected:null,discoverySelected:0,discoveryQuery:'',showSubscribed:false,subscribed:[1],alertCategory:'',alertSeverity:'',alertQuery:'',vulnQuery:'',modal:null,toast:'',hideBanner:false,collapsed:false,period:'30 天',update:0,view:'全部公司'};
const app=document.getElementById('app');
function e(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function parentFor(page){return menu.find(m=>m[3]?.some(x=>x[1]===page))?.[0]||'';}
function nav(){return menu.map(m=>`<div class="menu-group"><button class="menu-main ${state.page===m[1]||m[3]?.some(x=>x[1]===state.page)?'active':''}" data-nav="${m[1]||''}" data-group="${m[0]}"><span class="icon">${m[2]}</span><span>${m[0]}</span>${m[3]?'<span class="chev">'+(state.open===m[0]?'⌄':'›')+'</span>':''}</button>${m[3]&&state.open===m[0]?`<div class="submenu">${m[3].map(([label,id])=>`<button class="${state.page===id?'active':''}" data-nav="${id}">${label}</button>`).join('')}</div>`:''}</div>`).join('');}
function topbar(){const vendorPages=['vendor-overview','framework','instant','assessments','vectors','findings','threat','tree','remediation','infrastructure'];const c=vendorPages.includes(state.page)?companies[vendorState.company]:null;return `<div class="top"><button class="portfolio-select ${c?'company-select':''}" ${c?'data-vendor-company':'data-modal="view"'}><span class="briefcase">${c?'▣':'▣'}</span><span>${c?e(c[0]):e(state.view)+'　12 家公司'}</span>${c?`<b class="top-rating">≡ ${c[1]}</b>`:''}<span class="arrow">⌄</span></button><input class="global-search" placeholder="搜尋公司、網域或頁面名稱" data-global-search><div class="top-right"><button title="通知" data-nav="portfolio-alerts">⚑</button><button title="設定" data-nav="alert-settings">⚙</button><button data-tour>☷　操作導覽</button></div></div>`;}
function pagebar(title,actions=''){return `<div class="pagebar"><h1>${title}</h1><div class="actions">${actions}</div></div>`;}
function globalFooter(){return `<footer class="global-footer"><span>© 2026 BitSight Technologies, Inc.</span><button data-toast="隱私權政策為原站外部文件">隱私權政策</button><button data-toast="免責聲明為原站外部文件">免責聲明</button><button data-toast="使用條款為原站外部文件">使用條款</button><button data-toast="版本資訊為原站外部文件">版本資訊</button><button data-toast="最新消息為原站外部文件">最新消息</button></footer>`}
function dashboard(){const headlines=['新興資安事件：網路設備弱點','供應鏈套件風險通報','雲端服務設定異常'];return `${pagebar('投資組合儀表板',`<select class="outline" id="period"><option>30 天</option><option>90 天</option><option>1 年</option></select><button class="outline" data-modal="add-card">新增卡片</button><button class="outline" data-modal="edit-dashboard">編輯儀表板</button>`)}<div class="content"><div class="panel dash-panel"><div class="dash-title">最新更新 <button style="float:right;border:0;background:white" data-toggle="updates">顯示／隱藏⌃</button></div><div id="updates" class="updates"><div class="update-card"><h2>⚠　10 項新興資安事件</h2><hr><h3>${headlines[state.update]}</h3><div class="meta"><span><b>嚴重程度</b><br>高</span><span><b>暴露趨勢</b><br>10 家公司 ↗</span><span><b>受影響公司</b><br>10 家</span></div><p><b>說明</b></p><p>這是一筆虛構的示範通報，供你練習從儀表板進入弱點偵測與受影響公司清單。</p><div class="update-foot"><button class="outline" data-update="prev">←</button><span>${state.update+1} / 3</span><button class="outline" data-nav="vulnerability">查看弱點</button><button class="outline" data-update="next">→</button></div></div><div class="update-card"><h3><b>威脅情報新聞</b></h3><hr><p>近期供應鏈與雲端服務風險摘要。這裡使用示意內容，避免引用帳號中的真實資料。</p><div class="update-foot"><span>最新消息</span><button class="outline" data-nav="threat">繼續閱讀</button></div></div></div></div><div class="metric-grid"><div class="panel metric">評等中位數<div class="big">760</div><small>近 30 天 → 0</small></div><div class="panel metric">開始使用<div class="big">8 / 8</div><small>核心設定已完成</small></div><div class="panel metric">投資組合風險矩陣<div class="big">12</div><small>受監控公司</small></div></div></div>`;}
function filterRows(){const q=document.querySelector('.filter-search')?.value?.toLowerCase()||'';return filters.filter(([name])=>name.includes(q)).map(([name,opts])=>`<div class="filter-row"><button data-filter="${name}">${name}<span>⌄</span></button>${state.filterOpen===name?`<div class="filter-options">${opts.map(o=>`<label><input type="checkbox" data-filter-value="${name}" value="${o}" ${state.filterValues[name]?.includes(o)?'checked':''}> ${o}</label>`).join('')}</div>`:''}</div>`).join('');}
function filteredCompanies(){return companies.filter(c=>(!state.query||c[0].includes(state.query))&&(!state.filterValues['層級']?.length||state.filterValues['層級'].includes(c[3]))&&(!state.filterValues['關係']?.length||state.filterValues['關係'].includes(c[4]))&&(!state.filterValues['安全評等']?.length||state.filterValues['安全評等'].some(v=>v==='700 以上'?+c[1]>=700:v==='600–699'?+c[1]>=600&&+c[1]<700:+c[1]<600)));}
function companiesView(){const list=filteredCompanies();return `${pagebar('公司清單',`<button class="outline" data-nav="discovery">供應商探索</button><button class="outline" data-modal="reports">報表</button><button class="outline" data-modal="company-actions">動作⌄</button>`)}<div class="content company-content">${state.hideBanner?'':`<div class="banner"><span>ⓘ　部分公司可能將資產的安全控制委由其他單位管理。示範資料僅用於說明清單操作與篩選。</span><button data-hide-banner>×</button></div>`}<div class="companies-layout"><div class="filters"><div class="filter-top"><button class="active">▽ 篩選</button><button data-modal="columns">▥</button><button data-modal="views">♧</button></div><input class="filter-search" placeholder="搜尋篩選條件…"><div class="filter-scroll" id="filterRows">${filterRows()}</div><button class="filter-bottom" data-modal="create-view">建立檢視</button></div><div class="panel table-panel"><div class="table-tools"><span>${list.length} 家公司</span><button data-modal="reports">報表⌄</button><button data-modal="company-actions">動作⌄</button><span class="spacer"></span><button title="搜尋" data-toggle="table-search">⌕</button><button title="下載 CSV" data-download>↓</button><button title="全螢幕" data-toggle="fullscreen">⛶</button></div><div id="tableSearch" style="display:none;padding:0 12px 10px"><input id="companySearch" placeholder="搜尋公司" value="${e(state.query)}" style="padding:8px;border:1px solid #cbd7e2;border-radius:5px;width:250px"></div><div class="table-scroll"><table class="data-table"><thead><tr><th><input type="checkbox" data-select-all></th><th>公司　↑</th><th>安全評等</th><th>趨勢</th><th>層級</th><th>關係</th><th>訂閱類型</th></tr></thead><tbody>${list.map((c,i)=>`<tr><td><input type="checkbox" class="row-check"></td><td class="name" data-company="${companies.indexOf(c)}">▣　${e(c[0])}</td><td class="rating ${+c[1]<700?'medium':''}">${c[1]}</td><td class="spark">⌁⌁⌁⌁</td><td>${c[3]}</td><td>${c[4]}</td><td>持續監控</td></tr>`).join('')}</tbody></table>${list.length?'':'<div class="empty">沒有符合條件的公司</div>'}</div><div class="pager"><button data-toast="可選擇每頁顯示筆數">30⌄</button><span>1 – ${list.length}，共 ${list.length} 筆</span><span class="spacer"></span><button>‹</button><span>1 / 1</span><button>›</button></div></div></div><div class="footer">獨立繁體中文操作範例 · 所有公司與評分均為示意資料</div></div>`;}
const discovered=[['範例雲端運算','科技','已確認','高','cloud.example'],['範例辦公軟體','科技','已確認','高','office.example'],['範例客戶管理','科技','已確認','中','crm.example'],['範例支付服務','金融','疑似','中','pay.example'],['範例電信網路','電信','疑似','低','network.example']];
function discoveryView(){const list=discovered.map((x,i)=>[...x,i]).filter(x=>(!state.discoveryQuery||x[0].includes(state.discoveryQuery))&&(!state.showSubscribed||state.subscribed.includes(x[5])));const selected=discovered[state.discoverySelected];return `${pagebar('供應商探索')}<div class="content discovery-page"><div class="discovery-tools"><button class="outline" data-discovery-action="subscribe">訂閱⌄</button><button class="outline" data-discovery-action="unsubscribe">取消訂閱</button><label class="switch"><input type="checkbox" id="showSubscribed" ${state.showSubscribed?'checked':''}> 僅顯示已訂閱</label><span class="spacer"></span><input id="discoverySearch" value="${e(state.discoveryQuery)}" placeholder="搜尋建議供應商…"><button class="outline" data-download-discovery>↓</button><button class="outline" data-modal="discovery-actions">⌄</button></div><div class="discovery-body"><div class="discovery-list"><div class="discovery-head"><span>公司　↕</span><span>產業</span><span>確定程度</span><span>相關性</span></div>${list.map(c=>`<button class="discovery-row ${state.discoverySelected===c[5]?'selected':''}" data-discovery="${c[5]}"><span><input type="checkbox" class="discovery-check" ${state.subscribed.includes(c[5])?'checked':''}> <b>${e(c[0])}</b><small>${e(c[4])}</small></span><span>${e(c[1])}</span><span>${e(c[2])}</span><span class="relevance">◢<small>${e(c[3])}</small></span></button>`).join('')}${list.length?'':'<div class="empty">沒有符合條件的供應商</div>'}</div><aside class="discovery-detail"><div class="discovery-detail-head"><strong>${e(selected[0])}</strong><small>${e(selected[4])}</small></div><div class="discovery-detail-body"><p>這是系統建議的潛在供應商。請根據產品使用、技術關聯與組織資訊判斷是否需要監控。</p><dl><dt>產業</dt><dd>${e(selected[1])}</dd><dt>確定程度</dt><dd>${e(selected[2])}</dd><dt>相關性</dt><dd>${e(selected[3])}</dd></dl><h3>建議原因</h3><p>在示範資產中觀察到與此供應商相關的技術參照。</p><h3>已辨識產品</h3><ul><li>範例雲端平台</li><li>範例網路服務</li></ul><div class="detail-actions"><button class="outline" data-discovery-action="decline">排除此供應商</button><button class="outline" data-discovery-action="subscribe">${state.subscribed.includes(state.discoverySelected)?'已訂閱':'訂閱'}</button></div></div></aside></div></div>`;}
const reportGroups=[['我儲存與排程的報表',[['主管報表 A','最近儲存：2026 年 9 月 11 日','JSON · PDF'],['主管報表','最近儲存：2026 年 9 月 11 日','JSON · PDF'],['基準比較','下次產生：2026 年 10 月 1 日','PDF'],['每月績效','下次產生：2026 年 10 月 1 日','PDF']]],['總覽與主管報告',[['公司總覽','公司安全評等摘要','PDF'],['公司預覽','近期風險變化摘要','PDF'],['投資組合總覽','跨公司風險分析','PDF']]]];
function reportsView(){return `${pagebar('報表',`<button class="outline" data-modal="create-report">建立自訂報表</button>`)}<div class="report-search"><input id="reportSearch" placeholder="搜尋…"></div><div class="report-layout"><div class="report-groups">${reportGroups.map(([group,items])=>`<section><h2>◉　${group}</h2><div class="report-cards">${items.map(([name,description,formats])=>`<button class="report-card" data-report="${e(name)}"><span class="report-illustration">▤</span><span><strong>${e(name)}</strong><small>${e(description)}</small><small>${e(formats)}</small></span></button>`).join('')}</div></section>`).join('')}</div><aside class="report-info"><div class="panel"><h3>精選報表</h3><h4>公司相對風險</h4><p>比較公司在資安事件或勒索軟體風險中的相對位置。</p></div><div class="panel"><h3>你知道嗎？</h3><p>儲存常用報表後，就能快速再次產生，排程報表也可定期提供更新。</p></div></aside></div>`;}
const alerts=[['2026/09/05','範例商業銀行','感染事件','惡意程式訊號','層級 1','高'],['2026/09/02','範例資訊服務','弱點','CVE-2026-1293','層級 2','中'],['2026/08/24','範例電信公司','安全評等','評等下降 20 分','層級 1','高'],['2026/08/15','範例保險公司','公開揭露','資安事件通報','層級 2','重大'],['2026/08/10','範例雲端服務','感染事件','可疑活動','層級 2','中']];
const alertFilters=[['類別',['資訊型風險面向','NIST CSF 等級','公開揭露','風險面向等級','安全評等','弱點與感染事件','威脅情報事件']],['嚴重程度',['增加','下降','重大下降']],['公司',['範例商業銀行','範例資訊服務','範例電信公司']]];
function alertsView(){const list=alerts.filter(a=>(!state.alertQuery||a.join(' ').includes(state.alertQuery))&&(!state.alertCategory||a[2]===state.alertCategory)&&(!state.alertSeverity||a[5]===state.alertSeverity));return `${pagebar('投資組合警示',`<button class="outline" data-nav="alert-settings">警示設定</button>`)}<div class="content"><div class="companies-layout"><div class="filters"><div class="filter-top"><button class="active">▽ 篩選</button><button data-modal="alert-views">♧</button></div><input class="filter-search" id="alertFilterSearch" placeholder="搜尋篩選條件…"><div class="filter-scroll">${alertFilters.map(([name,opts])=>`<div class="filter-row"><button data-alert-group="${name}">${name}<span>⌃</span></button><div class="filter-options">${opts.map(o=>`<label><input type="checkbox" data-alert-filter="${name}" value="${o}" ${state.alertCategory===o||state.alertSeverity===o?'checked':''}> ${o}</label>`).join('')}</div></div>`).join('')}</div><button class="filter-bottom" data-modal="create-alert-view">建立檢視</button></div><div class="panel table-panel"><div class="table-tools"><span>${list.length} 筆警示</span><span class="spacer"></span><button data-toggle="alert-search">⌕</button><button data-download-alerts>↓</button><button data-toggle="fullscreen">⛶</button></div><div id="alertSearchBox" style="display:none;padding:0 12px 10px"><input id="alertSearch" value="${e(state.alertQuery)}" placeholder="搜尋警示" style="padding:8px;border:1px solid #cbd7e2;border-radius:5px"></div><div class="table-scroll"><table class="data-table"><thead><tr><th>日期　↓</th><th>公司</th><th>類別</th><th>警示</th><th>層級／資料夾／訂閱</th></tr></thead><tbody>${list.map((a,i)=>`<tr data-alert="${alerts.indexOf(a)}"><td>${a[0]}</td><td class="name">${a[1]}</td><td>${a[2]}</td><td class="name">${a[3]}<br><small>查看發現事項</small></td><td>${a[4]}</td></tr>`).join('')}</tbody></table>${list.length?'':'<div class="empty">沒有符合條件的警示</div>'}</div><div class="pager">顯示 1 – ${list.length}，共 ${list.length} 筆<span class="spacer"></span><button>‹</button>1 / 1<button>›</button></div></div></div></div>`;}
const vulnerabilities=[['CVE-2025-53521','CVSS 9.8','5.76','已在真實環境利用','2%','可能'],['已知遭利用弱點','CVSS 10.0','10','概念驗證程式公開','100%','已確認'],['CVE-2026-3055','CVSS 9.8','8.22','已在真實環境利用','87%','很可能'],['CVE-2025-25249','CVSS 8.1','10','地下社群討論','2%','可能'],['CVE-2026-42016','CVSS 7.5','7.2','近期支援','12%','可能']];
function vulnerabilityView(){const list=vulnerabilities.filter(v=>!state.vulnQuery||v.join(' ').toLowerCase().includes(state.vulnQuery.toLowerCase()));return `${pagebar('弱點偵測')}<div class="vuln-summary"><div><small>投資組合中偵測到的弱點</small><p><b>2,848</b> 項弱點</p></div><div><small>14 天暴露趨勢</small><p>↗　暴露增加</p><button data-toast="已套用暴露趨勢篩選">套用為篩選條件</button></div><div><small>近期支援的弱點</small><p>CVE-2026-42016</p><span>4 天前加入</span></div><button class="outline" data-toggle="vuln-summary">查看完整分析 ⌄</button></div><div class="content"><div class="companies-layout"><div class="filters"><div class="filter-top"><button class="active">▽ 篩選</button><button data-modal="columns">▥</button><button data-modal="views">♧</button></div><input class="filter-search" placeholder="搜尋篩選條件…"><div class="filter-scroll"><div class="filter-row"><button>已套用篩選　清除全部</button><div class="filter-options"><span>已在投資組合中偵測</span></div></div>${[['偵測到弱點',['已在投資組合中偵測']],['類別',['一般弱點','已知遭利用弱點']],['嚴重程度',['重大','高','中']],['DVE 分數',['8–10','5–7','0–4']]].map(([name,opts])=>`<div class="filter-row"><button data-filter="${name}">${name}<span>⌄</span></button>${state.filterOpen===name?`<div class="filter-options">${opts.map(o=>`<label><input type="checkbox"> ${o}</label>`).join('')}</div>`:''}</div>`).join('')}</div><button class="filter-bottom" data-modal="create-view">建立檢視</button></div><div class="panel table-panel"><div class="table-tools"><span>${list.length} 項弱點</span><button data-toast="進階威脅情報示範">查看進階威脅情報</button><span class="spacer"></span><button data-toggle="vuln-search">⌕</button><button data-toast="已準備示範匯出">↓</button><button data-toggle="fullscreen">⛶</button></div><div id="vulnSearchBox" style="display:none;padding:0 12px 10px"><input id="vulnSearch" value="${e(state.vulnQuery)}" placeholder="搜尋 CVE 或弱點" style="padding:8px;border:1px solid #cbd7e2;border-radius:5px"></div><div class="table-scroll"><table class="data-table"><thead><tr><th>弱點</th><th>嚴重程度</th><th>DVE 分數</th><th>威脅情報屬性</th><th>EPSS</th><th>證據確定程度</th></tr></thead><tbody>${list.map((v,i)=>`<tr data-vuln="${vulnerabilities.indexOf(v)}">${v.map((x,j)=>`<td class="${j===0?'name':''}">${e(x)}</td>`).join('')}</tr>`).join('')}</tbody></table>${list.length?'':'<div class="empty">沒有符合條件的弱點</div>'}</div><div class="pager">1 – ${list.length}，共 ${list.length} 筆<span class="spacer"></span><button>‹</button>1 / 1<button>›</button></div></div></div></div>`;}
const genericContent={
  'fi-assessments':['評估數','待檢視','已完成'], 'critical-assets':['關鍵資產','高優先','已檢視'],compare:['已選公司','可比較欄位','評等差距'],discovery:['潛在供應商','高相關性','已訂閱'],expired:['已到期','近期到期','需確認'],
  'vendor-overview':['安全評等','風險面向','發現事項'],framework:['框架項目','已對照','待確認'],instant:['主要洞察','近期變化','需關注'],assessments:['進行中','待回覆','已完成'],vectors:['風險面向','良好','待改善'],findings:['發現事項','高風險','已處理'],threat:['威脅訊號','近期事件','需檢視'],tree:['組織節點','評等公司','關聯公司'],remediation:['改善事項','進行中','已完成'],infrastructure:['網路資產','網域','IP 範圍'],breach:['外洩事件','受影響公司','待調查'],vulnerability:['弱點訊號','高嚴重度','受影響公司'],
  'fourth-overview':['第四方公司','關聯供應商','需關注'],providers:['服務提供者','高相關性','共用依賴'],products:['產品','關聯公司','高相關性'],'portfolio-alerts':['未讀警示','本週新增','已處理'],'fourth-alerts':['第四方警示','本週新增','需關注'],reports:['可用報表','最近產生','已排程'],invitations:['待接受邀請','已接受','已過期'],'access-links':['有效連結','已過期','待審查'],contacts:['供應商聯絡人','有聯絡人公司','待補齊'],'alert-settings':['啟用規則','通知對象','已暫停'],folders:['資料夾','已分類公司','未分類'],tiers:['層級','已指派公司','未指派'],integrations:['可用整合','已連接','待設定']
};
function genericView(){const title=names[state.page],labels=genericContent[state.page]||['總計','待處理','已完成'];let values=state.page==='discovery'?['241','64','18']:state.page==='reports'?['8','3','2']:['12','3','7'];let headers=state.page==='discovery'?['公司','產業','確定程度','相關性','狀態']:state.page.includes('alerts')?['警示','公司','類型','日期','狀態']:state.page==='reports'?['報表名稱','範圍','建立日期','狀態','操作']:['項目','關聯公司','類型','更新時間','狀態'];const rows=state.page==='discovery'?[['範例雲端服務商','科技','已確認','高','未訂閱'],['範例支付平台','金融','已確認','中','已訂閱'],['範例軟體公司','科技','疑似','低','未訂閱']]:state.page==='reports'?[['投資組合總覽','全部公司','2026-09-14','可下載','查看'],['供應商評等摘要','重要供應商','2026-09-10','可下載','查看']]:[['範例項目 A','範例商業銀行','風險資訊','2026-09-14','需檢視'],['範例項目 B','範例資訊服務','監控資訊','2026-09-12','已確認'],['範例項目 C','範例電信公司','變動資訊','2026-09-10','處理中']];return `${pagebar(title,`<button class="outline" data-modal="${state.page}-action">${state.page==='reports'?'建立報表':'動作'}⌄</button>`)}<div class="content"><div class="panel generic"><div class="generic-toolbar"><input id="genericSearch" placeholder="搜尋${title}…"><select id="genericStatus"><option>全部狀態</option><option>需檢視</option><option>已確認</option></select><button class="outline" data-toast="已重新整理示範資料">重新整理</button></div><div class="generic-grid">${labels.map((l,i)=>`<div class="panel generic-card"><small>${l}</small><strong>${values[i]}</strong></div>`).join('')}</div><div class="table-scroll"><table class="data-table" id="genericTable"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map((r,i)=>`<tr data-generic-row="${i}">${r.map((x,j)=>`<td ${j===0?'class="name"':''}>${e(x)}</td>`).join('')}</tr>`).join('')}</tbody></table></div><div class="pager">共 ${rows.length} 筆示範資料</div></div><div class="footer">本頁重現主要操作模式；細節依原系統可見畫面逐步校對</div></div>`;}
function drawer(){if(state.selected===null)return '';const c=companies[state.selected];return `<div class="drawer-back" data-close-drawer></div><aside class="drawer"><div class="drawer-head"><button data-close-drawer>×</button>${e(c[0])}<button style="margin-left:auto" data-nav="vendor-overview" title="開啟公司總覽">↗</button></div><div class="drawer-body"><b>評等詳情</b><div class="drawer-cards"><div class="drawer-card"><h3>Bitsight 安全評等</h3><div class="gauge"><b>${c[1]}</b></div><p style="text-align:center">進階 · 示意評分</p><button class="outline" style="display:block;margin:40px auto 0" data-nav="tree">查看評等樹</button></div><div class="drawer-card"><h3>公司資訊</h3><p style="line-height:1.6;margin:35px 0">${e(c[0])} 為本範例使用的虛構公司，資料只用來展示介面操作。</p><dl><dt>產業</dt><dd>金融／科技</dd><dt>監控者</dt><dd>12 家公司</dd><dt>關係</dt><dd>${e(c[4])}</dd></dl><button class="outline" style="float:right;margin-top:30px" data-nav="vendor-overview">顯示詳情</button></div></div><div class="drawer-card"><h3>安全評等變化</h3><div style="height:200px;margin-top:30px;background:linear-gradient(175deg,transparent 48%,#e8eff5 49%);border-bottom:1px solid #bed0dd;display:flex;align-items:center;justify-content:center;color:#396888;letter-spacing:10px">● ● ● ● ● ● ● ● ● ●</div><p>2026 年 · 示意趨勢</p></div></div></aside>`;}
function modal(){if(!state.modal)return '';if(state.modal.startsWith('vuln:')){const v=vulnerabilities[+state.modal.slice(5)];return `<div class="modal-back" data-close-modal><div class="modal"><h2>${e(v[0])}</h2><p><b>嚴重程度：</b>${e(v[1])}</p><p><b>DVE 分數：</b>${e(v[2])}</p><p><b>威脅情報：</b>${e(v[3])}</p><p><b>證據確定程度：</b>${e(v[5])}</p><div class="modal-foot"><button data-close-modal>關閉</button><button class="save" data-nav="findings">查看發現事項</button></div></div></div>`;}if(state.modal.startsWith('report:'))return `<div class="modal-back" data-close-modal><div class="modal"><h2>${e(state.modal.slice(7))}</h2><p>選擇報表範圍與格式，產生示範報表。此操作不會連接 BitSight 帳號。</p><label>範圍<select id="modalInput"><option>全部公司</option><option>重要供應商</option></select></label><label>格式<select><option>PDF</option><option>JSON</option></select></label><div class="modal-foot"><button data-close-modal>取消</button><button class="save" data-save-modal>產生</button></div></div></div>`;if(state.modal.startsWith('alert:')){const a=alerts[+state.modal.slice(6)];return `<div class="modal-back" data-close-modal><div class="modal"><h2>${e(a[3])}</h2><p><b>公司：</b>${e(a[1])}</p><p><b>類別：</b>${e(a[2])}</p><p><b>日期：</b>${e(a[0])}</p><p>這筆示範警示可作為追查發現事項的起點。</p><div class="modal-foot"><button data-close-modal>關閉</button><button class="save" data-nav="findings">查看發現事項</button></div></div></div>`;}const title={'view':'選擇檢視','add-card':'新增卡片','edit-dashboard':'編輯儀表板','reports':'報表','company-actions':'公司動作','columns':'欄位設定','views':'檢視方式','create-view':'建立檢視','create-report':'建立自訂報表'}[state.modal]||`${names[state.page]}操作`;return `<div class="modal-back" data-close-modal><div class="modal"><h2>${title}</h2>${state.modal==='view'?`<label>檢視<select id="modalInput"><option>全部公司</option><option>重要供應商</option><option>金融服務</option></select></label>`:state.modal==='columns'?`<label><input type="checkbox" checked> 安全評等</label><label><input type="checkbox" checked> 趨勢</label><label><input type="checkbox" checked> 層級</label><label><input type="checkbox" checked> 關係</label>`:`<label>名稱或選項<input id="modalInput" placeholder="輸入示範名稱"></label>`}<div class="modal-foot"><button data-close-modal>取消</button><button class="save" data-save-modal>確認</button></div></div></div>`;}
function render(){const portfolio=['fi-assessments','critical-assets','compare','expired'];const vendor=['vendor-overview','framework','instant','assessments','vectors','findings','threat','tree','remediation','infrastructure'];const ecosystem=['breach','fourth-overview','providers','products','fourth-alerts'];const admin=['invitations','access-links','contacts','alert-settings','folders','tiers','integrations'];const view=portfolio.includes(state.page)?portfolioView(state.page):vendor.includes(state.page)?vendorView(state.page):ecosystem.includes(state.page)?ecosystemView(state.page):admin.includes(state.page)?adminView(state.page):state.page==='dashboard'?dashboard():state.page==='companies'?companiesView():state.page==='discovery'?discoveryView():state.page==='reports'?reportsView():state.page==='portfolio-alerts'?alertsView():state.page==='vulnerability'?vulnerabilityView():genericView();app.innerHTML=`<div class="shell"><aside class="side ${state.collapsed?'collapsed':''}"><div class="logo">BITSIGHT</div><div class="app-switch"><span class="dots">⠿</span><span>持續監控</span></div><div class="menu">${nav()}</div></aside><button class="collapse" data-collapse>${state.collapsed?'›':'‹'}</button><div class="main-shell">${topbar()}${view}${globalFooter()}</div></div>${drawer()}${modal()}${state.toast?`<div class="toast">${e(state.toast)}</div>`:''}<button class="help" data-tour title="開啟操作導覽">?</button>`;}
function go(id){state.page=id;state.open=parentFor(id);state.selected=null;state.modal=null;history.replaceState(null,'','#'+id);render();window.scrollTo(0,0);}
function showToast(t){state.toast=t;render();setTimeout(()=>{state.toast='';render();},2400);}
app.addEventListener('click',event=>{const x=event.target.closest('button,[data-company],[data-generic-row],[data-close-modal],[data-close-drawer]');if(!x)return;if(x.dataset.nav){go(x.dataset.nav);return;}if(x.dataset.group&&!x.dataset.nav){state.open=state.open===x.dataset.group?'':x.dataset.group;render();return;}if(x.hasAttribute('data-company')){state.selected=+x.dataset.company;render();return;}if(x.hasAttribute('data-close-drawer')){state.selected=null;render();return;}if(x.dataset.modal){state.modal=x.dataset.modal;render();return;}if(x.hasAttribute('data-close-modal')){state.modal=null;render();return;}if(x.hasAttribute('data-save-modal')){if(state.modal==='view')state.view=document.getElementById('modalInput').value;state.modal=null;showToast('已套用示範設定');return;}if(x.dataset.filter){state.filterOpen=state.filterOpen===x.dataset.filter?'':x.dataset.filter;render();return;}if(x.hasAttribute('data-hide-banner')){state.hideBanner=true;render();return;}if(x.dataset.update){state.update=(state.update+(x.dataset.update==='next'?1:2))%3;render();return;}if(x.dataset.toggle==='table-search'){const el=document.getElementById('tableSearch');el.style.display=el.style.display==='none'?'block':'none';return;}if(x.dataset.toggle==='updates'){const el=document.getElementById('updates');el.style.display=el.style.display==='none'?'grid':'none';return;}if(x.dataset.toggle==='fullscreen'){document.querySelector('.table-panel').requestFullscreen?.();return;}if(x.hasAttribute('data-collapse')){state.collapsed=!state.collapsed;render();return;}if(x.hasAttribute('data-download')){const csv='公司,安全評等,層級,關係\n'+filteredCompanies().map(c=>[c[0],c[1],c[3],c[4]].join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv'}));a.download='示範公司清單.csv';a.click();URL.revokeObjectURL(a.href);return;}if(x.hasAttribute('data-generic-row')){showToast('已開啟示範項目');return;}if(x.dataset.toast){showToast(x.dataset.toast);return;}});
app.addEventListener('change',event=>{const x=event.target;if(x.hasAttribute('data-select-all')){document.querySelectorAll('.row-check').forEach(c=>c.checked=x.checked);return;}if(x.dataset.filterValue){let arr=state.filterValues[x.dataset.filterValue]||[];arr=x.checked?[...arr,x.value]:arr.filter(v=>v!==x.value);state.filterValues[x.dataset.filterValue]=arr;render();}if(x.id==='period'){state.period=x.value;showToast(`已切換為 ${x.value}`);}if(x.id==='genericStatus'){document.querySelectorAll('[data-generic-row]').forEach(row=>row.style.display=x.value==='全部狀態'||row.textContent.includes(x.value)?'':'none');}});
app.addEventListener('input',event=>{const x=event.target;if(x.id==='companySearch'){state.query=x.value;const pos=x.selectionStart;render();const input=document.getElementById('companySearch');input.closest('#tableSearch').style.display='block';input.focus();input.setSelectionRange(pos,pos);}if(x.classList.contains('filter-search')){document.getElementById('filterRows').innerHTML=filterRows();}if(x.id==='genericSearch'){document.querySelectorAll('[data-generic-row]').forEach(row=>row.style.display=row.textContent.includes(x.value)?'':'none');}});
window.addEventListener('hashchange',()=>go(location.hash.slice(1)||'dashboard'));
go(names[location.hash.slice(1)]?location.hash.slice(1):'dashboard');

app.addEventListener('click',event=>{
  const discovery=event.target.closest('[data-discovery]');
  if(discovery&&!event.target.classList.contains('discovery-check')){state.discoverySelected=+discovery.dataset.discovery;render();return;}
  const action=event.target.closest('[data-discovery-action]');
  if(action){const id=state.discoverySelected;if(action.dataset.discoveryAction==='subscribe'){if(!state.subscribed.includes(id))state.subscribed.push(id);showToast('已將示範供應商加入訂閱');}else if(action.dataset.discoveryAction==='unsubscribe'){state.subscribed=state.subscribed.filter(x=>x!==id);showToast('已取消示範訂閱');}else showToast('已排除此示範供應商');return;}
  const report=event.target.closest('[data-report]');
  if(report){state.modal='report:'+report.dataset.report;render();return;}
  const alert=event.target.closest('[data-alert]');
  if(alert){state.modal='alert:'+alert.dataset.alert;render();return;}
  if(event.target.closest('[data-download-discovery]')){showToast('示範清單已準備下載');return;}
  if(event.target.closest('[data-download-alerts]')){showToast('示範警示已準備下載');return;}
  if(event.target.closest('[data-toggle="alert-search"]')){const box=document.getElementById('alertSearchBox');if(box)box.style.display=box.style.display==='none'?'block':'none';}
  const vuln=event.target.closest('[data-vuln]');if(vuln){state.modal='vuln:'+vuln.dataset.vuln;render();return;}
  if(event.target.closest('[data-toggle="vuln-search"]')){const box=document.getElementById('vulnSearchBox');if(box)box.style.display=box.style.display==='none'?'block':'none';}
  if(event.target.closest('[data-toggle="vuln-summary"]'))showToast('已展開示範分析');
});
app.addEventListener('input',event=>{
  const x=event.target;
  if(x.id==='discoverySearch'){state.discoveryQuery=x.value;const at=x.selectionStart;render();const input=document.getElementById('discoverySearch');input.focus();input.setSelectionRange(at,at);}
  if(x.id==='reportSearch'){document.querySelectorAll('.report-card').forEach(card=>card.style.display=card.textContent.includes(x.value)?'grid':'none');}
  if(x.id==='alertSearch'){state.alertQuery=x.value;const at=x.selectionStart;render();const input=document.getElementById('alertSearch');input.closest('#alertSearchBox').style.display='block';input.focus();input.setSelectionRange(at,at);}
  if(x.id==='vulnSearch'){state.vulnQuery=x.value;const at=x.selectionStart;render();const input=document.getElementById('vulnSearch');input.closest('#vulnSearchBox').style.display='block';input.focus();input.setSelectionRange(at,at);}
});
app.addEventListener('change',event=>{
  const x=event.target;
  if(x.id==='showSubscribed'){state.showSubscribed=x.checked;render();}
  if(x.dataset.alertFilter){if(x.dataset.alertFilter==='類別')state.alertCategory=x.checked?({'弱點與感染事件':'感染事件','公開揭露':'公開揭露','安全評等':'安全評等'}[x.value]||x.value):'';if(x.dataset.alertFilter==='嚴重程度')state.alertSeverity=x.checked?({'重大下降':'重大','下降':'中','增加':'高'}[x.value]||x.value):'';render();}
});

function dashboard(){const headlines=['未經驗證的 GitLab 路徑穿越可任意讀取檔案','供應鏈套件風險通報','雲端服務設定異常'];return `${pagebar('投資組合儀表板',`<select class="outline" id="period"><option>30 天</option><option>90 天</option><option>1 年</option></select><button class="outline" data-modal="add-card">新增卡片</button><button class="outline" data-modal="edit-dashboard">編輯儀表板</button>`)}<div class="content dashboard-page"><div class="panel dash-panel"><div class="dash-title">最新更新 <button data-toggle="updates">隱藏　⌃</button></div><div id="updates" class="updates"><div class="update-card"><h2>△　10 項新興資安事件</h2><hr><h3>${headlines[state.update]}</h3><div class="meta"><span><b>嚴重程度</b><br>CVSS 10.0</span><span><b>暴露趨勢</b><br>5 家公司 ↗</span><span><b>受影響公司</b><br>5 家公司</span><span><b>DVE 分數</b><br>10</span></div><p><b>說明</b></p><p>此重大弱點可能讓未經驗證的攻擊者讀取伺服器敏感檔案。建議立即檢查受影響資產並套用修補程式。</p><div class="advisories">▮ NVD 公告　　▮ 供應商公告</div><div class="update-foot"><button class="outline" data-update="prev">←</button><span>${state.update+1} / 3</span><button class="outline" data-nav="vulnerability">查看弱點</button><button class="outline" data-update="next">→</button></div></div><div class="update-card news-card"><h3><b>威脅情報新聞</b>　<em>BitSight pulse</em></h3><hr><h3>Microsoft 偵測到利用 ASCII 偷渡來規避篩選的網路釣魚活動</h3><p>研究人員發現一波大量網路釣魚活動，利用提示注入研究中常見的技術規避郵件安全機制。</p><div class="update-foot"><span>2026/09/15</span><button class="outline" data-nav="threat">繼續閱讀</button></div></div></div></div>${dashboardCards()}</div>`}
