function emptyDashCard(title,icon,text,label,nav){return `<section class="panel dash-widget empty-widget"><header>${title}<span>30 天　⋮</span></header><div class="empty-icon">${icon}</div><p>${text}</p><button data-nav="${nav}">${label}</button></section>`}
function dashboardCards(){const tasks=['訂閱公司','新增使用者','新增群組','建立層級','建立資料夾','建立警示','設定報告','邀請公司'];const tiers=[['第 1 級',9,6,3],['第 2 級',8,7,1],['第 3 級',7,7,0]];return `<div class="dashboard-grid original-cards">
<section class="panel dash-widget rating-widget"><header>評等中位數<span>30 天　⋮</span></header><div class="median-main"><span>±0</span><strong>760</strong></div><div class="median-gauge"><i></i></div><p class="advanced">● 進階</p><button data-nav="companies">前往公司清單</button></section>
<section class="panel dash-widget featured-widget"><header>精選報告<span>⋮</span></header><div class="report-art">▤</div><h3>公司相對風險</h3><p>查看公司相對風險與資安事件的關聯，以及成為勒索軟體目標的可能性。</p><div class="card-links"><button data-nav="reports">前往報告</button><button data-toast="已建立示範報告">建立報告</button></div></section>
<section class="panel dash-widget getting-widget"><header>開始使用<span>⋮</span></header><div class="task-progress"><strong>8 / 8</strong><span>項工作已完成</span><i><b></b></i></div><ul class="setup-tasks">${tasks.map(x=>`<li><i>✓</i>${x}</li>`).join('')}</ul><button data-toast="已開啟更換卡片選單">更換卡片</button></section>
<section class="panel dash-widget matrix-widget"><header>投資組合風險矩陣<span>⋮</span></header><div class="risk-matrix"><div class="risk-axis">關鍵性</div><div class="risk-head"><span>低風險<br><b>820</b></span><span>高風險<br><b>300</b></span></div>${tiers.map(r=>`<div class="risk-row"><label>${r[0]}<small>${r[1]} 家公司</small></label><button class="monitor" data-nav="companies">${r[2]}</button><button class="review" data-nav="companies">${r[3]}</button><button class="escalate" data-nav="companies">0</button></div>`).join('')}<div class="risk-caption">風險</div></div><div class="action-plan"><b>處置計畫</b><span><i class="escalate"></i><strong>升級處理</strong><small>聯絡供應商處理不可接受的發現。</small></span><span><i class="review"></i><strong>審查</strong><small>調查是否需要採取行動。</small></span><span><i class="monitor"></i><strong>監控</strong><small>目前無需立即採取行動。</small></span></div><button data-nav="companies">前往公司清單</button></section>
<section class="panel dash-widget changes-widget"><header>評等變化<span>30 天　⋮</span></header><div class="change-summary"><b>74%</b><i></i><b>26%</b></div><p>19 家供應商的評等發生變化</p><table><tr><td>永豐金融控股集團</td><td class="down">↓ -40</td><td>710</td></tr><tr><td>永豐金融控股公司</td><td class="down">↓ -30</td><td>740</td></tr><tr><td>精誠資訊集團</td><td class="down">↓ -30</td><td>730</td></tr></table><button data-nav="companies">查看所有評等變化</button></section>
${emptyDashCard('近期資安事件','✓','此期間內，這個資料夾中的公司未發生資安事件。','查看所有資安事件','companies')}${emptyDashCard('風險向量警示','⚑','目前沒有可用的警示。','查看所有警示','alerts')}
<section class="panel dash-widget trending-widget"><header>熱門供應商<span>⋮</span></header><div class="trend-vendor"><i>B</i><div><b>BASF Group</b><small>搜尋量增加 100%</small><p>總部位於德國的企業集團。</p></div><button data-toast="已訂閱 BASF Group">訂閱</button></div><footer>←　1 / 20　→</footer></section>
${emptyDashCard('生命週期','○','套用的篩選條件中，沒有公司處於重新評估階段。','前往公司清單','companies')}
<section class="panel dash-widget subscription-widget"><header>已使用與已分配訂閱<span>⋮</span></header><strong>100%</strong><label>持續監控 <span>50 / 50</span><i><b></b></i></label><label>供應商選擇 <span>250 / 250</span><i><b></b></i></label><button data-toast="已開啟訂閱明細">查看全部</button></section></div>`}
