const ecoState={query:'',provider:0,onlyCritical:false};
const breachRows=[['範例商業銀行','憑證資料外洩','高','12,480','2026/09/11'],['範例雲端服務','第三方資料集曝光','重大','38,920','2026/09/07'],['範例電信公司','帳號密碼外洩','中','2,150','2026/08/28'],['範例資訊服務','原始碼憑證曝光','高','460','2026/08/19']];
const providersData=[['範例雲端平台','6','4','高','720'],['範例內容傳遞網路','5','3','中','760'],['範例身分驗證服務','4','2','重大','690'],['範例支付閘道','3','2','中','740'],['範例協作軟體','2','1','低','810']];
const productsData=[['雲端運算平台','範例雲端平台','6','基礎設施','高'],['單一登入服務','範例身分驗證服務','4','身分管理','重大'],['全球內容傳遞','範例內容傳遞網路','5','網路服務','中'],['線上支付模組','範例支付閘道','3','金融科技','中']];
function ecoTools(label,count){return `<div class="eco-tools"><button class="outline active">${label}</button><input id="ecoSearch" value="${e(ecoState.query)}" placeholder="搜尋…"><label><input id="ecoCritical" type="checkbox" ${ecoState.onlyCritical?'checked':''}> 僅顯示重大／高風險</label><span>${count} 筆結果</span><button class="outline" data-toast="已準備示範匯出">下載</button></div>`}
function breachView(){const filters=['嚴重程度','事件類型','評等影響','來源類型','國家／地區','產業','公司','日期','攻擊者','APT','CVE','受影響產品'];return `${pagebar('資料外洩情報',`<button class="outline" data-toast="已準備 CSV">↓　下載 CSV</button>`)}<div class="breach-layout"><aside class="fi-filter"><div class="filter-top"><button class="active">▽ 篩選</button><span>‹</span></div><input placeholder="搜尋篩選條件…">${filters.map(x=>`<button class="finding-filter-row">${x}<span>⌄</span></button>`).join('')}</aside><main class="breach-results"><div class="breach-tabs"><button class="active"><b>13</b> 全部事件<small>目前投資組合選取範圍</small></button><button><b>11</b> <span>⚑ 公開揭露</span><small>來自可信的公開資訊</small></button><button><b>2</b> <span class="red-label">⚑ 威脅情報*</span><small><b>潛在事件：</b>來自深網、暗網與開放網路監控</small></button></div><div class="breach-feed"><article class="breach-event"><div><span class="dark-label">⚑ 公開揭露</span><h2>範例高速鐵路公司受到資料外洩影響</h2><p><b>受影響供應商</b>　<span class="linkish">範例高速鐵路公司</span></p><p>該公司發生資安事件，影響部分系統的可用性。</p></div><aside><button data-breach-row>查看詳情</button><p>▣ <b>日期</b><br>2026 年 5 月 6 日</p><p>⚑ <b>事件類型</b><br>未公開事件類型</p><p>△ <b>嚴重程度</b><br><i>● 中</i></p><p>✓ <b>已驗證</b><br>影響評等</p></aside></article><article class="breach-event"><div><span class="red-label">⚑ 威脅情報*</span> <span class="blue-label">網路新聞</span><h2>潛在事件：學生因入侵高速鐵路系統遭逮捕</h2><p><b>受影響供應商</b>　<span class="linkish">範例高速鐵路公司</span></p></div><aside><button data-breach-row>查看詳情</button><p>▣ <b>日期</b><br>2026 年 5 月 5 日</p><p>⚑ <b>事件類型</b><br>網路犯罪</p></aside></article></div></main></div>`}
function alertFeed(){return `<div class="alert-feed"><button data-nav="providers"><span class="severity severity-重大">重大</span><b>身分驗證服務評等下降 35 分</b><small>影響 4 家公司 · 2 天前</small></button><button data-nav="products"><span class="severity severity-高">高</span><b>雲端運算平台出現新的重大弱點</b><small>影響 6 家公司 · 5 天前</small></button></div>`}
function fourthOverview(){const tile=(n,c)=>`<button class="fp-tile ${c}" data-nav="providers"><span>${n}</span></button>`;const red=['Google Corporation','The Apache Software Foundation','Microsoft Group of Companies','Cisco Systems','Meta Corporation'];const amber=['World Wide Web Consortium, Inc.','OpenJS Foundation Corporation','Web Hypertext Application Technology Working Group','Bootstrap','Content Security Policy','F5 Group','Domain-based Message Authentication','BuiltWith Pty Ltd','Oracle Corporation Group of Companies','Wikimedia Foundation, Inc.','web.dev','Apple Corporation','W3Schools','Taiwan Chinese Medical Association','Fonticons, Inc.','Cloudflare, Inc.','Swiper','Internet Corporation for Assigned Names and Numbers','PHP Group'];const green=['Microsoft','Chunghwa Telecom Group','TAIWAN-CA Inc.','Vue.js','Amazon Web Services, Inc.','Modernizr'];return `${pagebar('第四方風險總覽',`<button class="outline" data-toast="已開啟儀表板編輯模式">編輯儀表板</button>`)}<div class="content fp-page"><section class="panel fp-dashboard"><header><h2>評等與集中度</h2><label class="fp-switch"><input id="fpTop" type="checkbox" checked><i></i><span>顯示相依度超過 50% 的前 30 項</span></label></header><div class="fp-treemap"><div class="fp-band fp-red"><b>評等 250–630 的第四方</b><div>${red.map(x=>tile(x,'red')).join('')}</div></div><div class="fp-band fp-amber"><b>評等 640–730 的第四方</b><div>${amber.map(x=>tile(x,'amber')).join('')}</div></div><div class="fp-band fp-green"><b>評等 740–900 的第四方</b><div>${green.map(x=>tile(x,'green')).join('')}</div></div></div></section><div class="fp-stats"><section class="panel"><h3>第四方評等中位數</h3><strong class="amber-text">700</strong><span><i class="amber-dot"></i>中等</span><p>目前投資組合內所有第四方服務提供者的安全評等中位數</p></section><section class="panel"><h3>服務提供者</h3><strong>28</strong><span>相依度超過 50%</span><p>出現在受監控公司技術供應鏈中的服務提供者</p><button data-nav="providers">查看服務提供者 →</button></section><section class="panel"><h3>產品集中度</h3><strong>97</strong><span>相依度超過 50%</span><p>由第四方服務提供者供應，且具有高度集中風險的產品</p><button data-nav="products">查看產品 →</button></section></div></div>`}
function providerView(){let rows=providersData.map((r,i)=>[...r,i]).filter(r=>(!ecoState.query||r.join(' ').includes(ecoState.query))&&(!ecoState.onlyCritical||['重大','高'].includes(r[3])));const p=providersData[ecoState.provider];return `${pagebar('服務提供者')}${ecoTools('服務提供者',rows.length)}<div class="provider-layout"><section class="panel"><table class="data-table"><thead><tr><th>服務提供者</th><th>關聯公司</th><th>關聯產品</th><th>風險</th><th>安全評等</th></tr></thead><tbody>${rows.map(r=>`<tr data-provider="${r[5]}" class="${r[5]===ecoState.provider?'selected-row':''}"><td class="name">${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td><td><span class="severity severity-${r[3]}">${r[3]}</span></td><td>${r[4]}</td></tr>`).join('')}</tbody></table></section><aside class="panel provider-detail"><h2>${p[0]}</h2><div class="provider-rating">${p[4]}</div><p>此服務提供者同時出現在 ${p[1]} 家受監控公司的技術依賴中。</p><h3>關聯公司</h3><ul><li>範例商業銀行</li><li>範例資訊服務</li><li>範例保險公司</li></ul><button class="outline" data-nav="products">查看關聯產品</button></aside></div>`}
function productsView(){const rows=productsData.filter(r=>(!ecoState.query||r.join(' ').includes(ecoState.query))&&(!ecoState.onlyCritical||['重大','高'].includes(r[4])));return `${pagebar('產品')}${ecoTools('產品',rows.length)}<div class="content"><section class="panel"><table class="data-table"><thead><tr><th>產品</th><th>服務提供者</th><th>關聯公司</th><th>產品類型</th><th>風險</th></tr></thead><tbody>${rows.map(r=>`<tr data-product-row><td class="name">${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td><td>${r[3]}</td><td><span class="severity severity-${r[4]}">${r[4]}</span></td></tr>`).join('')}</tbody></table></section></div>`}
function fourthAlerts(){return `${pagebar('第四方警示',`<button class="outline" data-toast="已開啟第四方警示設定">警示設定</button>`)}<div class="content">${ecoTools('全部警示',2)}<section class="panel eco-card">${alertFeed()}</section></div>`}
function ecosystemView(page){return page==='breach'?breachView():page==='fourth-overview'?fourthOverview():page==='providers'?providerView():page==='products'?productsView():fourthAlerts()}
document.addEventListener('click',event=>{const x=event.target.closest('[data-provider],[data-breach-row],[data-product-row]');if(!x)return;if(x.dataset.provider!==undefined){ecoState.provider=+x.dataset.provider;render()}else showToast(x.hasAttribute('data-breach-row')?'已開啟外洩事件詳情':'已開啟產品關聯詳情')});
document.addEventListener('input',event=>{if(event.target.id==='ecoSearch'){ecoState.query=event.target.value;const p=event.target.selectionStart;render();const i=document.getElementById('ecoSearch');i.focus();i.setSelectionRange(p,p)}});
document.addEventListener('change',event=>{if(event.target.id==='ecoCritical'){ecoState.onlyCritical=event.target.checked;render()}});
