const ecoState={query:'',provider:0,onlyCritical:false,breachFilterOpen:'',breachFilters:{},providerFilterOpen:'',providerFilterQuery:'',providerFilters:{},productFilterOpen:'',productFilterQuery:'',productFilters:{}};
const breachRows=[['範例商業銀行','憑證資料外洩','高','12,480','2026/09/11'],['範例雲端服務','第三方資料集曝光','重大','38,920','2026/09/07'],['範例電信公司','帳號密碼外洩','中','2,150','2026/08/28'],['範例資訊服務','原始碼憑證曝光','高','460','2026/08/19']];
const providersData=[['Google Corporation','580','科技','重大','49','98%','美國'],['Microsoft Group of Companies','510','科技','重大','48','96%','美國'],['World Wide Web Consortium, Inc.','720','非營利組織／NGO','重大','50','100%','美國']];
const productsData=[['Taiwan Server Location',['Hosting'],'BuiltWith Pty Ltd',['IT'],'高','45','90%'],['X-Frame-Options',['Business Solutions','Operating Systems and Languages'],'—',['Enterprise','IT'],'高','49','98%'],['Content Type Options',['Hosting','Operating Systems and Languages'],'Web Hypertext Application Technology Working Group',['IT'],'高','48','96%']];
function ecoTools(label,count){return `<div class="eco-tools"><button class="outline active">${label}</button><input id="ecoSearch" value="${e(ecoState.query)}" placeholder="搜尋…"><label><input id="ecoCritical" type="checkbox" ${ecoState.onlyCritical?'checked':''}> 僅顯示重大／高風險</label><span>${count} 筆結果</span><button class="outline" data-toast="已準備示範匯出">下載</button></div>`}
const breachFilterGroups=['嚴重程度','事件類型','評等影響','來源類型','國家／地區','產業','公司','日期','攻擊者','APT','CVE','受影響產品'];
const breachFilterLists={
  '事件類型':['未公開事件類型','網路犯罪','國家支持行動','權限濫用','DNS 發現事項','勒索軟體','阻斷服務','其他揭露','惡意軟體','社交工程','資料外洩','內部威脅','供應鏈攻擊','網路釣魚','帳號接管','資料竊取','系統入侵','弱點利用','詐騙','服務中斷'],
  '國家／地區':['台灣','美國','中國','日本','南韓','新加坡','香港','英國','德國','法國','荷蘭','加拿大','澳洲','印度','泰國','馬來西亞','越南','菲律賓','印尼','巴西'],
  '產業':['航太／國防','銀行','商業服務','消費性商品','信用合作社','教育','能源／資源','工程','金融','政府／政治','醫療／健康','保險','製造業','媒體／娛樂','零售','科技','電信','運輸','旅遊','公用事業'],
  '公司':['範例高速鐵路公司','範例半導體集團','範例商業銀行','範例金融控股','範例資訊服務','範例電信公司','範例保險公司','範例雲端服務','範例鐵路公司','Saperix, Inc.','First Commercial Bank','Taiwan Financial Holding','SYSTEX Corporation','Nan Shan General Insurance','Chunghwa Telecom','Fubon Financial','Cathay Financial','Mega Financial','Taiwan Business Bank','TSMC'],
  '攻擊者':['LockBit','BlackCat','Clop','Conti','REvil','Lazarus Group','Mustang Panda','Volt Typhoon','Kimsuky','Sandworm','Charming Kitten','OilRig','BlackTech','Wizard Spider','Scattered Spider','TeamTNT','Sofacy','Ember Bear','Winnti Group','MuddyWater'],
  'APT':['APT1','APT28','APT29','APT32','APT33','APT34','APT35','APT38','APT40','APT41','Lazarus Group','Mustang Panda','Volt Typhoon','Kimsuky','Sandworm','Charming Kitten','OilRig','BlackTech','Sofacy','MuddyWater'],
  'CVE':['CVE-2023-44487','CVE-2025-23419','CVE-2017-13099','CVE-2021-44228','CVE-2023-23397','CVE-2024-3400','CVE-2024-21887','CVE-2024-3094','CVE-2022-30190','CVE-2021-26855','CVE-2020-1472','CVE-2019-0708','CVE-2017-0144','CVE-2014-3566','CVE-2023-46805','CVE-2024-21762','CVE-2023-27997','CVE-2022-26134','CVE-2021-21972','CVE-2020-0601'],
  '受影響產品':['F5 BIG-IP','Microsoft Exchange','Windows Server','Apache Log4j','Fortinet FortiOS','Palo Alto PAN-OS','VMware ESXi','Cisco IOS','Citrix NetScaler','Ivanti Connect Secure','MOVEit Transfer','Atlassian Confluence','SolarWinds Orion','OpenSSL','Apache HTTP Server','Nginx','WordPress','Microsoft SQL Server','Oracle Database','Google Chrome']
};
function breachFilterOption(group,value){const selected=(ecoState.breachFilters[group]||[]).includes(value);return `<label><input type="checkbox" data-breach-filter-option="${e(group)}" value="${e(value)}" ${selected?'checked':''}> <span>${e(value)}</span></label>`}
function breachFilterBody(name){
  if(name==='嚴重程度')return ['高','中','低'].map(x=>breachFilterOption(name,x)).join('');
  if(name==='評等影響')return ['影響評等','不影響評等'].map(x=>breachFilterOption(name,x)).join('');
  if(name==='來源類型')return ['公開揭露','威脅情報','網路新聞'].map(x=>breachFilterOption(name,x)).join('');
  if(name==='日期')return `<div class="breach-filter-dates"><label>開始日期<input type="date"></label><label>結束日期<input type="date"></label></div>`;
  const items=(breachFilterLists[name]||[]).slice(0,20);return `<input class="breach-option-search" placeholder="搜尋選項…">${items.map(x=>breachFilterOption(name,x)).join('')}`;
}
function breachView(){const groups=breachFilterGroups.map(name=>{const open=ecoState.breachFilterOpen===name,count=(ecoState.breachFilters[name]||[]).length;return `<div class="breach-filter-group"><button class="finding-filter-row" data-breach-filter-group="${e(name)}" aria-expanded="${open}">${name}${count?`<em>${count} ×</em>`:''}<span>${open?'⌃':'⌄'}</span></button>${open?`<div class="breach-filter-options">${breachFilterBody(name)}</div>`:''}</div>`}).join('');return `${pagebar('資料外洩情報',`<button class="outline" data-toast="已準備 CSV">↓　下載 CSV</button>`)}<div class="breach-layout"><aside class="fi-filter"><div class="filter-top"><button class="active">▽ 篩選</button><span>‹</span></div><input placeholder="搜尋篩選條件…"><div class="active-filter-head"><b>使用中的篩選</b><button data-breach-clear>清除全部</button></div><div class="breach-filter-scroll filter-scroll">${groups}</div></aside><main class="breach-results"><div class="breach-tabs"><button class="active"><b>13</b> 全部事件<small>目前投資組合選取範圍</small></button><button><b>11</b> <span>⚑ 公開揭露</span><small>來自可信的公開資訊</small></button><button><b>2</b> <span class="red-label">⚑ 威脅情報*</span><small><b>潛在事件：</b>來自深網、暗網與開放網路監控</small></button></div><div class="breach-feed"><article class="breach-event"><div><span class="dark-label">⚑ 公開揭露</span><h2>範例高速鐵路公司受到資料外洩影響</h2><p><b>受影響供應商</b>　<span class="linkish">範例高速鐵路公司</span></p><p>該公司發生資安事件，影響部分系統的可用性。</p></div><aside><button data-breach-row>查看詳情</button><p>▣ <b>日期</b><br>2026 年 5 月 6 日</p><p>⚑ <b>事件類型</b><br>未公開事件類型</p><p>△ <b>嚴重程度</b><br><i>● 中</i></p><p>✓ <b>已驗證</b><br>影響評等</p></aside></article><article class="breach-event"><div><span class="red-label">⚑ 威脅情報*</span> <span class="blue-label">網路新聞</span><h2>潛在事件：學生因入侵高速鐵路系統遭逮捕</h2><p><b>受影響供應商</b>　<span class="linkish">範例高速鐵路公司</span></p></div><aside><button data-breach-row>查看詳情</button><p>▣ <b>日期</b><br>2026 年 5 月 5 日</p><p>⚑ <b>事件類型</b><br>網路犯罪</p></aside></article></div></main></div>`}
function alertFeed(){return `<div class="alert-feed"><button data-nav="providers"><span class="severity severity-重大">重大</span><b>身分驗證服務評等下降 35 分</b><small>影響 4 家公司 · 2 天前</small></button><button data-nav="products"><span class="severity severity-高">高</span><b>雲端運算平台出現新的重大弱點</b><small>影響 6 家公司 · 5 天前</small></button></div>`}
function fourthOverview(){const tile=(n,c)=>`<button class="fp-tile ${c}" data-nav="providers"><span>${n}</span></button>`;const red=['Google Corporation','The Apache Software Foundation','Microsoft Group of Companies','Cisco Systems','Meta Corporation'];const amber=['World Wide Web Consortium, Inc.','OpenJS Foundation Corporation','Web Hypertext Application Technology Working Group','Bootstrap','Content Security Policy','F5 Group','Domain-based Message Authentication','BuiltWith Pty Ltd','Oracle Corporation Group of Companies','Wikimedia Foundation, Inc.','web.dev','Apple Corporation','W3Schools','Taiwan Chinese Medical Association','Fonticons, Inc.','Cloudflare, Inc.','Swiper','Internet Corporation for Assigned Names and Numbers','PHP Group'];const green=['Microsoft','Chunghwa Telecom Group','TAIWAN-CA Inc.','Vue.js','Amazon Web Services, Inc.','Modernizr'];return `${pagebar('第四方風險總覽',`<button class="outline" data-toast="已開啟儀表板編輯模式">編輯儀表板</button>`)}<div class="content fp-page"><section class="panel fp-dashboard"><header><h2>評等與集中度</h2><label class="fp-switch"><input id="fpTop" type="checkbox" checked><i></i><span>顯示相依度超過 50% 的前 30 項</span></label></header><div class="fp-treemap"><div class="fp-band fp-red"><b>評等 250–630 的第四方</b><div>${red.map(x=>tile(x,'red')).join('')}</div></div><div class="fp-band fp-amber"><b>評等 640–730 的第四方</b><div>${amber.map(x=>tile(x,'amber')).join('')}</div></div><div class="fp-band fp-green"><b>評等 740–900 的第四方</b><div>${green.map(x=>tile(x,'green')).join('')}</div></div></div></section><div class="fp-stats"><section class="panel"><h3>第四方評等中位數</h3><strong class="amber-text">700</strong><span><i class="amber-dot"></i>中等</span><p>目前投資組合內所有第四方服務提供者的安全評等中位數</p></section><section class="panel"><h3>服務提供者</h3><strong>28</strong><span>相依度超過 50%</span><p>出現在受監控公司技術供應鏈中的服務提供者</p><button data-nav="providers">查看服務提供者 →</button></section><section class="panel"><h3>產品集中度</h3><strong>97</strong><span>相依度超過 50%</span><p>由第四方服務提供者供應，且具有高度集中風險的產品</p><button data-nav="products">查看產品 →</button></section></div></div>`}
const providerFilterGroups=[
  ['重要性',['重大','高','中','低'],'list'],
  ['產業',['科技','商業服務','電信','非營利組織／NGO','金融','媒體／娛樂','教育','製造業','醫療／健康','運輸','零售','消費性商品','法律服務','不動產','待確認','政府／政治','旅遊／餐旅','保險'],'list'],
  ['國家／地區',['美國','英國','法國','中國','日本','德國','香港','加拿大','以色列','台灣','澳洲','荷蘭','印度','丹麥','越南','波蘭','比利時','芬蘭','拉脫維亞','泰國'],'list'],
  ['安全評等',[],'rating'],
  ['依賴比例',[],'percent']
];
function providerFilterOption(group,value){const selected=(ecoState.providerFilters[group]||[]).includes(value);return `<label><input type="checkbox" data-provider-filter-option="${e(group)}" value="${e(value)}" ${selected?'checked':''}> <span>${e(value)}</span></label>`}
function providerFilterBody(name,options,type){
  if(type==='rating'||type==='percent'){const min=type==='rating'?250:0,max=type==='rating'?900:100;return `<div class="provider-range"><div><b>${min}</b><b>${max}</b></div><input type="range" min="${min}" max="${max}" value="${min}"><input type="range" min="${min}" max="${max}" value="${max}"></div>`}
  return `${name==='國家／地區'?'<input class="provider-option-search" placeholder="搜尋選項…">':''}${options.slice(0,20).map(value=>providerFilterOption(name,value)).join('')}`;
}
function providerView(){
  const active=Object.values(ecoState.providerFilters).flat().length;
  const rows=providersData.filter(row=>(!ecoState.query||row.join(' ').toLowerCase().includes(ecoState.query.toLowerCase()))&&(!ecoState.providerFilters['重要性']?.length||ecoState.providerFilters['重要性'].includes(row[3]))&&(!ecoState.providerFilters['產業']?.length||ecoState.providerFilters['產業'].includes(row[2]))&&(!ecoState.providerFilters['國家／地區']?.length||ecoState.providerFilters['國家／地區'].includes(row[6])));
  const groups=providerFilterGroups.filter(([name])=>!ecoState.providerFilterQuery||name.includes(ecoState.providerFilterQuery)).map(([name,options,type])=>{const open=ecoState.providerFilterOpen===name,count=(ecoState.providerFilters[name]||[]).length;return `<div class="provider-filter-group"><button data-provider-filter-group="${e(name)}">${e(name)}${count?`<em>${count}</em>`:''}<span>${open?'⌃':'⌄'}</span></button>${open?`<div class="provider-filter-options">${providerFilterBody(name,options,type)}</div>`:''}</div>`}).join('');
  return `${pagebar('第三方使用的服務提供者')}<div class="service-provider-layout"><aside class="filters service-provider-filters"><div class="filter-top"><button class="active">▽ 篩選</button><button data-modal="views">♧</button><span>‹</span></div><input id="providerFilterSearch" class="service-provider-filter-search" value="${e(ecoState.providerFilterQuery)}" placeholder="搜尋篩選條件…">${active?`<div class="vuln-active-head"><b>使用中的篩選</b><button data-provider-clear>清除全部</button></div>`:''}<div class="filter-scroll">${groups}</div><button class="filter-bottom" data-modal="create-view">建立檢視</button></aside><main class="panel service-provider-table"><div class="table-tools"><b>${rows.length} 筆資料</b><span class="spacer"></span><button data-toggle="provider-search">⌕</button><button data-toast="已準備服務提供者 CSV">↓</button><button data-toggle="fullscreen">⛶</button></div><div id="providerSearchBox" class="provider-search-box" style="display:none"><input id="ecoSearch" value="${e(ecoState.query)}" placeholder="搜尋服務提供者…"></div><div class="table-scroll"><table class="data-table"><thead><tr><th>服務提供者</th><th>趨勢</th><th>評等</th><th>產業</th><th>重要性 ↓</th><th>相依公司</th></tr></thead><tbody>${rows.map((row,i)=>`<tr data-provider="${providersData.indexOf(row)}"><td class="provider-name"><span class="provider-logo">${row[0].charAt(0)}</span><span><b>${e(row[0])}</b><button data-provider-subscribe="${i}">訂閱</button></span></td><td><span class="provider-trend">⌁⌁⌁⌁</span></td><td><b class="provider-score">≡ ${row[1]}</b></td><td>${e(row[2])}</td><td><span class="importance importance-${row[3]}">${e(row[3])}</span></td><td><button class="dependent-count" data-toast="${row[4]} 家相依公司">${row[4]}</button>（${row[5]}）</td></tr>`).join('')}</tbody></table>${rows.length?'':'<div class="empty">沒有符合條件的服務提供者</div>'}</div><div class="pager">顯示 1 – ${rows.length}，共 ${rows.length} 筆<span class="spacer"></span><button disabled>‹</button><span>1 / 1</span><button disabled>›</button></div></main></div>`;
}
const productFilterGroups=[
  ['重要性',['重大','高','中','低'],'list'],
  ['產品類型',['CMS（內容管理系統）','Help Desk','Relationship Management','Business Solutions','Productivity Solutions','Commerce','Enterprise Resource Planning','Payment Processor','SCM（供應鏈管理）','HR Management','Operating Systems and Languages','Hosting','IT Management','Security Services','CDN（內容傳遞網路）','Hardware','Server Technologies','Web Application','DNS（網域名稱系統）','Ad Network'],'list'],
  ['業務功能',['IT','其他','行銷','內容管理系統','企業營運','財務','客戶關係管理','人力資源'],'list'],
  ['依賴比例',[],'percent']
];
function productFilterOption(group,value){const selected=(ecoState.productFilters[group]||[]).includes(value);return `<label><input type="checkbox" data-product-filter-option="${e(group)}" value="${e(value)}" ${selected?'checked':''}> <span>${e(value)}</span></label>`}
function productFilterBody(name,options,type){if(type==='percent')return `<div class="provider-range"><div><b>0</b><b>100</b></div><input type="range" min="0" max="100" value="0"><input type="range" min="0" max="100" value="100"></div>`;return options.slice(0,20).map(value=>productFilterOption(name,value)).join('')}
function productsView(){
  const active=Object.values(ecoState.productFilters).flat().length;
  const rows=productsData.filter(row=>(!ecoState.query||row.flat().join(' ').toLowerCase().includes(ecoState.query.toLowerCase()))&&(!ecoState.productFilters['重要性']?.length||ecoState.productFilters['重要性'].includes(row[4]))&&(!ecoState.productFilters['產品類型']?.length||row[1].some(value=>ecoState.productFilters['產品類型'].includes(value)))&&(!ecoState.productFilters['業務功能']?.length||row[3].some(value=>ecoState.productFilters['業務功能'].includes(value))));
  const groups=productFilterGroups.filter(([name])=>!ecoState.productFilterQuery||name.includes(ecoState.productFilterQuery)).map(([name,options,type])=>{const open=ecoState.productFilterOpen===name,count=(ecoState.productFilters[name]||[]).length;return `<div class="provider-filter-group"><button data-product-filter-group="${e(name)}">${e(name)}${count?`<em>${count}</em>`:''}<span>${open?'⌃':'⌄'}</span></button>${open?`<div class="provider-filter-options">${productFilterBody(name,options,type)}</div>`:''}</div>`}).join('');
  const cellList=values=>values.map(value=>`<span class="product-pill">${e(value)}</span>`).join('');
  return `${pagebar('第三方使用的產品')}<div class="service-provider-layout"><aside class="filters service-provider-filters"><div class="filter-top"><button class="active">▽ 篩選</button><button data-modal="views">♧</button><span>‹</span></div><input id="productFilterSearch" class="service-provider-filter-search" value="${e(ecoState.productFilterQuery)}" placeholder="搜尋篩選條件…">${active?`<div class="vuln-active-head"><b>使用中的篩選</b><button data-product-clear>清除全部</button></div>`:''}<div class="filter-scroll">${groups}</div><button class="filter-bottom" data-modal="create-view">建立檢視</button></aside><main class="panel service-provider-table"><div class="table-tools"><b>${rows.length} 筆資料</b><span class="spacer"></span><button data-toggle="product-search">⌕</button><button data-toast="已準備產品 CSV">↓</button><button data-toggle="fullscreen">⛶</button></div><div id="productSearchBox" class="provider-search-box" style="display:none"><input id="ecoSearch" value="${e(ecoState.query)}" placeholder="搜尋產品…"></div><div class="table-scroll"><table class="data-table product-data-table"><thead><tr><th>產品</th><th>產品類型</th><th>服務提供者</th><th>業務功能</th><th>重要性 ↓</th><th>相依公司</th></tr></thead><tbody>${rows.map(row=>`<tr data-product-row><td class="name"><b>${e(row[0])}</b></td><td>${cellList(row[1])}</td><td>${e(row[2])}</td><td>${cellList(row[3])}</td><td><span class="importance importance-${row[4]}">${e(row[4])}</span></td><td><button class="dependent-count" data-toast="${row[5]} 家相依公司">${row[5]}</button>（${row[6]}）</td></tr>`).join('')}</tbody></table>${rows.length?'':'<div class="empty">沒有符合條件的產品</div>'}</div><div class="pager">顯示 1 – ${rows.length}，共 ${rows.length} 筆<span class="spacer"></span><button disabled>‹</button><span>1 / 1</span><button disabled>›</button></div></main></div>`;
}
function fourthAlerts(){return `${pagebar('第四方警示',`<button class="outline" data-toast="已開啟第四方警示設定">警示設定</button>`)}<div class="content">${ecoTools('全部警示',2)}<section class="panel eco-card">${alertFeed()}</section></div>`}
function ecosystemView(page){return page==='breach'?breachView():page==='fourth-overview'?fourthOverview():page==='providers'?providerView():page==='products'?productsView():fourthAlerts()}
document.addEventListener('click',event=>{const group=event.target.closest('[data-breach-filter-group]');if(group){ecoState.breachFilterOpen=ecoState.breachFilterOpen===group.dataset.breachFilterGroup?'':group.dataset.breachFilterGroup;render();return}if(event.target.closest('[data-breach-clear]')){ecoState.breachFilters={};render()}});
document.addEventListener('change',event=>{if(!event.target.matches('[data-breach-filter-option]'))return;const name=event.target.dataset.breachFilterOption;const current=new Set(ecoState.breachFilters[name]||[]);event.target.checked?current.add(event.target.value):current.delete(event.target.value);ecoState.breachFilters[name]=[...current];render()});
document.addEventListener('click',event=>{const productGroup=event.target.closest('[data-product-filter-group]');if(productGroup){ecoState.productFilterOpen=ecoState.productFilterOpen===productGroup.dataset.productFilterGroup?'':productGroup.dataset.productFilterGroup;render();return}if(event.target.closest('[data-product-clear]')){ecoState.productFilters={};render();return}if(event.target.closest('[data-toggle="product-search"]')){const box=document.getElementById('productSearchBox');if(box)box.style.display=box.style.display==='none'?'block':'none';return}const group=event.target.closest('[data-provider-filter-group]');if(group){ecoState.providerFilterOpen=ecoState.providerFilterOpen===group.dataset.providerFilterGroup?'':group.dataset.providerFilterGroup;render();return}if(event.target.closest('[data-provider-clear]')){ecoState.providerFilters={};render();return}if(event.target.closest('[data-toggle="provider-search"]')){const box=document.getElementById('providerSearchBox');if(box)box.style.display=box.style.display==='none'?'block':'none';return}const subscribe=event.target.closest('[data-provider-subscribe]');if(subscribe){showToast('已訂閱示範服務提供者');return}const x=event.target.closest('[data-provider],[data-breach-row],[data-product-row]');if(!x)return;if(x.dataset.provider!==undefined){ecoState.provider=+x.dataset.provider;showToast('已開啟服務提供者摘要')}else showToast(x.hasAttribute('data-breach-row')?'已開啟外洩事件詳情':'已開啟產品關聯詳情')});
document.addEventListener('input',event=>{if(event.target.id==='ecoSearch'){ecoState.query=event.target.value;const p=event.target.selectionStart;render();const i=document.getElementById('ecoSearch');(i.closest('#providerSearchBox')||i.closest('#productSearchBox'))?.style.setProperty('display','block');i.focus();i.setSelectionRange(p,p)}if(event.target.id==='providerFilterSearch'){ecoState.providerFilterQuery=event.target.value;const p=event.target.selectionStart;render();const i=document.getElementById('providerFilterSearch');i.focus();i.setSelectionRange(p,p)}if(event.target.id==='productFilterSearch'){ecoState.productFilterQuery=event.target.value;const p=event.target.selectionStart;render();const i=document.getElementById('productFilterSearch');i.focus();i.setSelectionRange(p,p)}});
document.addEventListener('change',event=>{if(!event.target.matches('[data-provider-filter-option]'))return;const name=event.target.dataset.providerFilterOption;const values=new Set(ecoState.providerFilters[name]||[]);event.target.checked?values.add(event.target.value):values.delete(event.target.value);ecoState.providerFilters[name]=[...values];render()});
document.addEventListener('change',event=>{if(!event.target.matches('[data-product-filter-option]'))return;const name=event.target.dataset.productFilterOption;const values=new Set(ecoState.productFilters[name]||[]);event.target.checked?values.add(event.target.value):values.delete(event.target.value);ecoState.productFilters[name]=[...values];render()});
document.addEventListener('change',event=>{if(event.target.id==='ecoCritical'){ecoState.onlyCritical=event.target.checked;render()}});
