const tourState={open:false,step:0};
const tourSteps=[
 {title:'歡迎使用持續監控中文操作範例',text:'這是一套使用虛構公司與評分資料製作的教學環境。你可以放心操作，不會連接或改動正式 BitSight 帳號。',target:'整套系統'},
 {title:'從投資組合掌握整體風險',text:'使用左側「投資組合風險」查看公司清單、框架評估、關鍵資產、公司比較與供應商探索。',target:'投資組合風險'},
 {title:'深入查看單一供應商',text:'「供應商風險」包含安全評等趨勢、風險面向、發現事項、威脅洞察、改善追蹤與基礎設施。',target:'供應商風險'},
 {title:'追蹤外洩、弱點與第四方',text:'資料外洩情報、弱點偵測及第四方風險頁面，可協助說明事件如何影響公司與供應鏈。',target:'風險情報'},
 {title:'建立日常工作流程',text:'警示、報表、協作、資料夾、層級與整合頁面，可示範監控後的通知、分工及治理流程。',target:'管理與協作'},
 {title:'開始自由操作',text:'點選表格列、篩選條件與卡片即可查看互動。需要回到初始狀態時，可使用「重設示範」。',target:'完成'}
];
function tourMarkup(){if(!tourState.open)return '';const s=tourSteps[tourState.step];return `<div class="tour-back"><section class="tour-dialog" role="dialog" aria-label="操作導覽"><div class="tour-progress">${tourSteps.map((_,i)=>`<i class="${i<=tourState.step?'active':''}"></i>`).join('')}</div><small>操作導覽 ${tourState.step+1} / ${tourSteps.length} · ${s.target}</small><h2>${s.title}</h2><p>${s.text}</p><div class="tour-actions"><button data-tour-close>關閉</button><button data-demo-reset>重設示範</button><span></span>${tourState.step?'<button data-tour-prev>上一步</button>':''}<button class="save" data-tour-next>${tourState.step===tourSteps.length-1?'開始操作':'下一步'}</button></div></section></div>`}
function paintTour(){document.getElementById('tourLayer')?.remove();const layer=document.createElement('div');layer.id='tourLayer';layer.innerHTML=tourMarkup();document.body.appendChild(layer)}
function resetDemo(){state.filterOpen='';state.filterValues={};state.query='';state.selected=null;state.discoveryQuery='';state.showSubscribed=false;state.subscribed=[1];state.alertCategory='';state.alertSeverity='';state.alertQuery='';state.vulnQuery='';state.modal=null;state.toast='';state.hideBanner=false;state.period='30 天';state.update=0;state.view='全部公司';vendorState.company=1;vendorState.findingQuery='';vendorState.severity='全部';vendorState.findingStrict=true;ecoState.query='';ecoState.provider=0;ecoState.onlyCritical=false;adminState.query='';adminState.folder=0;portfolioState.assessmentStatus='已完成';portfolioState.assessmentFilter='';portfolioState.assets=[];portfolioState.compareSelected=[1,3];go('dashboard');showToast('示範資料已重設')}
document.addEventListener('click',event=>{const x=event.target.closest('[data-tour],[data-tour-close],[data-tour-prev],[data-tour-next],[data-demo-reset]');if(!x)return;if(x.hasAttribute('data-tour')){tourState.open=true;tourState.step=0;paintTour()}else if(x.hasAttribute('data-tour-close')){tourState.open=false;paintTour()}else if(x.hasAttribute('data-tour-prev')){tourState.step=Math.max(0,tourState.step-1);paintTour()}else if(x.hasAttribute('data-tour-next')){if(tourState.step===tourSteps.length-1){tourState.open=false;paintTour()}else{tourState.step++;paintTour()}}else if(x.hasAttribute('data-demo-reset')){tourState.open=false;paintTour();resetDemo()}});
function globalResults(query){document.getElementById('globalResults')?.remove();if(!query.trim())return;const q=query.trim().toLowerCase();const pages=Object.entries(names).filter(([id,label])=>label.toLowerCase().includes(q)||id.includes(q)).slice(0,5).map(([id,label])=>({id,label,kind:'功能頁面'}));const cos=companies.map((c,i)=>({id:'vendor-overview',label:c[0],kind:'公司',company:i})).filter(x=>x.label.includes(query)).slice(0,5);const items=[...pages,...cos];const box=document.createElement('div');box.id='globalResults';box.className='global-results';box.innerHTML=items.length?items.map(x=>`<button data-global-result="${x.id}" ${x.company!==undefined?`data-global-company="${x.company}"`:''}><b>${e(x.label)}</b><small>${x.kind}</small></button>`).join(''):'<p>找不到符合的公司或功能</p>';document.querySelector('.top')?.appendChild(box)}
document.addEventListener('input',event=>{if(event.target.hasAttribute('data-global-search'))globalResults(event.target.value)});
document.addEventListener('click',event=>{const x=event.target.closest('[data-global-result]');if(x){if(x.dataset.globalCompany!==undefined)vendorState.company=+x.dataset.globalCompany;document.getElementById('globalResults')?.remove();go(x.dataset.globalResult)}});
