const portfolioState={assessmentStatus:'已完成',assessmentFilter:'',assetFilters:{},assetFilterOpen:'',assetUploadOpen:false,assets:[],compareEditing:false,compareSelected:[1,3],compareHidden:[],compareVectors:[]};
const demoAssessments=[
  ['供應商年度評估','範例商業銀行','NIST CSF','進行中','—','示範使用者','持續監控'],
  ['資訊安全問卷','範例資訊服務','ISO 27001','草稿','—','示範使用者','持續監控']
];

function portfolioView(page){
  if(page==='fi-assessments')return assessmentsPortfolioView();
  if(page==='critical-assets')return criticalAssetsView();
  if(page==='compare')return comparePortfolioView();
  return `${pagebar('到期訂閱')}<div class="expired-space" aria-label="目前未顯示到期訂閱內容"></div><div class="footer">獨立繁體中文操作範例 · 此頁依目前帳號可見的空白狀態重建</div>`;
}
function portfolioFilters(list){return list.map(([label,opts])=>`<div class="filter-row"><button data-portfolio-filter="${e(label)}">${e(label)}<span>⌄</span></button>${portfolioState.assetFilterOpen===label?`<div class="filter-options">${opts.map(o=>`<label><input type="checkbox" data-asset-filter-value="${e(label)}" value="${e(o)}" ${portfolioState.assetFilters[label]?.includes(o)?'checked':''}> ${e(o)}</label>`).join('')}</div>`:''}</div>`).join('');}
function assessmentsPortfolioView(){
  const status=portfolioState.assessmentStatus;
  const rows=status==='已完成'?[]:demoAssessments.filter(r=>status==='全部'||r[3]===status).filter(r=>!portfolioState.assessmentFilter||r.join(' ').includes(portfolioState.assessmentFilter));
  const filterList=[['公司',['範例商業銀行','範例資訊服務']],['狀態',['已完成','進行中','草稿']],['使用者',['示範使用者']],['日期',['最近 30 天','最近 90 天']],['框架',['NIST CSF','ISO 27001']]];
  return `${pagebar('框架情報評估')}<div class="content portfolio-content"><div class="companies-layout"><div class="filters"><div class="filter-top"><button class="active">▽ 篩選</button><button data-modal="columns">▥</button><button data-modal="views">♧</button></div><input class="filter-search" placeholder="搜尋篩選條件…"><div class="filter-scroll"><div class="filter-row"><button>已套用篩選 <span data-assessment-clear style="color:#3273a5">清除全部</span></button><div class="filter-options"><span class="applied-chip">${e(status)}</span></div></div>${portfolioFilters(filterList)}</div><div class="portfolio-filter-foot"><button class="filter-bottom" data-modal="create-view">建立檢視</button><button class="outline" data-toast="示範設定已儲存">儲存變更</button></div></div><div class="panel table-panel"><div class="portfolio-table-heading"><select id="assessmentStatus"><option ${status==='已完成'?'selected':''}>已完成</option><option ${status==='全部'?'selected':''}>全部</option><option ${status==='進行中'?'selected':''}>進行中</option><option ${status==='草稿'?'selected':''}>草稿</option></select></div><div class="table-tools"><span>${rows.length} 筆</span><span class="spacer"></span><input id="assessmentSearch" value="${e(portfolioState.assessmentFilter)}" placeholder="搜尋評估" class="portfolio-search"><button data-toggle="fullscreen">⛶</button></div><div class="table-scroll"><table class="data-table"><thead><tr><th>評估名稱</th><th>公司</th><th>框架</th><th>狀態</th><th>完成日期 ↓</th><th>使用者</th><th>訂閱類型</th></tr></thead><tbody>${rows.map(r=>`<tr data-assessment-row><td class="name">${e(r[0])}</td>${r.slice(1).map(x=>`<td>${e(x)}</td>`).join('')}</tr>`).join('')}</tbody></table>${rows.length?'':'<div class="portfolio-empty"><span>⌕</span><p>找不到結果</p></div>'}</div><div class="pager"><button>30⌄</button><span>0 – ${rows.length}，共 ${rows.length} 筆</span><span class="spacer"></span><button>‹</button><span>${rows.length?'1 / 1':'0 / 0'}</span><button>›</button></div></div></div></div>`;
}

function criticalAssetsView(){
  const filters=[['資產類型',['網域','IP 位址']],['發現事項數量',['0','1–10','10 以上']],['重要性',['高','中','低']],['寬限期',['有','無']],['寬限期結束日期',['最近 30 天']],['訪客網路排除',['是','否']],['訪客網路排除結束日期',['最近 30 天']],['雲端平台',['AWS','Azure']],['雲端服務',['運算','儲存']]];
  const rows=portfolioState.assets;
  return `${pagebar('關鍵資產',`<button class="outline" data-assets-upload>↥　上傳資產</button>`)}<div class="content portfolio-content"><div class="companies-layout"><div class="filters"><div class="filter-top"><button class="active">▽ 篩選</button><button data-modal="views">♧</button></div><input class="filter-search" placeholder="搜尋篩選條件…"><div class="filter-scroll">${portfolioFilters(filters)}</div><button class="filter-bottom" data-modal="create-view">建立檢視</button></div><div class="panel table-panel"><div class="table-tools"><span>${rows.length} 筆</span><button class="portfolio-unmonitor" data-assets-unmonitor>停止監控（${rows.length}）</button><span class="spacer"></span><button data-toast="可搜尋示範資產">⌕</button><button data-toast="已準備示範匯出">↓</button><button data-toggle="fullscreen">⛶</button></div><div class="table-scroll"><table class="data-table"><thead><tr><th><input type="checkbox" data-select-all></th><th>資產</th><th>資產類型</th><th>公司</th><th>重要性　↓</th><th>訪客網路排除</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td><input type="checkbox" class="row-check" data-asset-check="${i}"></td><td class="name">${e(r[0])}</td><td>${e(r[1])}</td><td>${e(r[2])}</td><td>${e(r[3])}</td><td>否</td></tr>`).join('')}</tbody></table>${rows.length?'':'<div class="asset-empty"><div class="asset-illustration">▤<span>⌕</span></div><p>要開始使用，請從供應商的基礎設施頁面選取資產，<br>或使用「上傳資產」按鈕匯入 CSV。</p><button class="portfolio-blue" data-toast="可從基礎設施頁面選取資產，或載入下方示範資料">了解更多</button></div>'}</div><div class="pager"><button>30⌄</button><span>0 – ${rows.length}，共 ${rows.length} 筆</span><span class="spacer"></span><button>‹</button><span>${rows.length?'1 / 1':'0 / 0'}</span><button>›</button></div></div></div>${portfolioState.assetUploadOpen?`<div class="portfolio-upload panel"><strong>上傳資產</strong><p>這是本機示範操作。你可以載入虛構範例資產，或選擇自己的 CSV；資料只在此瀏覽器分頁處理。</p><input type="file" id="assetFile" accept=".csv,text/csv"><div><button class="outline" data-assets-cancel>取消</button><button class="portfolio-blue" data-assets-example>載入示範資產</button></div></div>`:''}</div>`;
}

function comparePortfolioView(){
  const selected=portfolioState.compareSelected.map(i=>[...companies[i],i]);
  const visible=selected.filter(x=>!portfolioState.compareHidden.includes(x[5]));
  const sorted=[...selected].sort((a,b)=>+b[1]-+a[1]);
  const colors=['#4e9485','#3d688d','#a45d91','#ce9d49'];
  const graph=visible.map((c,j)=>{const points=Array.from({length:28},(_,i)=>`${35+i*25},${160-(+c[1]-700)*.45+Math.sin(i*.7+j)*5+(i>17?i-17:0)*2}`).join(' ');return `<polyline points="${points}" fill="none" stroke="${colors[j%colors.length]}" stroke-width="2"/>`;}).join('');
  return `${pagebar('公司比較',`<button class="outline" data-compare-edit>${portfolioState.compareEditing?'完成':'編輯'}</button><button class="portfolio-blue" data-compare-download>下載</button>`)}<div class="content compare-content">${portfolioState.compareEditing?`<div class="panel compare-editor"><strong>選擇要比較的公司（最多 4 家）</strong><div>${companies.slice(0,8).map((c,i)=>`<label><input type="checkbox" data-compare-company="${i}" ${portfolioState.compareSelected.includes(i)?'checked':''}> ${e(c[0])}</label>`).join('')}</div></div>`:''}<div class="panel compare-panel"><h2>安全評等</h2><div class="compare-chart-row"><div class="compare-chart"><svg viewBox="0 0 750 280" preserveAspectRatio="none" role="img" aria-label="公司安全評等趨勢示意圖"><line x1="35" y1="40" x2="735" y2="40" stroke="#d7e0e8" stroke-dasharray="3 3"/><line x1="35" y1="95" x2="735" y2="95" stroke="#d7e0e8" stroke-dasharray="3 3"/><line x1="35" y1="150" x2="735" y2="150" stroke="#d7e0e8" stroke-dasharray="3 3"/><line x1="35" y1="205" x2="735" y2="205" stroke="#d7e0e8" stroke-dasharray="3 3"/><text x="2" y="45">800</text><text x="2" y="100">700</text><text x="2" y="155">600</text><text x="2" y="210">500</text>${graph}<text x="35" y="265">2025/09</text><text x="350" y="265">2026/03</text><text x="675" y="265">2026/09</text></svg></div><div class="compare-legend">${selected.map((c,j)=>`<button data-compare-hide="${c[5]}"><span style="color:${colors[j%colors.length]}">${portfolioState.compareHidden.includes(c[5])?'◯':'⬤'}</span> ${e(c[0])}<b>${e(c[1])}</b></button>`).join('')}</div></div></div><div class="panel compare-panel"><h2>排行榜</h2><table class="data-table"><thead><tr><th>排名</th><th>公司</th><th>安全評等</th><th>產業</th><th>子產業</th></tr></thead><tbody>${sorted.map((c,i)=>`<tr><td>${i+1}</td><td class="name" data-compare-detail="${c[5]}">${e(c[0])}</td><td>${e(c[1])}</td><td>金融／科技</td><td>示範產業</td></tr>`).join('')}</tbody></table></div><div class="panel compare-panel"><h2>風險面向</h2><h3>受入侵系統</h3><div class="compare-vectors">${['殭屍網路感染','垃圾郵件傳播','惡意軟體伺服器','非預期通訊','可能遭利用'].map(x=>`<label><input type="checkbox" data-compare-vector="${x}" ${portfolioState.compareVectors.includes(x)?'checked':''}> ${x}</label>`).join('')}</div><h3>資安治理</h3><div class="compare-vectors">${['SPF','DKIM','DMARC','SSL 憑證','開放埠'].map(x=>`<label><input type="checkbox" data-compare-vector="${x}" ${portfolioState.compareVectors.includes(x)?'checked':''}> ${x}</label>`).join('')}</div>${portfolioState.compareVectors.length?`<p>已選風險面向：${portfolioState.compareVectors.join('、')}</p>`:''}</div></div>`;
}

document.addEventListener('click',event=>{
  const x=event.target.closest('[data-assets-upload],[data-assets-cancel],[data-assets-example],[data-assets-unmonitor],[data-compare-edit],[data-compare-hide],[data-compare-download],[data-compare-detail],[data-portfolio-filter],[data-assessment-clear],[data-assessment-row]');
  if(!x)return;
  if(x.hasAttribute('data-assets-upload')){portfolioState.assetUploadOpen=true;render();return;}
  if(x.hasAttribute('data-assets-cancel')){portfolioState.assetUploadOpen=false;render();return;}
  if(x.hasAttribute('data-assets-example')){portfolioState.assets=[['portal.demo.example','網域','範例資訊服務','高'],['198.51.100.10','IP 位址','範例商業銀行','中']];portfolioState.assetUploadOpen=false;showToast('已載入兩筆虛構資產');return;}
  if(x.hasAttribute('data-assets-unmonitor')){if(portfolioState.assets.length)showToast('請先勾選要停止監控的資產');return;}
  if(x.hasAttribute('data-compare-edit')){portfolioState.compareEditing=!portfolioState.compareEditing;render();return;}
  if(x.hasAttribute('data-compare-hide')){const id=+x.dataset.compareHide;portfolioState.compareHidden=portfolioState.compareHidden.includes(id)?portfolioState.compareHidden.filter(n=>n!==id):[...portfolioState.compareHidden,id];render();return;}
  if(x.hasAttribute('data-compare-download')){const csv='公司,安全評等\n'+portfolioState.compareSelected.map(i=>`${companies[i][0]},${companies[i][1]}`).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv'}));a.download='公司比較示範.csv';a.click();URL.revokeObjectURL(a.href);return;}
  if(x.hasAttribute('data-compare-detail')){state.selected=+x.dataset.compareDetail;render();return;}
  if(x.hasAttribute('data-portfolio-filter')){portfolioState.assetFilterOpen=portfolioState.assetFilterOpen===x.dataset.portfolioFilter?'':x.dataset.portfolioFilter;render();return;}
  if(x.hasAttribute('data-assessment-clear')){portfolioState.assessmentStatus='全部';render();return;}
  if(x.hasAttribute('data-assessment-row')){showToast('這是示範評估紀錄');return;}
});
document.addEventListener('change',event=>{
  const x=event.target;
  if(x.id==='assessmentStatus'){portfolioState.assessmentStatus=x.value;render();return;}
  if(x.hasAttribute('data-compare-company')){const id=+x.dataset.compareCompany;if(x.checked&&portfolioState.compareSelected.length>=4){x.checked=false;showToast('最多比較 4 家公司');return;}portfolioState.compareSelected=x.checked?[...portfolioState.compareSelected,id]:portfolioState.compareSelected.filter(n=>n!==id);render();return;}
  if(x.hasAttribute('data-compare-vector')){portfolioState.compareVectors=x.checked?[...portfolioState.compareVectors,x.dataset.compareVector]:portfolioState.compareVectors.filter(n=>n!==x.dataset.compareVector);render();return;}
  if(x.hasAttribute('data-asset-filter-value')){const key=x.dataset.assetFilterValue;const old=portfolioState.assetFilters[key]||[];portfolioState.assetFilters[key]=x.checked?[...old,x.value]:old.filter(v=>v!==x.value);render();return;}
  if(x.id==='assetFile'&&x.files?.length){const file=x.files[0];const reader=new FileReader();reader.onload=()=>{const rows=String(reader.result).split(/\r?\n/).slice(1,21).filter(Boolean).map(line=>{const cols=line.split(',');return [cols[0]||'未命名資產',cols[1]||'網域',cols[2]||'示範公司',cols[3]||'中'];});portfolioState.assets=rows;portfolioState.assetUploadOpen=false;showToast(`已在本機讀取 ${rows.length} 筆資產`);};reader.readAsText(file);}
});
document.addEventListener('input',event=>{
  if(event.target.id==='assessmentSearch'){portfolioState.assessmentFilter=event.target.value;const at=event.target.selectionStart;render();const field=document.getElementById('assessmentSearch');field.focus();field.setSelectionRange(at,at);}
});
