const spmMenu=[
 ['儀表板','spm-dashboard','⌁'],
 ['組織',null,'⌘',[
  ['公司詳細資料','spm-company-details'],['風險面向','spm-risk-vectors'],['評等樹','spm-rating-tree'],['我的公司清單','spm-company-list'],['子公司','spm-subsidiaries'],['評估','spm-assessments'],['資料外洩情報','spm-breach-intelligence'],['Bitsight 徽章','spm-badge']]],
 ['發現事項',null,'▣',[
  ['發現事項表格','spm-findings'],['問題追蹤','spm-remediation'],['弱點偵測','spm-threat-detection']]],
 ['攻擊面',null,'◎',[
  ['基礎設施','spm-assets'],['攻擊面分析','spm-attack-surface'],['居家辦公','spm-work-from-home'],['雲端基礎設施同步','spm-cloud-infrastructure'],['可能的基礎設施','spm-probable-infrastructure'],['第三方資產','spm-third-party-assets']]],
 ['行動計畫',null,'✓',[
  ['風險改善','spm-action-plans'],['評等預測','spm-forecasting'],['子公司改善','spm-subsidiary-improvement'],['控制措施洞察','spm-control-insights']]],
 ['同業比較',null,'♙',[
  ['同業分析','spm-peer'],['風險位置','spm-risk-position']]],
 ['協作','spm-collaboration','✉'],
 ['警示',null,'⚑',[
  ['已設定警示','spm-alert-settings'],['警示記錄','spm-alerts'],['感染事件','spm-infections']]],
 ['報表','spm-reports','▤'],['整合','spm-integrations','♧']
]
const spmNames=Object.fromEntries(spmMenu.flatMap(m=>m[3]?m[3].map(x=>[x[1],x[0]]):[[m[1],m[0]]]));
function isSpm(){return state.page.startsWith('spm-')}
function spmParent(page){return spmMenu.find(m=>m[3]?.some(x=>x[1]===page))?.[0]||''}
function spmNav(){return spmMenu.map(m=>`<div class="menu-group"><button class="menu-main ${state.page===m[1]||m[3]?.some(x=>x[1]===state.page)?'active':''}" data-nav="${m[1]||''}" data-group="${m[0]}"><span class="icon">${m[2]}</span><span>${m[0]}</span>${m[3]?'<span class="chev">'+(state.open===m[0]?'⌄':'›')+'</span>':''}</button>${m[3]&&state.open===m[0]?`<div class="submenu">${m[3].map(([label,id])=>`<button class="${state.page===id?'active':''}" data-nav="${id}">${label}</button>`).join('')}</div>`:''}</div>`).join('')}
function productSwitcher(){return `<div class="product-switch-wrap"><button class="app-switch" data-product-menu><span class="dots">⠿</span><span>${isSpm()?'安全態勢管理':'持續監控'}</span><span class="switch-caret">⌄</span></button>${state.productMenu?`<div class="product-menu"><button data-product="cm"><b>持續監控</b><small>第三方風險管理</small></button><button data-product="spm"><b>安全態勢管理</b><small>組織資安曝險與改善</small></button></div>`:''}</div>`}
const spmCards=()=>`<div class="spm-grid">
 <section class="spm-card rating-card"><header>Bitsight 安全評等 <select><option>90 天</option><option>30 天</option></select></header><div class="rating-main"><div><small>Saperix, Inc.</small><strong>420</strong><span class="delta">▼ 20</span><em>基礎</em></div><div class="rating-gauge"><i style="--score:20%"></i></div></div><button data-nav="spm-company-details">前往主要評等</button><a data-nav="spm-company-details">★ Saperix Lab</a><a data-nav="spm-rating-tree">檢視評等樹</a></section>
 <section class="spm-card"><header>供應商探索 <button>⋮</button></header><div class="donut"><b>246</b><span>未監控公司</span></div><ul class="legend"><li><i class="basic"></i>基礎評等 <b>29</b></li><li><i class="mid"></i>中階評等 <b>146</b></li><li><i class="advanced"></i>進階評等 <b>71</b></li></ul><footer>←　1 / 7　→</footer></section>
 <section class="spm-card"><header>我的評等變化 <select><option>30 天</option></select></header><div class="change-row"><b>Awesome Inc</b><span class="down">−10</span><strong>640</strong></div><div class="change-row"><b>Saperix, Inc.</b><span class="up">+10</span><strong>420</strong></div><button data-nav="spm-organization">所有 SPM 公司評等變化</button></section>
 <section class="spm-card"><header>新的高優先發現事項 <select><option>30 天</option></select></header><div class="finding-total"><span>所有 SPM 公司</span><strong>155</strong></div><div class="mini-bars">${[10,25,18,42,34,63,51,72,45,80,57,92].map(h=>`<i style="height:${h}%"></i>`).join('')}</div><h4>最多新發現事項</h4><p>Saperix, Inc. <b>152</b></p><p>Saperix Corporate <b>3</b></p></section>
 <section class="spm-card"><header>帳戶建議</header><p>已完成：4 / 5</p><div class="steps"><i></i><i></i><i></i><i></i><i class="open"></i></div><h3>自訂儀表板</h3><p>調整儀表板，突顯與工作流程最相關的資料。</p><button data-modal="edit-dashboard">開始使用</button></section>
 <section class="spm-card"><header>警示</header>${[['測試','Awesome Inc.'],['Bitsight 新發現事項警示','Saperix Corporate'],['測試','Saperix Corporate'],['Bitsight SSL 警示','Saperix, Inc.']].map(x=>`<div class="alert-line"><b>${x[0]}</b><small>2026/09/19 · ${x[1]}</small></div>`).join('')}<button data-nav="spm-alerts">檢視警示</button></section>
 <section class="spm-card"><header>基礎設施變更 <select><option>90 天</option></select></header><div class="finding-total"><span>所有 SPM 公司</span><strong>43</strong></div><h4>變更最多的公司</h4><p>Saperix Corporate（Azure）<b>40</b></p><p>Saperix, Inc. <b>2</b></p><p>WiFi 測試環境 <b>1</b></p></section>
 <section class="spm-card"><header>新的重大／嚴重發現事項 <select><option>90 天</option></select></header><div class="finding-total"><span>所有 SPM 公司</span><strong>1,063</strong></div><h4>最多新發現事項</h4><p>Saperix, Inc. <b>799</b></p><p>Awesome Inc <b>141</b></p><p>ABC-Test <b>62</b></p></section>
 <section class="spm-card"><header>協作收件匣</header><div class="inbox-item"><span>待處理</span><b>Saperix, Inc.</b><small>由資安團隊於 2026/08/27 傳送</small><p>請確認此發現事項與資產歸屬。</p></div><div class="inbox-item"><span>待處理</span><b>Saperix Corporate</b><small>由 Trevor LaBrie 於 2026/08/11 傳送</small></div></section>
</div>`;
function spmDashboard(){const stories=['Acronis 備份外掛程式權限提升弱點遭實際利用','Cisco ISE 驗證繞過弱點遭實際利用','Cisco 安全郵件閘道未經驗證命令執行','GitLab 路徑穿越可任意讀取檔案','ScreenConnect 未授權檔案傳輸與執行','JFrog Artifactory 驗證繞過與權限提升','Fortinet 防火牆與交換器管理遠端程式碼執行','Cisco 防火牆管理中心重大驗證繞過','Citrix NetScaler ADC 與 Gateway 驗證繞過','Adobe Commerce 與 Magento 範本引擎遠端程式碼執行'];return `${pagebar('我的公司儀表板','<button class="outline" data-modal="add-card">新增卡片</button><button class="outline" data-modal="edit-dashboard">編輯儀表板</button>')}<div class="content spm-page"><section class="panel spm-updates"><header>最新更新 <button data-toggle="updates">隱藏　⌃</button></header><div id="updates" class="spm-update-grid"><article><h2>△　10 項新興資安事件</h2><hr><h3>${stories[state.update]}</h3><div class="meta"><span><b>嚴重程度</b><br>CVSS 7.8</span><span><b>DVE 分數</b><br>10</span></div><h4>說明</h4><p>這項高嚴重性弱點可能讓低權限攻擊者提升權限並執行任意程式碼。建議立即確認暴露資產並套用修補程式。</p><div class="advisories">▮ 供應商公告　　▮ CISA 公告</div><small class="event-date">▣ 新增日期：2026/09/17</small><div class="update-foot"><button data-update="prev">←</button><span>${state.update+1} / 10</span><button data-nav="spm-threat-detection">檢視弱點偵測</button><button data-update="next">→</button></div></article><aside><h3>威脅情報新聞　<em>pulse</em></h3><hr><h3>新型惡意程式提供遠端桌面、竊密與錢包注入功能</h3><p>近期威脅情報摘要，協助資安團隊快速理解外部威脅與可能影響。</p><button data-toast="已開啟威脅情報摘要">繼續閱讀</button><footer>←　1 / 4　→</footer></aside></div></section>${spmCards()}</div>`}
function spmGeneric(){const cfg={
 'spm-company-details':['公司詳細資料',['公司','安全評等','評等變化','標籤','主要公司'],[['Saperix, Inc.','420','−20','主要公司','是'],['Saperix Corporate','690','+10','業務單位','否'],['Awesome Inc','640','−10','子公司','否']]],
 'spm-findings':['全部發現事項',['發現事項','公司','嚴重程度','最近發現','狀態'],[['過期 SSL 憑證','Saperix, Inc.','重大','2026/09/20','待處理'],['開放遠端管理連接埠','Awesome Inc','高','2026/09/19','調查中'],['DKIM 設定不完整','Saperix Corporate','中','2026/09/18','已指派']]],
 'spm-attack-surface':['攻擊面總覽',['資產','類型','公司','暴露狀態','最近觀察'],[['portal.example.com','網域','Saperix, Inc.','外部可見','今天'],['203.0.113.18','IP 位址','Awesome Inc','需檢視','昨天'],['Azure East Asia','雲端資產','Saperix Corporate','已確認','3 天前']]],
 'spm-action-plans':['行動計畫',['計畫','公司','負責人','到期日','進度'],[['修補外部弱點','Saperix, Inc.','資安團隊','2026/09/30','65%'],['強化郵件安全','Awesome Inc','IT 團隊','2026/10/05','30%']]],
 'spm-peer':['同業比較',['比較項目','本公司','同業中位數','百分位','趨勢'],[['安全評等','420','710','18%','下降'],['修補節奏','基礎','中階','25%','持平'],['網路安全','C','B','31%','改善中']]],
 'spm-collaboration':['協作',['主旨','公司','傳送者','日期','狀態'],[['確認資產歸屬','Saperix, Inc.','資安團隊','2026/08/27','待回覆'],['重大弱點改善證據','Saperix Corporate','Trevor LaBrie','2026/08/11','進行中']]],
 'spm-alerts':['警示',['警示','公司','日期','類型','狀態'],[['Bitsight 新發現事項警示','Saperix Corporate','2026/09/19','發現事項','未讀'],['SSL 憑證警示','Saperix, Inc.','2026/09/19','基礎設施','未讀'],['安全評等下降','Awesome Inc','2026/09/18','評等','已讀']]],
 'spm-reports':['報表',['報表名稱','範圍','上次產生','排程','操作'],[['公司風險摘要','主要公司','今天','每週','下載'],['發現事項趨勢','全部 SPM 公司','昨天','每月','檢視'],['高階主管摘要','Saperix, Inc.','7 天前','每月','下載']]],
 'spm-integrations':['整合',['整合服務','用途','狀態','上次同步','操作'],[['ServiceNow','工單與改善追蹤','已連線','10 分鐘前','管理'],['Microsoft Sentinel','SIEM 事件匯入','可設定','—','設定'],['Splunk','警示與事件串接','可設定','—','設定']]],
 'spm-rating-tree':['評等樹',['組織節點','安全評等','評等類型','資產數','關係'],[['Saperix, Inc.','420','主要評等','318','根節點'],['Saperix Corporate','690','自行發布','124','子公司'],['Saperix Lab','720','次要評等','46','業務單位']]],
 'spm-infrastructure-config':['基礎設施設定',['資產範圍','來源','狀態','上次變更','操作'],[['saperix.example','網域','已核准','2026/09/18','編輯'],['203.0.113.0/24','IP 範圍','已核准','2026/09/12','編輯'],['Azure 訂閱','雲端連接器','待確認','2026/09/20','檢視']]],
 'spm-risk-vectors':['風險面向',['風險面向','等級','發現事項','30 天變化','建議'],[['修補節奏','F','486','惡化','優先修補重大弱點'],['網路安全','C','163','持平','限制遠端管理服務'],['DNS 安全','B','27','改善','完成 DNSSEC 部署'],['Web 應用安全','D','92','惡化','檢查 TLS 與標頭']]],
 'spm-threat-detection':['弱點偵測',['弱點','DVE 分數','暴露資產','利用狀態','處置'],[['CVE-2026-87886','10','3','已遭利用','立即修補'],['CVE-2026-76460','10','1','已遭利用','隔離資產'],['CVE-2026-85706','9.8','5','概念驗證公開','升級 GitLab']]],
 'spm-assets':['基礎設施',['資產','資產類型','歸屬公司','來源','狀態'],[['portal.saperix.example','網域','Saperix, Inc.','DNS 探索','已確認'],['203.0.113.18','IPv4','Awesome Inc','掃描','需確認'],['mail.saperix.example','主機','Saperix Corporate','憑證','已確認']]],
 'spm-digital-footprint':['數位足跡',['數位資產','技術／服務','首次發現','風險','歸屬'],[['login.saperix.example','Microsoft IIS','2026/05/11','中','Saperix, Inc.'],['shop.saperix.example','Adobe Commerce','2026/07/08','高','待確認'],['api.saperix.example','NGINX','2026/08/16','低','Saperix Corporate']]],
 'spm-remediation':['改善追蹤',['改善事項','關聯發現','公司','目標日期','狀態'],[['更新 Acronis 外掛程式','CVE-2026-87886','Saperix, Inc.','2026/09/24','進行中'],['停用舊版 TLS','TLS 設定','Awesome Inc','2026/09/28','已指派'],['部署 DNSSEC','DNS 安全','Saperix Corporate','2026/10/10','規劃中']]],
 'spm-company-list':['我的公司清單',['公司','安全評等','關係','標籤','狀態'],[['Saperix, Inc.','420','主要公司','主要評等','監控中'],['Saperix Corporate','690','子公司','Azure','監控中'],['Awesome Inc','640','關聯公司','測試','監控中']]],
 'spm-subsidiaries':['子公司',['子公司','安全評等','評等變化','改善計畫','狀態'],[['Saperix Corporate','690','+10','進行中','需關注'],['Saperix Lab','720','0','未建立','穩定']]],
 'spm-assessments':['評估',['評估名稱','公司','完成度','到期日','狀態'],[['年度資安評估','Saperix, Inc.','82%','2026/10/15','進行中'],['雲端控制評估','Saperix Corporate','100%','2026/09/10','已完成']]],
 'spm-breach-intelligence':['資料外洩情報',['事件','公司','日期','資料類型','狀態'],[['憑證外洩訊號','Awesome Inc','2026/09/12','帳號憑證','調查中'],['公開儲存桶','Saperix Corporate','2026/08/29','設定資訊','已處理']]],
 'spm-badge':['Bitsight 徽章',['徽章','適用公司','目前評等','有效期限','狀態'],[['Security Rating Badge','Saperix, Inc.','420','2027/09/01','可發布']]],
 'spm-work-from-home':['居家辦公',['來源網路','裝置數','暴露服務','風險等級','最近觀察'],[['遠端辦公網路 A','34','5','中','今天'],['遠端辦公網路 B','18','1','低','昨天']]],
 'spm-cloud-infrastructure':['雲端基礎設施同步',['雲端帳戶','平台','資產數','上次同步','狀態'],[['Saperix Production','Microsoft Azure','124','10 分鐘前','已連線'],['Saperix Lab','AWS','46','2 小時前','已連線']]],
 'spm-probable-infrastructure':['可能的基礎設施',['資產','判斷依據','可信度','建議歸屬','狀態'],[['198.51.100.24','共同憑證','高','Saperix, Inc.','待確認'],['lab-saperix.example','DNS 關聯','中','Saperix Lab','待確認']]],
 'spm-third-party-assets':['第三方資產',['資產','服務提供者','產品','公司','風險'],[['login.microsoftonline.com','Microsoft','Entra ID','Saperix, Inc.','低'],['saperix.service-now.com','ServiceNow','ITSM','Saperix Corporate','中']]],
 'spm-forecasting':['評等預測',['情境','目前評等','預測評等','預計變化','時間範圍'],[['修補重大弱點','420','510','+90','90 天'],['改善 TLS 設定','420','450','+30','30 天']]],
 'spm-subsidiary-improvement':['子公司改善',['子公司','目前評等','目標評等','改善項目','進度'],[['Saperix Corporate','690','740','4','50%'],['Saperix Lab','720','760','2','25%']]],
 'spm-control-insights':['控制措施洞察',['控制措施','涵蓋風險','成熟度','缺口','建議'],[['弱點管理','修補節奏','基礎','3','建立修補 SLA'],['外部資產管理','攻擊面','中階','2','確認未知資產']]],
 'spm-risk-position':['風險位置',['比較群組','本公司百分位','同業中位數','評等差距','狀態'],[['全球軟體業','18%','710','−290','低於同業'],['亞太科技業','22%','690','−270','低於同業']]],
 'spm-infections':['感染事件',['事件','資產','惡意程式','首次發現','狀態'],[['殭屍網路通訊','203.0.113.18','未知下載器','2026/09/18','調查中'],['垃圾郵件活動','mail.saperix.example','Spam bot','2026/09/12','已處理']]],
 'spm-alert-settings':['警示設定',['規則名稱','觸發條件','公司範圍','通知方式','狀態'],[['重大評等下降','下降 40 分以上','所有 SPM 公司','電子郵件','啟用'],['新的重大發現','重大／嚴重','主要公司','電子郵件、Webhook','啟用'],['基礎設施變更','新增外部資產','Saperix, Inc.','電子郵件','暫停']]]};
 const fallback=[spmNames[state.page]||'安全態勢管理',['項目','公司','類型','更新時間','狀態'],[['示範項目 A','Saperix, Inc.','資安資訊','今天','需檢視'],['示範項目 B','Awesome Inc','監控資訊','昨天','已確認']]];const [title,headers,rows]=cfg[state.page]||fallback;const summaries={'spm-company-details':['3 家公司','420 主要評等','2 個組織節點'],'spm-findings':['1,063 項發現','155 項高優先','799 項屬於主要公司'],'spm-risk-vectors':['4 個風險面向','1 個改善中','2 個需優先處理'],'spm-threat-detection':['3 項重大弱點','9 個暴露資產','2 項遭實際利用'],'spm-attack-surface':['318 個資產','43 項近期變更','12 個需確認'],'spm-assets':['318 個資產','184 個網域','97 個 IP 位址'],'spm-digital-footprint':['246 個外部資產','17 項新發現','8 項高風險'],'spm-action-plans':['2 個行動計畫','6 個進行中工作','1 個即將到期'],'spm-remediation':['3 個改善事項','1 個進行中','0 個逾期'],'spm-peer':['第 18 百分位','同業中位數 710','評等差距 −290'],'spm-collaboration':['2 個待回覆','1 個進行中','0 個已逾期'],'spm-alerts':['3 個近期警示','2 個未讀','1 個已處理'],'spm-alert-settings':['2 個啟用規則','1 個暫停','2 種通知管道'],'spm-reports':['3 份報表','2 個排程','今天更新'],'spm-integrations':['1 個已連線','2 個可設定','10 分鐘前同步']}[state.page]||[rows.length+' 筆項目','資料已更新','可套用篩選'];return `${pagebar(title,'<button class="outline" data-toast="已建立示範篩選條件">篩選</button><button class="outline" data-modal="spm-action">動作⌄</button>')}<div class="content"><div class="spm-summary">${summaries.map((x,i)=>`<div><small>${['總覽','需關注','狀態'][i]}</small><strong>${x}</strong></div>`).join('')}</div></div><div class="content spm-list-page"><aside class="spm-filter"><h3>篩選</h3><input placeholder="搜尋篩選條件"><button>公司　⌄</button><button>嚴重程度　⌄</button><button>狀態　⌄</button><button>日期範圍　⌄</button></aside><section class="panel table-panel"><div class="table-tools"><b>${rows.length} 筆結果</b><span class="spacer"></span><input class="spm-search" placeholder="搜尋${title}"><button data-toast="示範資料已準備匯出">↓</button></div><div class="table-scroll"><table class="data-table"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map((v,i)=>`<td class="${i===0?'name':''}">${v}</td>`).join('')}</tr>`).join('')}</tbody></table></div></section></div>`}
function spmCompanyDetails(){return `${pagebar('Saperix, Inc. 公司詳細資料','<button class="outline" data-modal="reports">報表　▧</button><button class="outline" data-modal="spm-action">動作　⌄</button>')}<div class="content spm-company-page">
 <div class="company-overview-grid">
  <section class="panel company-rating"><h3>Bitsight 安全評等</h3><a>關於評等</a><div class="company-gauge"><span class="gauge-score">420<small>▰ 基礎</small></span></div><div class="gauge-range"><b>300</b><b>820</b></div><h4>前往主要評等</h4><button data-toast="已選擇主要評等公司">★ Saperix Lab</button><button data-nav="spm-rating-tree">檢視評等樹</button></section>
  <section class="panel incident-risk"><h3>資安事件風險</h3><div class="risk-block"><p><b>勒索軟體：</b>相較評等 750 以上的公司，您的風險高出 <strong>7.9 倍</strong>。 <a>深入了解</a></p><div class="risk-label"><span>高風險</span><span>您</span><span>低風險</span></div><div class="risk-scale"><i style="left:24%"></i></div></div><div class="risk-block"><p><b>資安事件：</b>相較評等 750 以上的公司，您的風險高出 <strong>4.8 倍</strong>。 <a>深入了解</a></p><div class="risk-label"><span>高風險</span><span>您</span><span>低風險</span></div><div class="risk-scale"><i style="left:27%"></i></div></div></section>
  <section class="panel company-info"><h3>公司資訊</h3><a>關於公司資訊</a><p>Saperix Technologies LLC 開發風險分析軟體解決方案。</p><dl><dt>訂閱</dt><dd>我的公司</dd><dt>關係</dt><dd>我的公司</dd><dt>監控者</dt><dd>262 家公司</dd><dt>搜尋者</dt><dd>22,729 位使用者</dd></dl><button data-modal="company-details">顯示詳細資料</button></section>
 </div>
 <section class="panel company-rating-history">
  <header><h3>安全評等變化</h3><button aria-label="更多選項">⋮</button></header>
  <div class="rating-history-stats">
   <article><small>最高評等（2026 年 4 月 6 日）</small><strong>490 <em>▰ 基礎</em></strong></article>
   <article><small>最低評等（2026 年 7 月 15 日）</small><strong>410 <em>▰ 基礎</em></strong></article>
   <article><small>2025 年變化次數</small><strong>2 <em>1 <span class="down">▼</span> ／ 1 <span class="up">▲</span></em></strong></article>
   <article><small>2026 年變化次數</small><strong>26 <em>15 <span class="down">▼</span> ／ 11 <span class="up">▲</span></em></strong></article>
  </div>
  <div class="rating-history-body">
   <div class="rating-history-chart"><p>按住並拖曳以縮放。</p>
    <svg viewBox="0 0 850 410" role="img" aria-label="2025 年 9 月至 2026 年 9 月的安全評等變化圖">
     <rect x="44" y="27" width="786" height="72" fill="#e5e9ec"/><path d="M44 80H830" stroke="#8c9ca6" stroke-width="2"/>
     ${[27,55,83,111,139,167,195,223,251,279,307,335,363,391].map((y,i)=>`<g><line x1="44" y1="${y}" x2="830" y2="${y}" stroke="#ccd5da" stroke-dasharray="4 3"/><text x="4" y="${y+5}" font-size="13" fill="#344b5b">${820-i*40}</text></g>`).join('')}
     <rect x="44" y="27" width="15" height="55" fill="#2aa26b"/><rect x="44" y="82" width="15" height="68" fill="#e1ae35"/><rect x="44" y="150" width="15" height="241" fill="#c9362d"/>
     <path d="M59 248 L64 258 L112 258 L112 267 L290 267 L290 258 L310 267 L324 258 L337 267 L350 258 L363 267 L378 258 L456 258 L456 250 L535 250 L535 258 L590 258 L600 267 L612 258 L620 267 L630 258 L640 267 L650 276 L690 276 L690 286 L724 286 L724 276 L738 286 L748 286 L748 304 L792 304 L792 276 L830 276" fill="none" stroke="#0d1114" stroke-width="4" stroke-linejoin="round"/>
     ${[[112,258],[290,267],[310,258],[324,267],[337,258],[350,267],[363,258],[378,258],[456,250],[535,250],[590,258],[600,267],[612,258],[620,267],[630,258],[640,267],[650,276],[690,276],[724,286],[738,286],[748,304],[792,304]].map(([x,y])=>`<circle cx="${x}" cy="${y}" r="5" fill="#0876b9" stroke="white" stroke-width="2"/>`).join('')}
     ${['2025 年 9 月','2025 年 11 月','2026 年 1 月','2026 年 3 月','2026 年 5 月','2026 年 7 月','2026 年 9 月'].map((m,i)=>`<text x="${44+i*126}" y="408" font-size="12" fill="#344b5b">${m}</text>`).join('')}
    </svg>
    <div class="rating-history-options"><label><input type="checkbox"> 隱藏上升事件</label><label><input type="checkbox" checked> 科技業產業範圍與中位數</label></div>
   </div>
   <aside class="rating-history-events"><h2>2026</h2><article><p>生效日期：<b>8 月 22 日</b></p><strong>410　↗　420</strong><span class="up">▲ 上升 10 分</span><h4>原因</h4><p>SSL 憑證：輕微變化，等級維持 D。</p><p>桌面軟體：輕微變化，等級維持 F。</p></article><article><b class="algorithm">評等演算法更新</b><p>評等日期：<b>7 月 15 日</b></p><strong>450　↘　410</strong><span class="down">▼ 下降 40 分</span></article></aside>
  </div>
 </section>
 <div class="company-detail-grid source-detail-grid">
  <section class="panel rating-overview"><h3>評等總覽</h3><p>評等總覽顯示此公司管理各項風險面向的成效。點選風險面向可查看風險細節。</p><div class="rating-vector-columns"><div><h4>受駭系統</h4>${[['殭屍網路感染','C'],['垃圾郵件傳播','D'],['惡意程式伺服器','A'],['未經請求的通訊','A'],['可能遭到利用','C']].map(x=>`<button>${x[0]}<i class="${gradeClass(x[1])}">${x[1]}</i></button>`).join('')}<h4>使用者行為</h4><button>檔案分享<i class="bad">D</i></button><button>外洩憑證 **<i>N/A</i></button><h4>公開揭露</h4><button>資安事件／資料外洩<i class="good">A</i></button><button>其他揭露 *<i>N/A</i></button></div><div><h4>盡職調查</h4>${[['SPF 網域','C'],['DKIM 記錄','C'],['DMARC','B'],['TLS/SSL 憑證','D'],['TLS/SSL 設定','F'],['開放連接埠','C'],['Web 應用程式安全','D'],['重大弱點管理','F'],['不安全系統','F'],['伺服器軟體','B'],['桌面軟體','F'],['行動軟體','D'],['DNSSEC *','C'],['Web 應用程式標頭 *','N/A'],['網域仿冒 **','N/A']].map(x=>`<button>${x[0]}<i class="${gradeClass(x[1])}">${x[1]}</i></button>`).join('')}</div></div><small>* 此風險面向目前不影響安全評等<br>** 資訊型風險面向（不會影響安全評等）</small></section>
  <section class="panel rating-makeup"><h3>安全評等如何組成？</h3><div class="makeup-donut"><span>風險類別<br>權重</span></div><ul><li><i></i><b>2.5%</b> 使用者行為</li><li><i></i><b>26%</b> 受駭系統</li><li><i></i><b>71.5%</b> 盡職調查</li></ul><p>各風險類別在評等中的權重。公開揭露可能影響 Bitsight 評等，但此類別中的風險面向沒有固定權重。</p><a>深入了解評等的計算方式</a><a>深入了解每項風險面向</a></section>
  <section class="panel source-table-card"><header><h3>感染事件</h3><span>最近 90 天</span></header><input placeholder="搜尋"><table><thead><tr><th>名稱</th><th>嚴重程度</th><th>首次發現</th><th>變化</th><th>受影響主機</th></tr></thead><tbody>${[['Spam Bot','嚴重','2026/07/02','0%','1'],['DroidRooter','重大','2026/07/15','0%','1'],['ProxyServices','重大','2026/07/16','0%','1']].map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table><a>關於</a></section>
  <section class="panel source-table-card vulnerability-table"><header><h3>弱點</h3><span>最近 90 天</span></header><input placeholder="搜尋"><table><thead><tr><th>名稱</th><th>嚴重程度</th><th>變化</th><th>受影響主機</th></tr></thead><tbody>${[['POODLE','輕微','−3%','77'],['CVE-2021-26691','嚴重','−6%','30'],['CVE-2024-38475','嚴重','−10%','19'],['CVE-2021-34798','重大','−20%','8'],['CVE-2026-1293','中度','0%','4'],['CVE-2024-23897','嚴重','0%','3']].map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table><div class="table-pager">顯示 1–6，共 39 筆　 <button>上一頁</button><button>下一頁</button></div></section>
  <section class="panel compliance-card"><h3>自行聲明合規</h3><p>此組織自行聲明已取得下列框架的認證及／或符合以下法規。Bitsight 未獨立驗證任何認證，也未確認此組織是否符合這些法規。 <a>深入了解</a></p><div class="compliance-tags"><b>NIST CSF</b><b>ISO-27001</b><b>GDPR</b><b>HIPAA</b><b>PCI DSS</b></div><button>檢視合規網頁</button></section>
  <section class="panel compromised-card"><h3>受駭系統</h3><p>受駭系統是組織網路中出現惡意或非預期軟體跡象的裝置或機器。這些感染可能干擾日常營運並提高資料外洩風險。</p><div class="compromised-metrics"><div><b>本週</b><strong>0</strong></div><div><b>過去一年</b><strong>79</strong></div><div><b>平均事件持續時間</b><strong>1.6 <small>天</small></strong></div></div><div class="duration-bars"><span style="--w:31%">1.6 天　Saperix, Inc.</span><span style="--w:100%">5.2 天　投資組合平均</span><span style="--w:62%">3.2 天　科技業平均</span></div><a>檢視詳細資料</a></section>
  <section class="panel remediation-card"><h3>改善策略</h3><p>假設未出現新發現，以下風險面向在 60 天內具有最高的潛在評等影響。</p>${[['SSL 設定','60 分'],['SSL 憑證','30 分'],['桌面軟體','10 分']].map(x=>`<div><a>${x[0]}</a><b>${x[1]}</b><button>改善計畫</button></div>`).join('')}<footer><a>檢視發現事項</a><a>改善計畫</a></footer></section>
  <section class="panel diligence-card"><h3>盡職調查</h3><p>盡職調查風險面向顯示公司為防止攻擊所採取的措施。Bitsight 掌握 Saperix, Inc. 的 <b>27,631</b> 筆盡職調查紀錄。</p><h4>最近 60 天</h4><div class="diligence-chart"><div class="axis-title">紀錄百分比</div><div class="stack-area"><div class="grid-labels"><span>100%</span><span>75%</span><span>50%</span><span>25%</span><span>0%</span></div><div class="stack-bars"><div><i style="--neutral:44%;--bad:9%;--warn:3%;--fair:2%;--good:42%"></i><b>公司</b></div><div><i style="--neutral:31%;--bad:6%;--warn:6%;--fair:3%;--good:54%"></i><b>產業</b></div><div><i style="--neutral:32%;--bad:8%;--warn:2%;--fair:4%;--good:54%"></i><b>投資組合</b></div></div></div><ul><li>良好</li><li>普通</li><li>警告</li><li>不佳</li><li>中性</li></ul></div><button class="detail-button">檢視詳細資料</button></section>
  <section class="panel network-card source-network"><h3>網路足跡</h3><div class="world-map"><svg viewBox="0 0 900 430" role="img" aria-label="依 IP 數量呈現的全球網路足跡"><g stroke="#87a3b4" stroke-width="3" stroke-linejoin="round"><path fill="#5b8299" d="M70 105l45-38 87-25 86 11 34 34-24 35-52 13-25 35-39 7-20 43-36-6-17-45-38-22z"/><path fill="#164966" d="M72 142l42 12 49 25 33 54-21 33-42-20-27-50-36-19z"/><path fill="#174b68" d="M118 216l55 8 41 40 7 50-29 78-25-18-13-65-36-45z"/><path fill="#b9d4e3" d="M219 50l65-18 45 17-12 31-70 4z"/><path fill="#6f93a7" d="M397 91l55-30 49 9 29 32-20 37-45-5-34 24-37-21z"/><path fill="#f5f8fa" d="M417 144l75-8 54 34 24 63-19 82-56 72-42-17-20-73-36-54z"/><path fill="#6a90a5" d="M515 116l92-60 106 12 92 63-28 46-75 7-48-20-43 41-59-17z"/><path fill="#5f879d" d="M653 154l77-12 48 24-18 47-72 25-43-36z"/><path fill="#a9c9da" d="M727 289l70-6 37 41-28 50-76-11-25-34z"/><path fill="#5c8399" d="M811 176l31-26 28 18-19 37z"/><path fill="#d6e4eb" d="M349 92l25-29 18 20-11 28z"/></g></svg><div class="map-zoom"><button>＋</button><button>−</button></div><div class="map-scale"><div><i></i><i></i><i></i><i></i><i></i></div><span>1 個 IP　　10 個 IP　　100 個 IP　　1,000 個 IP　　10,000 個 IP</span></div></div></section>
 </div>
 </div>`}
const riskGroups=[
 ['受駭系統','總權重：26%',[['殭屍網路感染','最高 26%','C'],['垃圾郵件傳播','最高 26%','D'],['惡意程式伺服器','最高 26%','A'],['未經請求的通訊','最高 26%','A'],['可能遭到利用','最高 26%','C']]],
 ['盡職調查','總權重：71.5%',[['SPF 網域','1%','C'],['DKIM 記錄','1%','C'],['DMARC','1%','B'],['TLS/SSL 憑證','10%','D'],['TLS/SSL 設定','15%','F'],['開放連接埠','10%','C'],['Web 應用程式安全','5%','D'],['重大弱點管理','20%','F'],['不安全系統','2.5%','F'],['伺服器軟體','2%','B'],['桌面軟體','3%','F'],['行動軟體','1%','D'],['DNSSEC*','不影響評等','C'],['Web 應用程式標頭*','不影響評等','N/A'],['網域仿冒**','不影響評等','N/A']]],
 ['使用者行為','總權重：2.5%',[['檔案分享','2.5%','D'],['外洩憑證**','不影響評等','N/A']]],
 ['公開揭露','浮動權重',[['資安事件／資料外洩','部分事件影響評等','A'],['其他揭露*','不影響評等','N/A']]]
];
function gradeClass(g){return g==='A'||g==='B'?'good':g==='F'||g==='D'?'bad':'average'}
function spmRiskVectors(){const weights=[['受駭系統',26],['重大弱點管理',20],['SSL 設定',15],['SSL 憑證',10],['開放連接埠',10],['Web 應用程式安全',5],['桌面軟體',3],['檔案分享',2.5],['不安全系統',2.5],['伺服器軟體',2],['其他',4]];return `${pagebar('Saperix, Inc. 風險面向總覽','<button class="outline" data-modal="reports">報表　▧</button><button class="outline" data-modal="spm-action">動作　⌄</button>')}<div class="risk-vector-layout"><aside class="risk-vector-nav"><button class="rv-overview active">總覽　‹</button>${riskGroups.map(([group,total,items])=>`<section><h4>${group}</h4><b>${total}</b>${items.map(([name,w,g])=>`<button data-rv="${name}"><span>${name}<small>權重：${w}</small></span><i class="${gradeClass(g)}">${g}</i></button>`).join('')}</section>`).join('')}</aside><main class="risk-vector-main"><section class="panel rv-intro"><h2>總覽</h2><h3>關於風險面向與類別</h3><div class="rv-intro-grid"><p>了解風險面向、類別及本頁的運作方式，有助於安排資源優先順序，並對安全評等產生最大正面影響。改善工作應優先處理權重最高的風險類別與相關面向。<br><br><a>Bitsight 安全評等</a>會每日依專有演算法計算，用來評估組織的資安成效。</p><ul>${weights.map(([n,w])=>`<li><i></i><b>${w}%</b> ${n}</li>`).join('')}</ul><div class="rv-donut"><span>影響評等的<br>風險面向權重</span></div></div></section>${riskGroups.map(([group,total,items])=>`<section class="panel rv-group"><h2>${group}</h2><div class="rv-cards">${items.map(([name,w,g],i)=>`<article><i class="${gradeClass(g)}">${g}</i><div><h3>${name}　<a>#</a></h3><span>${g==='A'?'前 10%':g==='B'?'前 30%':g==='C'?'前 50%':g==='D'?'後 30%':g==='F'?'後 20%':'無評級'}</span></div><button data-nav="spm-findings">查看發現事項</button></article>`).join('')}</div></section>`).join('')}</main></div>`}
function rvGrade(g){return `<i class="rv2-grade ${gradeClass(g)}">${g}</i>`}
function rvNav(){return `<aside class="rv2-nav"><button class="rv2-overview">總覽 <span>‹</span></button><div class="rv2-nav-scroll">${riskGroups.map(([group,total,items])=>`<section><h3>${group}</h3><b>${total}</b>${items.map(([name,w,g])=>`<button><span>${name}<small>${w.includes('不影響')?'不影響評等':'權重：'+w}</small></span>${rvGrade(g)}</button>`).join('')}</section>`).join('')}</div></aside>`}
function rvOverview(){const weights=[['26%','受駭系統'],['20%','重大弱點管理'],['15%','TLS/SSL 設定'],['10%','TLS/SSL 憑證'],['10%','開放連接埠'],['5%','Web 應用程式安全'],['3%','桌面軟體'],['2.5%','檔案分享'],['2.5%','不安全系統'],['2%','伺服器軟體'],['4%','其他']];return `<section class="panel rv2-overview-card"><h2>總覽</h2><h3>關於風險面向與類別</h3><div class="rv2-overview-body"><p>了解風險面向、類別及本頁的運作方式，有助於安排資源優先順序，並對評等產生最大的正面影響。改善工作應配合對安全評等貢獻最高的風險類別及相關面向。<br><br><a>Bitsight 安全評等</a>會使用專有演算法每日產生並計算，用以評估組織的資安成效。右側圖表顯示主要風險面向及其在 Bitsight 評等中的權重百分比。</p><ul>${weights.map(x=>`<li><i></i><b>${x[0]}</b> ${x[1]}</li>`).join('')}</ul><div class="rv2-donut"><span>影響評等的<br>風險面向權重</span></div></div></section>`}
function rvBubbleChart(){const dots=[[65,108,10],[118,165,7],[172,135,9],[230,190,7],[285,145,11],[345,215,8],[405,168,10],[466,235,7],[528,185,12],[592,220,8],[648,155,10],[710,205,7]];return `<div class="rv2-bubble"><header><h3>過去 12 個月的事件</h3><label>納入不影響評等的發現事項　<input type="checkbox"></label></header><svg viewBox="0 0 760 260"><g stroke="#d8e1e6" stroke-dasharray="4 4">${[35,80,125,170,215].map(y=>`<line x1="35" y1="${y}" x2="745" y2="${y}"/>`).join('')}</g>${dots.map(([x,y,r],i)=>`<circle cx="${x}" cy="${y}" r="${r}" fill="${['#347da6','#d16a54','#66a66e','#8f6fb0','#d8ad42'][i%5]}" opacity=".9"/>`).join('')}<g fill="#526a78" font-size="11">${['9 月','10 月','11 月','12 月','1 月','2 月','3 月','4 月','5 月','6 月','7 月','8 月'].map((m,i)=>`<text x="${45+i*60}" y="252">${m}</text>`).join('')}</g></svg><div class="rv2-chart-legend"><span>● 殭屍網路感染</span><span>● 垃圾郵件傳播</span><span>● 惡意程式伺服器</span><span>● 未經請求的通訊</span><span>● 可能遭到利用</span></div></div>`}
function rvExpanded(name,g,rank,desc,a,b){return `<article class="rv2-expanded"><header>${rvGrade(g)}<h3>${name}　<a>#</a><small>${rank}</small></h3></header><div class="rv2-expanded-body"><p>${desc}</p><a>檢視發現事項</a>　<a>更多資訊</a><div class="rv2-compare"><section><h4>過去一年的事件數</h4><b>${a}% 少於科技業</b><i><span style="width:${a}%"></span></i><small>Saperix, Inc.　　　　科技業</small></section><section><h4>過去一年解決事件的平均天數</h4><b>${b}% 快於科技業</b><i><span style="width:${b}%"></span></i><small>Saperix, Inc.　　　　科技業</small></section></div></div></article>`}
const rvDescriptions={
 '惡意程式伺服器':'偵測組織基礎設施中託管惡意內容、惡意程式或攻擊工具的伺服器。',
 '未經請求的通訊':'偵測從組織網路發出的可疑或未經請求通訊活動。','可能遭到利用':'識別可能已遭威脅行為者利用的系統與裝置。',
 'SPF 網域':'評估網域是否正確設定 SPF，以降低電子郵件偽冒風險。','DKIM 記錄':'評估電子郵件是否使用 DKIM 簽章來驗證郵件來源。','DMARC':'評估網域是否使用 DMARC 政策防止電子郵件冒用。',
 'TLS/SSL 憑證':'評估公開服務使用的 TLS/SSL 憑證是否有效、安全且正確部署。','TLS/SSL 設定':'評估伺服器的加密協定與密碼套件是否符合安全實務。','開放連接埠':'識別可從網際網路存取、可能增加攻擊面的網路服務。',
 'Web 應用程式安全':'評估公開網站與 Web 應用程式中的安全設定與常見弱點。','重大弱點管理':'衡量組織修補高風險與已知遭利用弱點的速度。','不安全系統':'識別使用過時、停止支援或具有高風險設定的系統。',
 '伺服器軟體':'評估對外伺服器軟體的版本、支援狀態與已知弱點。','桌面軟體':'評估終端裝置桌面軟體的版本與安全更新狀態。','行動軟體':'評估行動裝置軟體與應用程式的更新和安全狀態。',
 'DNSSEC*':'顯示網域是否使用 DNSSEC 保護 DNS 回應的完整性。','Web 應用程式標頭*':'檢查 Web 應用程式是否設定建議的 HTTP 安全標頭。','網域仿冒**':'識別可能冒用公司品牌、網域或商標的相似網域。',
 '檔案分享':'識別可能透過點對點檔案分享服務暴露資料的活動。','外洩憑證**':'顯示在公開資料來源中發現、可能與組織相關的外洩帳號。',
 '資安事件／資料外洩':'彙整已公開揭露且可能影響安全評等的資安事件與資料外洩。','其他揭露*':'顯示其他公開揭露、執法或監管相關的資安資訊。'};
function rvPercentile(g){return g==='A'?'前 10%':g==='B'?'前 30%':g==='C'?'前 50%':g==='D'?'後 30%':g==='F'?'後 20%':'無評級'}
function rvFullVector(name,g,index){const na=g==='N/A',v1=18+(index*13)%68,v2=24+(index*17)%64;return `<article class="rv2-full-vector"><header>${rvGrade(g)}<h3>${name}　<a>#</a><small>${rvPercentile(g)}</small></h3></header><p>${rvDescriptions[name]||'此風險面向呈現組織目前的安全成效與可改善項目。'}</p><p><a>檢視發現事項</a>　<a>更多資訊</a></p>${na?`<div class="rv2-na-note">此資訊型風險面向目前不影響 Bitsight 安全評等。</div>`:`<div class="rv2-vector-charts"><section><h4>過去一年觀察到的紀錄</h4><b>${v1}% 優於科技業</b><div class="rv2-bars"><span style="height:${v1}%"><i>Saperix</i></span><span style="height:${Math.min(96,v1+24)}%"><i>科技業</i></span></div></section><section><h4>最近 60 天的成效分布</h4><b>${v2}% 符合良好標準</b><div class="rv2-stack"><i style="width:${v2}%"></i><i style="width:${Math.max(8,70-v2)}%"></i><i></i></div><small>良好　　普通　　不佳</small></section></div>`}</article>`}
function rvFullGroup(group,items,start=0){return `<section class="panel rv2-group"><h2>${group}</h2>${items.map(([name,w,g],i)=>rvFullVector(name,g,start+i)).join('')}</section>`}
function spmRiskVectorsV2(){const compromised=riskGroups[0][2],diligence=riskGroups[1][2];return `${pagebar('Saperix, Inc. 風險面向總覽','<button class="outline" data-modal="reports">報表　▧</button><button class="outline" data-modal="spm-action">動作　⌄</button>')}<div class="rv2-layout">${rvNav()}<main class="rv2-main">${rvOverview()}<section class="panel rv2-compromised"><h2>受駭系統</h2><p>受駭系統是組織網路中出現惡意或非預期軟體跡象的裝置或機器。這些感染可能中斷日常營運並提高組織遭資料外洩的風險。</p><p>受駭系統會依惡意程式數量與類型、嚴重程度及持續時間進行評估，並為每項風險面向計算整體字母等級。</p>${rvBubbleChart()}${rvExpanded('殭屍網路感染','C','前 50%','殭屍網路感染事件表示公司網路中的裝置被觀察到參與殭屍網路，可能作為受控主機或命令與控制伺服器。',83,60)}${rvExpanded('垃圾郵件傳播','D','後 30%','當公司網路中的裝置正在傳送未經請求的商業或大量電子郵件時，便會記錄垃圾郵件傳播事件。',29,33)}${compromised.slice(2).map(([n,w,g],i)=>rvFullVector(n,g,i+2)).join('')}</section>${rvFullGroup('盡職調查',diligence,5)}${rvFullGroup('使用者行為',riskGroups[2][2],20)}${rvFullGroup('公開揭露',riskGroups[3][2],22)}</main></div>`}
const spmCompanyFilters=['資料夾','訂閱類型','安全評等','產業','國家／地區','自行發布','評等類型','風險面向等級','感染事件','弱點','開放連接埠','公開揭露','軟體','服務提供者','產品','產品類型'];
function spmCompanyList(){return `${pagebar('Saperix, Inc. 的公司清單','<button class="outline" data-modal="reports">報表　▧</button><button class="outline" data-modal="spm-action">動作　⌄</button>')}<div class="content spm-company-list"><div class="companies-layout"><aside class="filters"><div class="filter-top"><button class="active">▽ 篩選</button><button data-toast="選擇顯示欄位">▥</button><button data-toast="儲存的檢視">♧</button><button class="filter-collapse">‹</button></div><input class="filter-search" placeholder="搜尋篩選條件…"><div class="filter-scroll">${spmCompanyFilters.map(x=>`<div class="filter-row"><button data-filter="${x}">${x}<span>⌄</span></button>${state.filterOpen===x?`<div class="filter-options"><label><input type="checkbox"> 包含</label><label><input type="checkbox"> 不包含</label></div>`:''}</div>`).join('')}</div><button class="filter-bottom" data-modal="create-view">建立檢視</button></aside><section class="panel table-panel"><div class="table-tools"><b>0 家公司</b><button disabled>報表⌄</button><button disabled>動作⌄</button><span class="spacer"></span><button data-toggle="spm-company-search">⌕</button><button disabled>↓</button><button data-toggle="fullscreen">⛶</button></div><div class="table-scroll"><table class="data-table"><thead><tr><th><input type="checkbox" disabled></th><th>公司　↑</th><th>安全評等</th><th>趨勢</th><th>訂閱類型</th></tr></thead><tbody></tbody></table><div class="spm-empty-table">▽</div></div><div class="pager"><button>30⌄</button><span>0 – 0，共 0 筆</span><span class="spacer"></span><button disabled>‹</button><span>0 / 0</span><button disabled>›</button></div></section></div></div>`}
const subsidiaryRows=[['Saperix, Inc.','480','480','450','450','410','420','420'],['Awesome Inc','660','660','660','650','650','640','640'],['Saperix Corporate','670','670','660','650','650','650','650'],['ABC-Test','670','670','660','650','660','660','660'],['Saperix Lab','690','720','720','720','710','760','760']];
function ratingHeat(v){v=+v;return v<420?'#57241f':v<530?'#b84034':v<640?'#cf5140':v<680?'#c79c3d':v<710?'#d5ad48':v<740?'#ebca5d':v<770?'#4e9565':v<800?'#34734e':'#184c38'}
function spmSubsidiaries(){const months=['2026 年 4 月','2026 年 5 月','2026 年 6 月','2026 年 7 月','2026 年 8 月','2026 年 9 月','今天'];return `${pagebar('子公司')}<div class="content subsidiaries-page"><section class="panel subsidiary-panel"><div class="subsidiary-tools"><div><h3>組織歷史分布</h3><small>上次更新：2026/09/21</small></div><label class="switch"><input type="checkbox" id="allSubsidiaries"> 顯示所有子公司</label><select><option>Bitsight 評等</option></select><span>縮放</span><button class="active" data-sub-zoom="6m">6 個月</button><button data-sub-zoom="1y">1 年</button><span class="spacer"></span><button data-toast="示範熱圖已準備匯出">匯出　↓</button></div><div class="subsidiary-heatmap"><div class="heat-head">${months.map(x=>`<b>${x}</b>`).join('')}<b></b></div>${subsidiaryRows.map((r,i)=>`<div class="heat-row" data-subsidiary-row="${i}">${r.slice(1).map(v=>`<span style="background:${ratingHeat(v)}">${v}</span>`).join('')}<strong>▥　${r[0]}</strong></div>`).join('')}</div><div class="heat-legend"><p><b>基礎</b><i style="background:#57241f"></i>&lt; 410 <i style="background:#b84034"></i>420–520 <i style="background:#cf5140"></i>530–630</p><p><b>中階</b><i style="background:#c79c3d"></i>640–670 <i style="background:#d5ad48"></i>680–700 <i style="background:#ebca5d"></i>710–730</p><p><b>進階</b><i style="background:#4e9565"></i>740–760 <i style="background:#34734e"></i>770–790 <i style="background:#184c38"></i>&gt; 800</p></div><button class="subsidiary-cta" data-nav="spm-subsidiary-improvement">檢視子公司改善</button></section></div>`}
function spmBreach(){const fs=['嚴重程度','事件類型','評等影響','來源類型','國家／地區','產業','公司','日期','攻擊者','進階持續性威脅（APT）','CVE','受影響產品'];return `${pagebar('資料外洩情報','<button class="outline" data-toast="示範資料已準備下載">↓　下載 CSV</button>')}<div class="content breach-page"><aside class="breach-filters"><h3>▽ 篩選　‹</h3><input placeholder="搜尋篩選條件…">${fs.map(x=>`<button data-filter="${x}">${x}<span>⌄</span></button>`).join('')}</aside><section class="panel breach-results"><div class="breach-empty">▽</div></section></div>`}
function spmBadge(){const code='&lt;div id="bitsight-badge"&gt;&lt;/div&gt;\n&lt;script&gt;取得並顯示 Bitsight 評等徽章&lt;/script&gt;';return `${pagebar('Bitsight 徽章')}<div class="content badge-page"><section class="panel badge-panel"><label class="badge-enable"><input type="checkbox" checked> <span>啟用評等分享</span></label><p>建立可嵌入的元件來展示您的評等，並說明評等的意義及重要性。<a>深入了解</a></p><hr><div class="badge-tabs"><b>選項</b><button class="active" data-badge-tab="badge">徽章</button><button data-badge-tab="landing">到達頁面</button></div><div class="badge-builder"><div class="badge-preview"><span class="measure-v">300px</span><div class="badge-circle"><div class="badge-logo">BITSIGHT</div><strong>420</strong><small>安全評等 · 基礎</small></div><span class="measure-h">300px</span></div><aside><h4>版型</h4><label><input type="radio" name="layout" checked> 徽章</label><label><input type="radio" name="layout"> 窄版</label><label><input type="radio" name="layout"> 寬版</label><h4>尺寸</h4><label><input type="radio" name="size" checked> 大</label><label><input type="radio" name="size"> 中</label><label><input type="radio" name="size"> 小</label><hr><h4>嵌入碼</h4><pre>${code}</pre><button data-toast="已複製示範嵌入碼">複製嵌入碼</button></aside></div><section class="badge-config"><h3>徽章設定</h3><div><h4>我的評等</h4><label><input type="radio" checked> 90 天平均</label><label><input type="radio"> 目前評等</label></div><div><h4>產業比較</h4><label><input type="checkbox"> 顯示產業平均</label></div><div><h4>允許的網域</h4><p>預設僅能在 saperix.com 使用徽章嵌入碼。可在下方加入其他完整網址。</p><input placeholder="https://example.com"><button disabled>儲存變更</button></div></section></section></div>`}
function spmCompanyContent(html,kind=''){let out=html.replaceAll('範例商業銀行','Saperix, Inc.').replaceAll('範例物業管理集團','Saperix, Inc.').replaceAll('範例金融控股','Saperix Corporate').replaceAll('範例資訊服務','Saperix Lab');if(kind==='threat')out=out.replaceAll('威脅洞察：','弱點偵測：').replaceAll('主動偵測並回應新興威脅','偵測暴露於網際網路的重大弱點');return out}
