const spmMenu=[
 ['儀表板','spm-dashboard','⌁'],
 ['組織',null,'⌘',[
  ['公司詳細資料','spm-company-details'],['風險面向','spm-risk-vectors'],['評等樹','spm-rating-tree'],['我的公司清單','spm-company-list'],['子公司','spm-subsidiaries'],['評估','spm-assessments'],['資料外洩情報','spm-breach-intelligence'],['Bitsight 徽章','spm-badge']]],
 ['發現事項',null,'▣',[
  ['發現事項表格','spm-findings'],['問題追蹤','spm-remediation'],['弱點偵測','spm-threat-detection']]],
 ['攻擊面',null,'◎',[
  ['基礎設施','spm-assets'],['攻擊面分析','spm-attack-surface'],['居家辦公','spm-work-from-home'],['雲端基礎設施同步','spm-cloud-infrastructure'],['可能的基礎設施','spm-probable-infrastructure'],['第三方資產','spm-third-party-assets']]],
 ['行動計畫',null,'✓',[
  ['風險改善','spm-action-plans'],['評等預測','spm-forecasting'],['子公司改善','spm-subsidiary-improvement'],['控制措施洞察','spm-control-insights']]],
 ['同業比較',null,'♙',[
  ['同業分析','spm-peer'],['風險位置','spm-risk-position']]],
 ['協作','spm-collaboration','✉'],
 ['警示',null,'⚑',[
  ['已設定警示','spm-alert-settings'],['警示記錄','spm-alerts'],['感染事件','spm-infections']]],
 ['報表','spm-reports','▤'],['整合','spm-integrations','♧']
]
const spmNames=Object.fromEntries(spmMenu.flatMap(m=>m[3]?m[3].map(x=>[x[1],x[0]]):[[m[1],m[0]]]));
function isSpm(){return state.page.startsWith('spm-')}
function spmParent(page){return spmMenu.find(m=>m[3]?.some(x=>x[1]===page))?.[0]||''}
function spmNav(){return spmMenu.map(m=>`<div class="menu-group"><button class="menu-main ${state.page===m[1]||m[3]?.some(x=>x[1]===state.page)?'active':''}" data-nav="${m[1]||''}" data-group="${m[0]}"><span class="icon">${m[2]}</span><span>${m[0]}</span>${m[3]?'<span class="chev">'+(state.open===m[0]?'⌄':'›')+'</span>':''}</button>${m[3]&&state.open===m[0]?`<div class="submenu">${m[3].map(([label,id])=>`<button class="${state.page===id?'active':''}" data-nav="${id}">${label}</button>`).join('')}</div>`:''}</div>`).join('')}
function productSwitcher(){return `<div class="product-switch-wrap"><button class="app-switch" data-product-menu><span class="dots">⠿</span><span>${isSpm()?'安全態勢管理':'持續監控'}</span><span class="switch-caret">⌄</span></button>${state.productMenu?`<div class="product-menu"><button data-product="cm"><b>持續監控</b><small>第三方風險管理</small></button><button data-product="spm"><b>安全態勢管理</b><small>組織資安曝險與改善</small></button></div>`:''}</div>`}
const spmCards=()=>`<div class="spm-grid">
 <section class="spm-card rating-card"><header>Bitsight 安全評等 <select><option>90 天</option><option>30 天</option></select></header><div class="rating-main"><div><small>Saperix, Inc.</small><strong>420</strong><span class="delta">▼ 20</span><em>基礎</em></div><div class="rating-gauge"><i style="--score:20%"></i></div></div><button data-nav="spm-company-details">前往主要評等</button><a data-nav="spm-company-details">★ Saperix Lab</a><a data-nav="spm-rating-tree">檢視評等樹</a></section>
 <section class="spm-card"><header>供應商探索 <button>⋮</button></header><div class="donut"><b>246</b><span>未監控公司</span></div><ul class="legend"><li><i class="basic"></i>基礎評等 <b>29</b></li><li><i class="mid"></i>中階評等 <b>146</b></li><li><i class="advanced"></i>進階評等 <b>71</b></li></ul><footer>←　1 / 7　→</footer></section>
 <section class="spm-card"><header>我的評等變化 <select><option>30 天</option></select></header><div class="change-row"><b>Awesome Inc</b><span class="down">−10</span><strong>640</strong></div><div class="change-row"><b>Saperix, Inc.</b><span class="up">+10</span><strong>420</strong></div><button data-nav="spm-organization">所有 SPM 公司評等變化</button></section>
 <section class="spm-card"><header>新的高優先發現事項 <select><option>30 天</option></select></header><div class="finding-total"><span>所有 SPM 公司</span><strong>155</strong></div><div class="mini-bars">${[10,25,18,42,34,63,51,72,45,80,57,92].map(h=>`<i style="height:${h}%"></i>`).join('')}</div><h4>最多新發現事項</h4><p>Saperix, Inc. <b>152</b></p><p>Saperix Corporate <b>3</b></p></section>
 <section class="spm-card"><header>帳戶建議</header><p>已完成：4 / 5</p><div class="steps"><i></i><i></i><i></i><i></i><i class="open"></i></div><h3>自訂儀表板</h3><p>調整儀表板，突顯與工作流程最相關的資料。</p><button data-modal="edit-dashboard">開始使用</button></section>
 <section class="spm-card"><header>警示</header>${[['測試','Awesome Inc.'],['Bitsight 新發現事項警示','Saperix Corporate'],['測試','Saperix Corporate'],['Bitsight SSL 警示','Saperix, Inc.']].map(x=>`<div class="alert-line"><b>${x[0]}</b><small>2026/09/19 · ${x[1]}</small></div>`).join('')}<button data-nav="spm-alerts">檢視警示</button></section>
 <section class="spm-card"><header>基礎設施變更 <select><option>90 天</option></select></header><div class="finding-total"><span>所有 SPM 公司</span><strong>43</strong></div><h4>變更最多的公司</h4><p>Saperix Corporate（Azure）<b>40</b></p><p>Saperix, Inc. <b>2</b></p><p>WiFi 測試環境 <b>1</b></p></section>
 <section class="spm-card"><header>新的重大／嚴重發現事項 <select><option>90 天</option></select></header><div class="finding-total"><span>所有 SPM 公司</span><strong>1,063</strong></div><h4>最多新發現事項</h4><p>Saperix, Inc. <b>799</b></p><p>Awesome Inc <b>141</b></p><p>ABC-Test <b>62</b></p></section>
 <section class="spm-card"><header>協作收件匣</header><div class="inbox-item"><span>待處理</span><b>Saperix, Inc.</b><small>由資安團隊於 2026/08/27 傳送</small><p>請確認此發現事項與資產歸屬。</p></div><div class="inbox-item"><span>待處理</span><b>Saperix Corporate</b><small>由 Trevor LaBrie 於 2026/08/11 傳送</small></div></section>
</div>`;
function spmDashboard(){const stories=['Acronis 備份外掛程式權限提升弱點遭實際利用','Cisco ISE 驗證繞過弱點遭實際利用','Cisco 安全郵件閘道未經驗證命令執行','GitLab 路徑穿越可任意讀取檔案','ScreenConnect 未授權檔案傳輸與執行','JFrog Artifactory 驗證繞過與權限提升','Fortinet 防火牆與交換器管理遠端程式碼執行','Cisco 防火牆管理中心重大驗證繞過','Citrix NetScaler ADC 與 Gateway 驗證繞過','Adobe Commerce 與 Magento 範本引擎遠端程式碼執行'];return `${pagebar('我的公司儀表板','<button class="outline" data-modal="add-card">新增卡片</button><button class="outline" data-modal="edit-dashboard">編輯儀表板</button>')}<div class="content spm-page"><section class="panel spm-updates"><header>最新更新 <button data-toggle="updates">隱藏　⌃</button></header><div id="updates" class="spm-update-grid"><article><h2>△　10 項新興資安事件</h2><hr><h3>${stories[state.update]}</h3><div class="meta"><span><b>嚴重程度</b><br>CVSS 7.8</span><span><b>DVE 分數</b><br>10</span></div><h4>說明</h4><p>這項高嚴重性弱點可能讓低權限攻擊者提升權限並執行任意程式碼。建議立即確認暴露資產並套用修補程式。</p><div class="advisories">▮ 供應商公告　　▮ CISA 公告</div><small class="event-date">▣ 新增日期：2026/09/17</small><div class="update-foot"><button data-update="prev">←</button><span>${state.update+1} / 10</span><button data-nav="spm-threat-detection">檢視弱點偵測</button><button data-update="next">→</button></div></article><aside><h3>威脅情報新聞　<em>pulse</em></h3><hr><h3>新型惡意程式提供遠端桌面、竊密與錢包注入功能</h3><p>近期威脅情報摘要，協助資安團隊快速理解外部威脅與可能影響。</p><button data-toast="已開啟威脅情報摘要">繼續閱讀</button><footer>←　1 / 4　→</footer></aside></div></section>${spmCards()}</div>`}
function spmGeneric(){const cfg={
 'spm-company-details':['公司詳細資料',['公司','安全評等','評等變化','標籤','主要公司'],[['Saperix, Inc.','420','−20','主要公司','是'],['Saperix Corporate','690','+10','業務單位','否'],['Awesome Inc','640','−10','子公司','否']]],
 'spm-findings':['全部發現事項',['發現事項','公司','嚴重程度','最近發現','狀態'],[['過期 SSL 憑證','Saperix, Inc.','重大','2026/09/20','待處理'],['開放遠端管理連接埠','Awesome Inc','高','2026/09/19','調查中'],['DKIM 設定不完整','Saperix Corporate','中','2026/09/18','已指派']]],
 'spm-attack-surface':['攻擊面總覽',['資產','類型','公司','暴露狀態','最近觀察'],[['portal.example.com','網域','Saperix, Inc.','外部可見','今天'],['203.0.113.18','IP 位址','Awesome Inc','需檢視','昨天'],['Azure East Asia','雲端資產','Saperix Corporate','已確認','3 天前']]],
 'spm-action-plans':['行動計畫',['計畫','公司','負責人','到期日','進度'],[['修補外部弱點','Saperix, Inc.','資安團隊','2026/09/30','65%'],['強化郵件安全','Awesome Inc','IT 團隊','2026/10/05','30%']]],
 'spm-peer':['同業比較',['比較項目','本公司','同業中位數','百分位','趨勢'],[['安全評等','420','710','18%','下降'],['修補節奏','基礎','中階','25%','持平'],['網路安全','C','B','31%','改善中']]],
 'spm-collaboration':['協作',['主旨','公司','傳送者','日期','狀態'],[['確認資產歸屬','Saperix, Inc.','資安團隊','2026/08/27','待回覆'],['重大弱點改善證據','Saperix Corporate','Trevor LaBrie','2026/08/11','進行中']]],
 'spm-alerts':['警示',['警示','公司','日期','類型','狀態'],[['Bitsight 新發現事項警示','Saperix Corporate','2026/09/19','發現事項','未讀'],['SSL 憑證警示','Saperix, Inc.','2026/09/19','基礎設施','未讀'],['安全評等下降','Awesome Inc','2026/09/18','評等','已讀']]],
 'spm-reports':['報表',['報表名稱','範圍','上次產生','排程','操作'],[['公司風險摘要','主要公司','今天','每週','下載'],['發現事項趨勢','全部 SPM 公司','昨天','每月','檢視'],['高階主管摘要','Saperix, Inc.','7 天前','每月','下載']]],
 'spm-integrations':['整合',['整合服務','用途','狀態','上次同步','操作'],[['ServiceNow','工單與改善追蹤','已連線','10 分鐘前','管理'],['Microsoft Sentinel','SIEM 事件匯入','可設定','—','設定'],['Splunk','警示與事件串接','可設定','—','設定']]],
 'spm-rating-tree':['評等樹',['組織節點','安全評等','評等類型','資產數','關係'],[['Saperix, Inc.','420','主要評等','318','根節點'],['Saperix Corporate','690','自行發布','124','子公司'],['Saperix Lab','720','次要評等','46','業務單位']]],
 'spm-infrastructure-config':['基礎設施設定',['資產範圍','來源','狀態','上次變更','操作'],[['saperix.example','網域','已核准','2026/09/18','編輯'],['203.0.113.0/24','IP 範圍','已核准','2026/09/12','編輯'],['Azure 訂閱','雲端連接器','待確認','2026/09/20','檢視']]],
 'spm-risk-vectors':['風險面向',['風險面向','等級','發現事項','30 天變化','建議'],[['修補節奏','F','486','惡化','優先修補重大弱點'],['網路安全','C','163','持平','限制遠端管理服務'],['DNS 安全','B','27','改善','完成 DNSSEC 部署'],['Web 應用安全','D','92','惡化','檢查 TLS 與標頭']]],
 'spm-threat-detection':['弱點偵測',['弱點','DVE 分數','暴露資產','利用狀態','處置'],[['CVE-2026-87886','10','3','已遭利用','立即修補'],['CVE-2026-76460','10','1','已遭利用','隔離資產'],['CVE-2026-85706','9.8','5','概念驗證公開','升級 GitLab']]],
 'spm-assets':['基礎設施',['資產','資產類型','歸屬公司','來源','狀態'],[['portal.saperix.example','網域','Saperix, Inc.','DNS 探索','已確認'],['203.0.113.18','IPv4','Awesome Inc','掃描','需確認'],['mail.saperix.example','主機','Saperix Corporate','憑證','已確認']]],
 'spm-digital-footprint':['數位足跡',['數位資產','技術／服務','首次發現','風險','歸屬'],[['login.saperix.example','Microsoft IIS','2026/05/11','中','Saperix, Inc.'],['shop.saperix.example','Adobe Commerce','2026/07/08','高','待確認'],['api.saperix.example','NGINX','2026/08/16','低','Saperix Corporate']]],
 'spm-remediation':['改善追蹤',['改善事項','關聯發現','公司','目標日期','狀態'],[['更新 Acronis 外掛程式','CVE-2026-87886','Saperix, Inc.','2026/09/24','進行中'],['停用舊版 TLS','TLS 設定','Awesome Inc','2026/09/28','已指派'],['部署 DNSSEC','DNS 安全','Saperix Corporate','2026/10/10','規劃中']]],
 'spm-company-list':['我的公司清單',['公司','安全評等','關係','標籤','狀態'],[['Saperix, Inc.','420','主要公司','主要評等','監控中'],['Saperix Corporate','690','子公司','Azure','監控中'],['Awesome Inc','640','關聯公司','測試','監控中']]],
 'spm-subsidiaries':['子公司',['子公司','安全評等','評等變化','改善計畫','狀態'],[['Saperix Corporate','690','+10','進行中','需關注'],['Saperix Lab','720','0','未建立','穩定']]],
 'spm-assessments':['評估',['評估名稱','公司','完成度','到期日','狀態'],[['年度資安評估','Saperix, Inc.','82%','2026/10/15','進行中'],['雲端控制評估','Saperix Corporate','100%','2026/09/10','已完成']]],
 'spm-breach-intelligence':['資料外洩情報',['事件','公司','日期','資料類型','狀態'],[['憑證外洩訊號','Awesome Inc','2026/09/12','帳號憑證','調查中'],['公開儲存桶','Saperix Corporate','2026/08/29','設定資訊','已處理']]],
 'spm-badge':['Bitsight 徽章',['徽章','適用公司','目前評等','有效期限','狀態'],[['Security Rating Badge','Saperix, Inc.','420','2027/09/01','可發布']]],
 'spm-work-from-home':['居家辦公',['來源網路','裝置數','暴露服務','風險等級','最近觀察'],[['遠端辦公網路 A','34','5','中','今天'],['遠端辦公網路 B','18','1','低','昨天']]],
 'spm-cloud-infrastructure':['雲端基礎設施同步',['雲端帳戶','平台','資產數','上次同步','狀態'],[['Saperix Production','Microsoft Azure','124','10 分鐘前','已連線'],['Saperix Lab','AWS','46','2 小時前','已連線']]],
 'spm-probable-infrastructure':['可能的基礎設施',['資產','判斷依據','可信度','建議歸屬','狀態'],[['198.51.100.24','共同憑證','高','Saperix, Inc.','待確認'],['lab-saperix.example','DNS 關聯','中','Saperix Lab','待確認']]],
 'spm-third-party-assets':['第三方資產',['資產','服務提供者','產品','公司','風險'],[['login.microsoftonline.com','Microsoft','Entra ID','Saperix, Inc.','低'],['saperix.service-now.com','ServiceNow','ITSM','Saperix Corporate','中']]],
 'spm-forecasting':['評等預測',['情境','目前評等','預測評等','預計變化','時間範圍'],[['修補重大弱點','420','510','+90','90 天'],['改善 TLS 設定','420','450','+30','30 天']]],
 'spm-subsidiary-improvement':['子公司改善',['子公司','目前評等','目標評等','改善項目','進度'],[['Saperix Corporate','690','740','4','50%'],['Saperix Lab','720','760','2','25%']]],
 'spm-control-insights':['控制措施洞察',['控制措施','涵蓋風險','成熟度','缺口','建議'],[['弱點管理','修補節奏','基礎','3','建立修補 SLA'],['外部資產管理','攻擊面','中階','2','確認未知資產']]],
 'spm-risk-position':['風險位置',['比較群組','本公司百分位','同業中位數','評等差距','狀態'],[['全球軟體業','18%','710','−290','低於同業'],['亞太科技業','22%','690','−270','低於同業']]],
 'spm-infections':['感染事件',['事件','資產','惡意程式','首次發現','狀態'],[['殭屍網路通訊','203.0.113.18','未知下載器','2026/09/18','調查中'],['垃圾郵件活動','mail.saperix.example','Spam bot','2026/09/12','已處理']]],
 'spm-alert-settings':['警示設定',['規則名稱','觸發條件','公司範圍','通知方式','狀態'],[['重大評等下降','下降 40 分以上','所有 SPM 公司','電子郵件','啟用'],['新的重大發現','重大／嚴重','主要公司','電子郵件、Webhook','啟用'],['基礎設施變更','新增外部資產','Saperix, Inc.','電子郵件','暫停']]]};
 const fallback=[spmNames[state.page]||'安全態勢管理',['項目','公司','類型','更新時間','狀態'],[['示範項目 A','Saperix, Inc.','資安資訊','今天','需檢視'],['示範項目 B','Awesome Inc','監控資訊','昨天','已確認']]];const [title,headers,rows]=cfg[state.page]||fallback;const summaries={'spm-company-details':['3 家公司','420 主要評等','2 個組織節點'],'spm-findings':['1,063 項發現','155 項高優先','799 項屬於主要公司'],'spm-risk-vectors':['4 個風險面向','1 個改善中','2 個需優先處理'],'spm-threat-detection':['3 項重大弱點','9 個暴露資產','2 項遭實際利用'],'spm-attack-surface':['318 個資產','43 項近期變更','12 個需確認'],'spm-assets':['318 個資產','184 個網域','97 個 IP 位址'],'spm-digital-footprint':['246 個外部資產','17 項新發現','8 項高風險'],'spm-action-plans':['2 個行動計畫','6 個進行中工作','1 個即將到期'],'spm-remediation':['3 個改善事項','1 個進行中','0 個逾期'],'spm-peer':['第 18 百分位','同業中位數 710','評等差距 −290'],'spm-collaboration':['2 個待回覆','1 個進行中','0 個已逾期'],'spm-alerts':['3 個近期警示','2 個未讀','1 個已處理'],'spm-alert-settings':['2 個啟用規則','1 個暫停','2 種通知管道'],'spm-reports':['3 份報表','2 個排程','今天更新'],'spm-integrations':['1 個已連線','2 個可設定','10 分鐘前同步']}[state.page]||[rows.length+' 筆項目','資料已更新','可套用篩選'];return `${pagebar(title,'<button class="outline" data-toast="已建立示範篩選條件">篩選</button><button class="outline" data-modal="spm-action">動作⌄</button>')}<div class="content"><div class="spm-summary">${summaries.map((x,i)=>`<div><small>${['總覽','需關注','狀態'][i]}</small><strong>${x}</strong></div>`).join('')}</div></div><div class="content spm-list-page"><aside class="spm-filter"><h3>篩選</h3><input placeholder="搜尋篩選條件"><button>公司　⌄</button><button>嚴重程度　⌄</button><button>狀態　⌄</button><button>日期範圍　⌄</button></aside><section class="panel table-panel"><div class="table-tools"><b>${rows.length} 筆結果</b><span class="spacer"></span><input class="spm-search" placeholder="搜尋${title}"><button data-toast="示範資料已準備匯出">↓</button></div><div class="table-scroll"><table class="data-table"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map((v,i)=>`<td class="${i===0?'name':''}">${v}</td>`).join('')}</tr>`).join('')}</tbody></table></div></section></div>`}
function spmCompanyDetails(){return `${pagebar('Saperix, Inc. 公司詳細資料','<button class="outline" data-modal="reports">報表　▧</button><button class="outline" data-modal="spm-action">動作　⌄</button>')}<div class="content spm-company-page">
 <div class="company-overview-grid">
  <section class="panel company-rating"><h3>Bitsight 安全評等</h3><a>關於評等</a><div class="company-gauge"><span class="gauge-score">420<small>▰ 基礎</small></span></div><div class="gauge-range"><b>300</b><b>820</b></div><h4>前往主要評等</h4><button data-toast="已選擇主要評等公司">★ Saperix Lab</button><button data-nav="spm-rating-tree">檢視評等樹</button></section>
  <section class="panel incident-risk"><h3>資安事件風險</h3><div class="risk-block"><p><b>勒索軟體：</b>相較評等 750 以上的公司，您的風險高出 <strong>7.9 倍</strong>。 <a>深入了解</a></p><div class="risk-label"><span>高風險</span><span>您</span><span>低風險</span></div><div class="risk-scale"><i style="left:24%"></i></div></div><div class="risk-block"><p><b>資安事件：</b>相較評等 750 以上的公司，您的風險高出 <strong>4.8 倍</strong>。 <a>深入了解</a></p><div class="risk-label"><span>高風險</span><span>您</span><span>低風險</span></div><div class="risk-scale"><i style="left:27%"></i></div></div></section>
  <section class="panel company-info"><h3>公司資訊</h3><a>關於公司資訊</a><p>Saperix Technologies LLC 開發風險分析軟體解決方案。</p><dl><dt>訂閱</dt><dd>我的公司</dd><dt>關係</dt><dd>我的公司</dd><dt>監控者</dt><dd>262 家公司</dd><dt>搜尋者</dt><dd>22,729 位使用者</dd></dl><button data-modal="company-details">顯示詳細資料</button></section>
 </div>
 <div class="company-detail-grid">
  <section class="panel chart-detail"><header><h3>感染事件</h3><span>最近 90 天</span></header><div class="line-chart"><i></i><i></i><i></i><i></i><i></i></div><small>近期未發現新的感染事件</small></section>
  <section class="panel chart-detail"><header><h3>弱點</h3><span>最近 90 天</span></header><div class="vuln-bars">${[28,44,31,64,52,73,48,83,68,91].map(h=>`<i style="height:${h}%"></i>`).join('')}</div><small>重大與高嚴重性弱點趨勢</small></section>
  <section class="panel compliance-card"><h3>自行聲明合規</h3><p>此組織自行聲明已取得下列框架認證或符合相關法規。Bitsight 尚未獨立驗證。</p><div class="compliance-tags"><b>NIST CSF</b><b>ISO 27001</b><b>GDPR</b><b>HIPAA</b><b>PCI DSS</b></div><button data-toast="已開啟示範合規頁面">檢視合規網頁</button></section>
  <section class="panel mini-detail"><h3>受駭系統</h3><strong>0</strong><p>最近 90 天偵測到的受駭系統。</p><button data-nav="spm-findings">檢視詳細資料</button></section>
  <section class="panel mini-detail"><h3>改善策略</h3><strong>155</strong><p>高優先發現事項可納入改善計畫。</p><button data-nav="spm-findings">檢視發現事項</button><button data-nav="spm-action-plans">改善計畫</button></section>
  <section class="panel mini-detail"><h3>盡職調查</h3><strong>13</strong><p>需要檢視的安全控制與設定。</p><button data-nav="spm-findings">檢視詳細資料</button></section>
  <section class="panel network-card"><h3>網路足跡</h3><div><b>318</b><span>資產</span><b>184</b><span>網域</span><b>97</b><span>IP 位址</span></div><button data-nav="spm-assets">檢視基礎設施</button></section>
 </div>
 </div>`}
