const spmMenu=[
 ['儀表板','spm-dashboard','⌁'],
 ['組織',null,'⌘',[['公司管理','spm-organization'],['評等樹','spm-rating-tree'],['基礎設施設定','spm-infrastructure-config']]],
 ['發現事項',null,'▣',[['全部發現事項','spm-findings'],['風險面向','spm-risk-vectors'],['弱點偵測','spm-threat-detection']]],
 ['攻擊面',null,'◎',[['攻擊面總覽','spm-attack-surface'],['基礎設施','spm-assets'],['數位足跡','spm-digital-footprint']]],
 ['行動計畫',null,'✓',[['行動計畫','spm-action-plans'],['改善追蹤','spm-remediation']]],
 ['同業比較','spm-peer','♙'],['協作','spm-collaboration','✉'],
 ['警示',null,'⚑',[['警示','spm-alerts'],['警示設定','spm-alert-settings']]],
 ['報表','spm-reports','▤'],['整合','spm-integrations','♧']
];
const spmNames=Object.fromEntries(spmMenu.flatMap(m=>m[3]?m[3].map(x=>[x[1],x[0]]):[[m[1],m[0]]]));
function isSpm(){return state.page.startsWith('spm-')}
function spmParent(page){return spmMenu.find(m=>m[3]?.some(x=>x[1]===page))?.[0]||''}
function spmNav(){return spmMenu.map(m=>`<div class="menu-group"><button class="menu-main ${state.page===m[1]||m[3]?.some(x=>x[1]===state.page)?'active':''}" data-nav="${m[1]||''}" data-group="${m[0]}"><span class="icon">${m[2]}</span><span>${m[0]}</span>${m[3]?'<span class="chev">'+(state.open===m[0]?'⌄':'›')+'</span>':''}</button>${m[3]&&state.open===m[0]?`<div class="submenu">${m[3].map(([label,id])=>`<button class="${state.page===id?'active':''}" data-nav="${id}">${label}</button>`).join('')}</div>`:''}</div>`).join('')}
function productSwitcher(){return `<div class="product-switch-wrap"><button class="app-switch" data-product-menu><span class="dots">⠿</span><span>${isSpm()?'安全態勢管理':'持續監控'}</span><span class="switch-caret">⌄</span></button>${state.productMenu?`<div class="product-menu"><button data-product="cm"><b>持續監控</b><small>第三方風險管理</small></button><button data-product="spm"><b>安全態勢管理</b><small>組織資安曝險與改善</small></button></div>`:''}</div>`}
const spmCards=()=>`<div class="spm-grid">
 <section class="spm-card rating-card"><header>Bitsight 安全評等 <select><option>90 天</option><option>30 天</option></select></header><div class="rating-main"><div><small>Saperix, Inc.</small><strong>420</strong><span class="delta">▼ 20</span><em>基礎</em></div><div class="rating-gauge"><i style="--score:20%"></i></div></div><button data-nav="spm-organization">前往主要評等</button><a data-nav="spm-rating-tree">檢視評等樹</a></section>
 <section class="spm-card"><header>供應商探索 <button>⋮</button></header><div class="donut"><b>246</b><span>未監控公司</span></div><ul class="legend"><li><i class="basic"></i>基礎評等 <b>29</b></li><li><i class="mid"></i>中階評等 <b>146</b></li><li><i class="advanced"></i>進階評等 <b>71</b></li></ul><footer>←　1 / 7　→</footer></section>
 <section class="spm-card"><header>我的評等變化 <select><option>30 天</option></select></header><div class="change-row"><b>Awesome Inc</b><span class="down">−10</span><strong>640</strong></div><div class="change-row"><b>Saperix, Inc.</b><span class="up">+10</span><strong>420</strong></div><button data-nav="spm-organization">所有 SPM 公司評等變化</button></section>
 <section class="spm-card"><header>新的高優先發現事項 <select><option>30 天</option></select></header><div class="finding-total"><span>所有 SPM 公司</span><strong>155</strong></div><div class="mini-bars">${[10,25,18,42,34,63,51,72,45,80,57,92].map(h=>`<i style="height:${h}%"></i>`).join('')}</div><h4>最多新發現事項</h4><p>Saperix, Inc. <b>152</b></p><p>Saperix Corporate <b>3</b></p></section>
 <section class="spm-card"><header>帳戶建議</header><p>已完成：4 / 5</p><div class="steps"><i></i><i></i><i></i><i></i><i class="open"></i></div><h3>自訂儀表板</h3><p>調整儀表板，突顯與工作流程最相關的資料。</p><button data-modal="edit-dashboard">開始使用</button></section>
 <section class="spm-card"><header>警示</header>${[['測試','Awesome Inc.'],['Bitsight 新發現事項警示','Saperix Corporate'],['Bitsight SSL 警示','Saperix, Inc.']].map(x=>`<div class="alert-line"><b>${x[0]}</b><small>2026/09/19 · ${x[1]}</small></div>`).join('')}<button data-nav="spm-alerts">檢視警示</button></section>
 <section class="spm-card"><header>基礎設施變更 <select><option>90 天</option></select></header><div class="finding-total"><span>所有 SPM 公司</span><strong>43</strong></div><h4>變更最多的公司</h4><p>Saperix Corporate（Azure）<b>40</b></p><p>Saperix, Inc. <b>2</b></p><p>WiFi 測試環境 <b>1</b></p></section>
 <section class="spm-card"><header>新的重大／嚴重發現事項 <select><option>90 天</option></select></header><div class="finding-total"><span>所有 SPM 公司</span><strong>1,063</strong></div><h4>最多新發現事項</h4><p>Saperix, Inc. <b>799</b></p><p>Awesome Inc <b>141</b></p><p>ABC-Test <b>62</b></p></section>
 <section class="spm-card"><header>協作收件匣</header><div class="inbox-item"><span>待處理</span><b>Saperix, Inc.</b><small>由資安團隊於 2026/08/27 傳送</small><p>請確認此發現事項與資產歸屬。</p></div><div class="inbox-item"><span>待處理</span><b>Saperix Corporate</b><small>由 Trevor LaBrie 於 2026/08/11 傳送</small></div></section>
</div>`;
function spmDashboard(){const stories=['Acronis 備份外掛程式權限提升弱點遭實際利用','Cisco ISE 驗證繞過弱點遭實際利用','GitLab 路徑穿越可任意讀取檔案'];return `${pagebar('我的公司儀表板','<button class="outline" data-modal="add-card">新增卡片</button><button class="outline" data-modal="edit-dashboard">編輯儀表板</button>')}<div class="content spm-page"><section class="panel spm-updates"><header>最新更新 <button data-toggle="updates">隱藏　⌃</button></header><div id="updates" class="spm-update-grid"><article><h2>△　10 項新興資安事件</h2><hr><h3>${stories[state.update]}</h3><div class="meta"><span><b>嚴重程度</b><br>CVSS 7.8</span><span><b>DVE 分數</b><br>10</span></div><h4>說明</h4><p>這項高嚴重性弱點可能讓低權限攻擊者提升權限並執行任意程式碼。建議立即確認暴露資產並套用修補程式。</p><div class="advisories">▮ 供應商公告　　▮ CISA 公告</div><div class="update-foot"><button data-update="prev">←</button><span>${state.update+1} / 3</span><button data-nav="spm-threat-detection">檢視弱點偵測</button><button data-update="next">→</button></div></article><aside><h3>威脅情報新聞　<em>pulse</em></h3><hr><h3>新型惡意程式提供遠端桌面、竊密與錢包注入功能</h3><p>近期威脅情報摘要，協助資安團隊快速理解外部威脅與可能影響。</p><button data-toast="已開啟威脅情報摘要">繼續閱讀</button><footer>←　1 / 4　→</footer></aside></div></section>${spmCards()}</div>`}
function spmGeneric(){const cfg={
 'spm-organization':['公司管理',['公司','安全評等','評等變化','標籤','主要公司'],[['Saperix, Inc.','420','−20','主要公司','是'],['Saperix Corporate','690','+10','業務單位','否'],['Awesome Inc','640','−10','子公司','否']]],
 'spm-findings':['全部發現事項',['發現事項','公司','嚴重程度','最近發現','狀態'],[['過期 SSL 憑證','Saperix, Inc.','重大','2026/09/20','待處理'],['開放遠端管理連接埠','Awesome Inc','高','2026/09/19','調查中'],['DKIM 設定不完整','Saperix Corporate','中','2026/09/18','已指派']]],
 'spm-attack-surface':['攻擊面總覽',['資產','類型','公司','暴露狀態','最近觀察'],[['portal.example.com','網域','Saperix, Inc.','外部可見','今天'],['203.0.113.18','IP 位址','Awesome Inc','需檢視','昨天'],['Azure East Asia','雲端資產','Saperix Corporate','已確認','3 天前']]],
 'spm-action-plans':['行動計畫',['計畫','公司','負責人','到期日','進度'],[['修補外部弱點','Saperix, Inc.','資安團隊','2026/09/30','65%'],['強化郵件安全','Awesome Inc','IT 團隊','2026/10/05','30%']]],
 'spm-peer':['同業比較',['比較項目','本公司','同業中位數','百分位','趨勢'],[['安全評等','420','710','18%','下降'],['修補節奏','基礎','中階','25%','持平'],['網路安全','C','B','31%','改善中']]],
 'spm-collaboration':['協作',['主旨','公司','傳送者','日期','狀態'],[['確認資產歸屬','Saperix, Inc.','資安團隊','2026/08/27','待回覆'],['重大弱點改善證據','Saperix Corporate','Trevor LaBrie','2026/08/11','進行中']]],
 'spm-alerts':['警示',['警示','公司','日期','類型','狀態'],[['Bitsight 新發現事項警示','Saperix Corporate','2026/09/19','發現事項','未讀'],['SSL 憑證警示','Saperix, Inc.','2026/09/19','基礎設施','未讀'],['安全評等下降','Awesome Inc','2026/09/18','評等','已讀']]],
 'spm-reports':['報表',['報表名稱','範圍','上次產生','排程','操作'],[['公司風險摘要','主要公司','今天','每週','下載'],['發現事項趨勢','全部 SPM 公司','昨天','每月','檢視'],['高階主管摘要','Saperix, Inc.','7 天前','每月','下載']]],
 'spm-integrations':['整合',['整合服務','用途','狀態','上次同步','操作'],[['ServiceNow','工單與改善追蹤','已連線','10 分鐘前','管理'],['Microsoft Sentinel','SIEM 事件匯入','可設定','—','設定'],['Splunk','警示與事件串接','可設定','—','設定']]]};
 const fallback=[spmNames[state.page]||'安全態勢管理',['項目','公司','類型','更新時間','狀態'],[['示範項目 A','Saperix, Inc.','資安資訊','今天','需檢視'],['示範項目 B','Awesome Inc','監控資訊','昨天','已確認']]];const [title,headers,rows]=cfg[state.page]||fallback;return `${pagebar(title,'<button class="outline" data-toast="已建立示範篩選條件">篩選</button><button class="outline" data-modal="spm-action">動作⌄</button>')}<div class="content spm-list-page"><aside class="spm-filter"><h3>篩選</h3><input placeholder="搜尋篩選條件"><button>公司　⌄</button><button>嚴重程度　⌄</button><button>狀態　⌄</button><button>日期範圍　⌄</button></aside><section class="panel table-panel"><div class="table-tools"><b>${rows.length} 筆結果</b><span class="spacer"></span><input class="spm-search" placeholder="搜尋${title}"><button data-toast="示範資料已準備匯出">↓</button></div><div class="table-scroll"><table class="data-table"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map((v,i)=>`<td class="${i===0?'name':''}">${v}</td>`).join('')}</tr>`).join('')}</tbody></table></div></section></div>`}
