const vendorState={company:1,findingQuery:'',severity:'全部',findingStrict:true,assessmentFilterOpen:'',assessmentFilters:{'已對照問題':['已對照問題']}};
const assessmentFilterGroups=[
  ['區段',['存取控制（AC）','認知與訓練（AT）','稽核與責任歸屬（AU）','評估、授權與監控（CA）','組態管理（CM）','應變計畫（CP）','識別與驗證（IA）','事件回應（IR）','維護（MA）','媒體保護（MP）','實體與環境保護（PE）','規劃（PL）','計畫管理（PM）','人員安全（PS）','個人識別資訊處理與透明度（PT）','風險評估（RA）','系統與服務取得（SA）','系統與通訊保護（SC）','系統與資訊完整性（SI）','供應鏈風險管理（SR）']],
  ['旗標',['已加旗標的問題','未加旗標的問題']],
  ['等級',['A','B','C','D','F','N/A']],
  ['風險面向',[
    ['受入侵系統',['殭屍網路感染','垃圾郵件傳播','惡意程式伺服器','未經請求的通訊','可能遭利用']],
    ['安全實務',['SPF','DKIM','DMARC','SSL 憑證','SSL 設定','開放埠','網頁應用程式安全','重大弱點管理','不安全系統','DNSSEC','伺服器軟體','桌面軟體','行動軟體','Web Application Headers']],
    ['使用者行為',['檔案分享']],
    ['公開揭露',['資安事件']]
  ]],
  ['已對照問題',['已對照問題','未對照問題']]
];
const vendorFindings=[['開放不安全通訊埠','網路安全','高','3','2026/09/12'],['過期的 TLS 憑證','安全工程','中','6','2026/09/10'],['不安全的 SSL 設定','安全工程','中','11','2026/09/08'],['已知遭利用弱點','修補節奏','重大','2','2026/09/05'],['缺少 SPF 記錄','電子郵件安全','低','4','2026/08/29']];
const vectorRows=[['殭屍網路感染','A','良好','0'],['垃圾郵件傳播','A','良好','0'],['惡意軟體伺服器','B','良好','1'],['非預期通訊','B','良好','2'],['安全工程','C','普通','17'],['修補節奏','C','普通','24'],['網路安全','D','待改善','9']];
function companyBand(){return ''}
function ratingChart(){return `<div class="rating-chart"><div class="chart-y"><span>820</span><span>760</span><span>700</span><span>640</span></div><svg viewBox="0 0 800 190" preserveAspectRatio="none" aria-label="安全評等趨勢圖"><path d="M0 75 L100 70 L190 82 L285 65 L370 72 L455 54 L540 60 L625 44 L710 50 L800 36" fill="none" stroke="#2274a5" stroke-width="4"/><path d="M0 150 H800 M0 100 H800 M0 50 H800" stroke="#dce6ed"/></svg><div class="chart-x"><span>2025/09</span><span>2026/01</span><span>2026/05</span><span>2026/09</span></div></div>`}
function vendorOverview(){const c=companies[vendorState.company];return `${pagebar(`${e(c[0])}總覽`,`<button class="primary-action" data-toast="已開啟供應商存取選單">供應商存取⌄</button><button class="header-link" data-toast="已開啟報表與評估">報表與評估　▤</button><button class="header-link" data-toast="已開啟公司動作">動作⌄</button>`)}<div class="overview-shell"><main class="overview-main"><section class="panel ai-summary"><h3>✦ 供應商風險 AI 摘要</h3><button class="outline" data-toast="已產生示範摘要">產生摘要</button></section><div class="overview-cards"><section class="panel rating-gauge-card"><h2>Bitsight 安全評等</h2><div class="semi-gauge"><b>${c[1]}</b><small>≡　進階</small></div><button data-nav="tree">查看評等樹</button><p><span>▲ 較佳</span>　優於相似公司</p></section><section class="panel incident-risk"><h2>資安事件風險</h2><p>此公司的<b>勒索軟體風險相近</b>於評等 750 以上的公司。</p><div class="riskbar"><span>高風險</span><i></i><span>你</span><span>低風險</span></div><p>此公司的<b>資安事件風險相近</b>於評等 750 以上的公司。</p><div class="riskbar"><span>高風險</span><i></i><span>你</span><span>低風險</span></div></section><section class="panel news-card"><h2>威脅情報新聞</h2><small>Pulse　·　2026/09/14</small><h3>五個組織任命新的資訊安全長</h3><button data-nav="threat">繼續閱讀</button><div class="news-pager">←　1 / 5　→</div></section></div><section class="panel changes-card"><div class="vendor-card-head"><h2>安全評等變化</h2><select><option>過去 1 年</option></select></div>${ratingChart()}</section></main><aside class="company-info"><h2>公司資訊</h2><p>◎　<a>example.com</a></p><p>▱　${e(c[0])} 為本教學範例使用的虛構公司，用來展示公司總覽與安全評等功能。</p><p>▦　金融 ＞ 金融服務</p><p>◉　7,322 個 IP 位址</p><p>⌕　受到 12 家公司監控</p><hr><h3>關係 <button>編輯</button></h3><p>♙　未指派</p><p>▣　未設定層級</p><p>⌘　持續監控</p></aside></div>`}
function vectorsView(){const company=e(companies[vendorState.company][0]);return spmRiskVectorsV2().replaceAll('Saperix, Inc.',company).replaceAll('範例商業銀行',company)}
function findingsView(){const all=vendorFindings.filter(r=>(vendorState.severity==='全部'||r[2]===vendorState.severity)&&(!vendorState.findingQuery||r.join(' ').includes(vendorState.findingQuery))),rows=vendorState.findingStrict?[]:all;const groups=['評等影響','等級','風險面向','發現事項影響','發現事項嚴重程度','首次與最近觀察','威脅洞察'];return `${pagebar(`發現事項：${e(companies[vendorState.company][0])}`,`<button class="primary-action">供應商存取⌄</button><button class="header-link">報表與評估　▤</button><button class="header-link">動作⌄</button>`)}<div class="finding-layout"><aside class="finding-filter"><div class="filter-top"><button class="active">▽ 篩選</button><button>▥</button><button>♧</button><span>‹</span></div><input id="vendorFindingSearch" value="${e(vendorState.findingQuery)}" placeholder="搜尋篩選條件…"><div class="active-filter-head"><b>使用中的篩選</b><button data-findings-clear>清除全部</button></div>${vendorState.findingStrict?'<div class="active-chips"><span>嚴重發現事項　×</span><span>重大發現事項　×</span><span>影響風險面向等級　×</span></div>':''}${groups.map(g=>`<button class="finding-filter-row">${g}<span>⌄</span></button>`).join('')}<div class="finding-filter-foot"><button>建立檢視</button><button disabled>儲存變更</button></div></aside><main class="finding-results"><div class="finding-view-chip">${vendorState.findingStrict?'嚴重與重大發現事項':'全部發現事項'}</div><div class="table-tools"><span>${rows.length} 筆發現事項</span><button disabled>供應商存取（0/10）</button><span class="spacer"></span><button>⌕</button><button>↓⌄</button><button>⛶</button></div><table class="data-table"><thead><tr><th>風險面向</th><th>發現事項識別碼</th><th>詳細資料</th><th>首次觀察</th><th>最近觀察 ↓</th><th>影響</th></tr></thead><tbody>${rows.map((r,i)=>`<tr data-finding-row><td>${r[1]}</td><td class="name">F-${1000+i}</td><td>${r[0]}</td><td>2026/08/01</td><td>${r[4]}</td><td>${r[2]}</td></tr>`).join('')}</tbody></table>${rows.length?'':'<div class="finding-empty">⌁</div>'}<div class="pager"><button>100⌄</button><span>0 - ${rows.length}，共 ${rows.length} 筆</span><span class="spacer"></span><button>‹</button><span>${rows.length?'1 / 1':'0 / 0'}</span><button>›</button></div></main></div>`}
function infrastructureView(){const filters=['資產類型','發現事項數量','標籤','狀態','地理區域','是否為萬用字元','資產重要性','雲端','產品'];return `${pagebar(`基礎設施：${e(companies[vendorState.company][0])}`)}<div class="infra-tabbar"><button class="active">資產</button></div><div class="infra-layout"><aside class="fi-filter"><div class="filter-top"><button class="active">▽ 篩選</button><button>▥</button><button>♧</button><span>‹</span></div><input placeholder="搜尋篩選條件…">${filters.map(x=>`<button class="finding-filter-row">${x}<span>⌄</span></button>`).join('')}<div class="finding-filter-foot"><button>建立檢視</button></div></aside><main class="infra-results"><div class="table-tools"><span>0 列</span><button disabled>查看發現事項（0）</button><button disabled>監控資產（0/500）</button><span class="spacer"></span><button>⌕</button><button>↓</button><button>⛶</button></div><table class="data-table"><thead><tr><th>資產</th><th>資產類型</th><th>標籤</th><th>重要性　ⓘ ↓</th><th>已監控　ⓘ</th><th>國家／地區</th></tr></thead></table><div class="finding-empty">▽</div><div class="pager"><button>30⌄</button><span>0 - 0，共 0 筆</span><span class="spacer"></span><button>‹</button><span>0 / 0</span><button>›</button></div></main></div>`}
function frameworkView(){return `${pagebar(`框架情報：${e(companies[vendorState.company][0])}`,`<button class="primary-action" data-toast="已建立新評估草稿">✦　新增評估</button>`)}<div class="fi-layout"><aside class="fi-filter"><div class="filter-top"><button class="active">▽ 篩選</button><button>▥</button><button>♧</button><span>‹</span></div><input placeholder="搜尋篩選條件…"><div class="active-filter-head"><b>使用中的篩選</b><button>清除全部</button></div><div class="active-chips"><span>已完成　×</span></div>${['狀態','使用者','日期','框架'].map((x,i)=>`<button class="finding-filter-row">${x}${i===0?'<em>1 ×</em>':''}<span>⌄</span></button>`).join('')}<div class="finding-filter-foot"><button>建立檢視</button><button disabled>儲存變更</button></div></aside><main class="fi-results"><div class="finding-view-chip">已完成的評估 ●</div><div class="table-tools"><span>0 列</span><span class="spacer"></span><button>⌕</button><button>⛶</button></div><table class="data-table"><thead><tr><th>評估名稱</th><th>框架</th><th>狀態</th><th>完成日期 ↓</th><th>使用者</th><th>符合度</th></tr></thead></table><div class="fi-empty"><span>▤⌕</span><p>找不到結果</p></div><div class="pager"><button>30⌄</button><span>0 - 0，共 0 筆</span><span class="spacer"></span><button>‹</button><span>0 / 0</span><button>›</button></div></main></div>`}
function instantView(){return `${pagebar(`即時洞察：${e(companies[vendorState.company][0])}`,`<button class="outline" disabled>▤　下載 PDF</button><button class="outline" disabled>↶　清除</button>`)}<div class="instant-page"><div class="banner">ⓘ　生成式 AI 功能產生的所有內容均不提供任何保證；使用者應自行驗證其正確性。</div><section class="panel instant-upload"><p>若要開始，請在下方上傳供應商的 SOC 報告。上傳後，點選「分析」以取得即時洞察。</p><label class="dropzone"><input type="file" id="insightFile" accept=".pdf"><b>↥</b><strong>拖放檔案或 <u>選擇檔案</u></strong><small>檔案大小上限為 10 MB</small></label><button class="analyze" data-analyze disabled>✦　分析</button></section></div>`}
function assessmentFilterOptions(name,options){const selected=vendorState.assessmentFilters[name]||[];const option=(value)=>`<label><input type="checkbox" data-assessment-filter-option="${e(name)}" value="${e(value)}" ${selected.includes(value)?'checked':''}> <span>${e(value)}</span></label>`;if(name==='風險面向')return options.map(([heading,items])=>`<h4>${heading}</h4>${items.map(option).join('')}`).join('');return options.map(option).join('')}
function vendorAssessmentsView(){const rows=[['存取控制（AC）','網域驗證','AC-4(17)','唯一識別並驗證資訊傳輸的來源與目的地。'],['存取控制（AC）','程式碼執行權限等級','AC-6(8)','防止軟體以高於指定權限的層級執行。'],['存取控制（AC）','遠端存取','AC-17','建立、記錄及監控遠端存取連線。']];const filters=assessmentFilterGroups.map(([name,options])=>{const count=(vendorState.assessmentFilters[name]||[]).length,open=vendorState.assessmentFilterOpen===name;return `<div class="assessment-filter-group"><button class="finding-filter-row" data-assessment-filter-group="${e(name)}" aria-expanded="${open}">${name}${count?`<em>${count} ×</em>`:''}<span>${open?'⌃':'⌄'}</span></button>${open?`<div class="assessment-filter-options">${name==='區段'?`<div class="assessment-filter-selected">${count} Selected</div><input class="assessment-option-search" placeholder="Search">`:''}${assessmentFilterOptions(name,options)}</div>`:''}</div>`}).join('');return `${pagebar(`NIST CSF：${e(companies[vendorState.company][0])}`,`<button class="outline">▤　下載 PDF</button><button class="primary-action">啟用供應商存取</button>`)}<div class="assessment-layout"><aside class="fi-filter"><div class="filter-top"><button class="active">▽ 篩選</button><button>♧</button><span>‹</span></div><input placeholder="搜尋篩選條件…"><div class="active-filter-head"><b>使用中的篩選</b><button data-assessment-clear>清除全部</button></div>${Object.values(vendorState.assessmentFilters).some(v=>v.length)?'<div class="active-chips"><span>已套用篩選條件　×</span></div>':''}<div class="assessment-filter-scroll filter-scroll">${filters}</div><div class="finding-filter-foot"><button>建立檢視</button></div></aside><main class="assessment-results"><div class="table-tools"><span>109 列</span><span class="spacer"></span><button>⌕</button><button>↓</button><button>⛶</button></div><table class="data-table assessment-table"><thead><tr><th>區段<br>子區段</th><th>問題編號</th><th>問題</th><th>風險面向</th></tr></thead><tbody>${rows.map(r=>`<tr data-assessment-detail><td><b>${r[0]}</b><br><small>${r[1]}</small></td><td>${r[2]}</td><td>${r[3]}</td><td><span class="grade grade-A">A</span> 殭屍網路感染<br><span class="grade grade-A">A</span> 檔案分享<br><span class="grade grade-A">A</span> 不安全系統</td></tr>`).join('')}</tbody></table><div class="pager"><button>50⌄</button><span>1 - 50，共 109 筆（從 1,010 筆篩選）</span><span class="spacer"></span><button>‹</button><span>1 / 3</span><button>›</button></div></main></div>`}
function threatView(){const filter=['威脅群組','威脅類型','產業','地理區域','發現事項','威脅活動'];return `${pagebar(`威脅洞察：${e(companies[vendorState.company][0])}`)}<section class="threat-intro"><h2>主動偵測並回應新興威脅</h2><div><article><b>威脅感知</b><p>掌握活躍威脅組織的資訊，以預測潛在威脅並強化組織防禦策略。</p></article><article><b>目標識別</b><p>識別哪些威脅組織鎖定你的產業，評估風險並排定最相關的防護措施。</p></article><article><b>戰術、技術與程序（TTP）</b><p>分析威脅行為，了解其運作方式並改善偵測與回應能力。</p></article></div></section><div class="threat-layout"><aside class="fi-filter"><div class="filter-top"><button class="active">▽ 篩選</button><button>▥</button><button>♧</button><span>‹</span></div><input placeholder="搜尋篩選條件…">${filter.map((x,i)=>`<div class="threat-filter-group"><button>${x}<span>${i<2?'⌃':'⌄'}</span></button>${i===1?'<label><input type="checkbox"> APT</label><label><input type="checkbox"> 勒索軟體</label>':''}</div>`).join('')}<div class="finding-filter-foot"><button>建立檢視</button></div></aside><main class="threat-results"><div class="table-tools"><span>0 列</span><span class="spacer"></span><button>⌕</button><button>⛶</button></div><table class="data-table"><thead><tr><th>威脅群組</th><th>類型</th><th>地理區域</th><th>產業</th><th>發現事項 ↓</th><th>不良／警告發現事項</th><th>威脅活動</th></tr></thead></table><div class="finding-empty">⌁</div></main></div>`}
function treeView(){const nodes=[['範例世紀保險','780'],['範例金融控股','790'],['範例期貨公司','760'],['範例人壽保險','800']];return `${pagebar('評等樹：範例物業管理集團')}<div class="tree-toolbar"><input placeholder="搜尋"><button>ⓘ</button><button class="outline" data-toast="已收合所有節點">全部收合</button><span>縮放　<input type="range" min="50" max="150" value="100">　◎</span></div><div class="ratings-canvas"><div class="rt-node rt-parent"><span>▣</span><b>範例物業管理集團</b><i>🔒</i><em>⌄</em></div><div class="rt-count">10⌃</div><div class="rt-node rt-focus"><span>▣</span><b>${e(companies[vendorState.company][0])}</b><em>⌃</em></div><div class="rt-count second">9⌃</div><div class="rt-branches">${nodes.map((n,i)=>`<button class="rt-node" data-tree-node style="--row:${i}"><span>▣</span><b>${n[0]}</b><i>🔒</i><em>⌄</em></button>`).join('')}</div></div>`}
function remediationView(){return `${pagebar(`改善追蹤：${e(companies[vendorState.company][0])}`,`<button class="primary-action">供應商存取⌄</button><button class="header-link">報表與評估　▤</button><button class="header-link">動作⌄</button>`)}<div class="remediation-empty"><span>⌁</span></div>`}
function vendorView(page){return page==='vendor-overview'?vendorOverview():page==='framework'?frameworkView():page==='instant'?instantView():page==='assessments'?vendorAssessmentsView():page==='vectors'?vectorsView():page==='findings'?findingsView():page==='threat'?threatView():page==='tree'?treeView():page==='remediation'?remediationView():infrastructureView()}
document.addEventListener('click',event=>{const x=event.target.closest('[data-vendor-company],[data-vector-row],[data-finding-row],[data-framework-row],[data-assessment-detail],[data-tree-node],[data-remedy]');if(!x)return;if(x.hasAttribute('data-vendor-company')){vendorState.company=(vendorState.company+1)%companies.length;render()}else if(x.hasAttribute('data-vector-row'))showToast('已開啟風險面向詳情');else if(x.hasAttribute('data-finding-row'))showToast('已開啟發現事項詳情');else if(x.hasAttribute('data-framework-row'))showToast('已開啟框架控制措施');else if(x.hasAttribute('data-assessment-detail'))showToast('已開啟評估進度');else if(x.hasAttribute('data-tree-node'))showToast('已選取評等樹節點');else showToast('已開啟改善要求詳情')});
document.addEventListener('input',event=>{if(event.target.id==='vendorFindingSearch'){vendorState.findingQuery=event.target.value;const p=event.target.selectionStart;render();const i=document.getElementById('vendorFindingSearch');i.focus();i.setSelectionRange(p,p)}});
document.addEventListener('change',event=>{if(event.target.id==='vendorSeverity'){vendorState.severity=event.target.value;render()}if(event.target.matches('[data-rating-period]'))showToast(`已切換為 ${event.target.value}`)});
document.addEventListener('change',event=>{if(event.target.id==='insightFile'){const b=document.querySelector('[data-analyze]');if(b)b.disabled=!event.target.files.length}});
document.addEventListener('click',event=>{if(event.target.closest('[data-findings-clear]')){vendorState.findingStrict=false;render()}});
document.addEventListener('click',event=>{const group=event.target.closest('[data-assessment-filter-group]');if(group){const y=window.scrollY;vendorState.assessmentFilterOpen=vendorState.assessmentFilterOpen===group.dataset.assessmentFilterGroup?'':group.dataset.assessmentFilterGroup;render();window.scrollTo(0,y);return}if(event.target.closest('[data-assessment-clear]')){vendorState.assessmentFilters={};render()}});
document.addEventListener('change',event=>{if(!event.target.matches('[data-assessment-filter-option]'))return;const name=event.target.dataset.assessmentFilterOption;const current=new Set(vendorState.assessmentFilters[name]||[]);event.target.checked?current.add(event.target.value):current.delete(event.target.value);vendorState.assessmentFilters[name]=[...current];render()});

function vendorOverview(){
  const c=companies[vendorState.company];
  const risks=[['殭屍網路感染','A','基準','0'],['垃圾郵件傳播','A','基準','0'],['未經請求的通訊','A','基準','0'],['可能遭利用','A','基準','0'],['TLS/SSL 憑證','A','基準','49'],['TLS/SSL 設定','A','基準','107'],['開放埠','A','基準','79'],['重大弱點管理','A','基準','0'],['檔案分享','A','基準','0'],['不安全系統','A','基準','0'],['惡意程式伺服器','A','—','0'],['SPF 網域','A','—','3'],['DKIM 記錄','A','—','4'],['DMARC','A','—','1'],['網頁應用程式安全','A','—','61'],['DNSSEC*','A','—','2'],['伺服器軟體','A','—','14'],['資安事件','A','—','0'],['桌面軟體','N/A','—','0'],['行動軟體','N/A','—','0'],['Web Application Headers*','N/A','—','0']];
  const riskTable=risks.map((r,i)=>`<tr><td>${r[0]}</td><td><span class="mini-trend">${i%4===0?'▁▂▂▃▃':'▂▂▂▂▂'}</span></td><td><span class="overview-grade ${r[1]==='A'?'good':'neutral'}">${r[1]}</span></td><td>${r[2]}</td><td>${r[3]}</td></tr>`).join('');
  return `${pagebar(`${e(c[0])}總覽`,`<button class="primary-action" data-toast="已開啟供應商存取選單">供應商存取⌄</button><button class="header-link" data-toast="已開啟報表與評估">報表與評估　▤</button><button class="header-link" data-toast="已開啟公司動作">動作⌄</button>`)}<div class="overview-shell"><main class="overview-main">
  <section class="panel ai-summary"><h3>✦ 供應商風險 AI 摘要</h3><button class="outline" data-toast="已產生示範摘要">產生摘要</button></section>
  <div class="overview-cards"><section class="panel rating-gauge-card"><h2>Bitsight 安全評等</h2><div class="semi-gauge"><b>${c[1]}</b><small>≡　進階</small></div><button data-nav="tree">查看評等樹</button><p><span>▲ 較佳</span>　優於相似公司</p></section><section class="panel incident-risk"><h2>資安事件風險</h2><p>此公司的<b>勒索軟體風險相近</b>於評等 750 以上的公司。</p><div class="riskbar"><span>高風險</span><i></i><span>你</span><span>低風險</span></div><p>此公司的<b>資安事件風險相近</b>於評等 750 以上的公司。</p><div class="riskbar"><span>高風險</span><i></i><span>你</span><span>低風險</span></div></section><section class="panel news-card"><h2>威脅情報新聞</h2><small>Pulse　·　2026/09/20</small><h3>本週資安領導者與重大資料外洩事件摘要</h3><button data-nav="threat">繼續閱讀</button><div class="news-pager">←　1 / 5　→</div></section></div>
  <div class="overview-mini-cards"><section class="panel overview-stat"><h2>資安事件</h2><b>0</b><p>過去 30 天的重大事件</p></section><section class="panel overview-stat"><h2>警示 <button data-nav="portfolio-alerts">前往警示</button></h2><b>0</b><p>過去 30 天的警示</p></section></div>
  <section class="panel changes-card"><div class="vendor-card-head"><h2>安全評等變化</h2><select><option>過去 1 年</option></select></div><div class="rating-change-summary"><span>最高：2025/12/11　<b>810</b></span><span>最低：2025/09/01　<b>770</b></span><span>2026 年變化　<b>6</b></span></div>${ratingChart()}</section>
  <section class="panel overview-wide-card"><h2>資安事件風險</h2><p>13 個風險面向中的不良表現會增加發生資安事件的可能性，良好表現則代表事件風險較低。依據 Marsh McLennan 資安事件關聯研究，目前 <b>0 / 13</b> 個風險面向提高了資安事件的可能性。</p></section>
  <section class="panel overview-wide-card"><h2>風險面向</h2><div class="overview-table-wrap"><table class="overview-risk-table"><thead><tr><th>風險面向</th><th>12 個月趨勢</th><th>等級</th><th>資安事件風險</th><th>發現事項</th></tr></thead><tbody>${riskTable}</tbody></table></div><small>* 目前不影響安全評等</small></section>
  <div class="overview-lower-grid"><section class="panel asset-map-card"><div class="vendor-card-head"><h2>資產分布</h2><button>查看所有資產</button></div><p>資產數量最多的國家／地區</p><div class="asset-map-layout"><div><p><b>台灣（TW）</b><span>99%</span></p><p><b>美國（US）</b><span>&lt; 1%</span></p><strong>1,321 個資產與國家／地區相關聯</strong></div><div class="world-map-placeholder">世界地圖示意</div></div></section>
  <section class="panel exposed-card"><h2>暴露弱點</h2><div class="exposed-donut"><b>27</b></div><ul><li><b>0</b> 暴露已確認</li><li><b>26</b> 暴露很可能</li><li><b>1</b> 暴露可能</li></ul></section><section class="panel fourth-card"><h2>第四方</h2><div><b>36</b><span>服務提供者</span><b>140</b><span>產品</span></div></section>
  <section class="panel exposure-trend"><h2>Exposure Trend</h2><div class="exposure-trend-value"><b>＋1</b><span>Vulnerabilities</span><em>Last 14 Days</em></div></section><section class="panel median-card"><h2>服務提供者評等中位數</h2><div class="median-rating"><b>680</b><div class="median-scale"><span>300</span><i></i><span>820</span></div></div></section>
  <section class="panel severity-card"><div class="vendor-card-head"><h2>CVSS 弱點嚴重程度</h2><button>查看全部</button></div>${[['重大',4],['高',11],['中',12],['低',0]].map(([n,v])=>`<div class="severity-row"><span>${n}</span><i style="--value:${v}"></i><b>${v}</b></div>`).join('')}</section><section class="panel provider-dist"><h2>服務提供者評等分布</h2>${[['基礎',6],['中階',23],['進階',7]].map(([n,v])=>`<div class="provider-bar"><span>${n}</span><i style="--value:${v}"></i><b>${v}</b></div>`).join('')}</section></div>
  </main><aside class="company-info"><h2>公司資訊</h2><p>◎　<a>example.com</a></p><p>▱　${e(c[0])} 為本教學範例使用的虛構公司，用來展示公司總覽與安全評等功能。</p><p>▦　金融 ＞ 金融服務</p><p>◉　7,322 個 IP 位址</p><p>⌕　受到 12 家公司監控</p><hr><h3>關係 <button>編輯</button></h3><p>♙　未指派</p><p>▣　未設定層級</p><p>⌘　持續監控</p><hr><h3>聯絡人 <button>新增</button></h3><p>尚無聯絡人。</p><h3>備註 <button>新增備註</button></h3><p>建立備註以記錄資訊並與團隊成員協作。</p></aside></div>`;
}
